using System.Linq;
using Content.Client.Friends;
using Content.Client.Imperial.Roadmap.UI;
using Content.Shared.Friends;
using Content.Shared.Friends.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI.Elements;

/// <summary>
/// Панель для отображения членов фракции по группам.
/// Позволяет редактировать их задачу
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionGroupPanel : BorderedPanelContainer
{
    public Action<FactionMemberGroup, string>? ObjectiveSet;

    public FactionMemberGroup Group;

    public FactionGroupPanel(FactionMemberGroup group, FactionMenuAccess access, FactionMemberGroup self, string groupObjective = "")
    {
        RobustXamlLoader.Load(this);

        GroupNamePanel.PanelOverride = new StyleBoxFlat(FriendsSystem.FactionGroups[group].Item1);
        Group = group;
        if (group != FactionMemberGroup.None)
            GroupNameText.Text = FriendsSystem.FactionGroups[group].Item2;

        SetObjectiveButton.Visible = group != FactionMemberGroup.None;
        ObjectivePanel.Visible = group != FactionMemberGroup.None;

        Objective.Text = groupObjective;
        SetObjectiveButtonText.Text = groupObjective != string.Empty ? "Изменить" : "Назначить задачу";
        ObjectivePanel.Visible = groupObjective != string.Empty && group != FactionMemberGroup.None;

        SetObjectiveButton.Visible = access switch
        {
            FactionMenuAccess.None => false,
            FactionMenuAccess.Group => self == group && group != FactionMemberGroup.None,
            FactionMenuAccess.Full => group != FactionMemberGroup.None,
            _ => false
        };

        ObjectiveEdit.OnTextEntered += args => ObjectiveSet?.Invoke(group, args.Text);

        SetObjectiveButton.OnPressed += args =>
        {
            SetObjectiveButton.Visible = false;
            ObjectiveEditPanel.Visible = true;
            ObjectiveEdit.Text = groupObjective;
        };

        ObjectiveEdit.OnTextChanged += args =>
        {
            ObjectiveEditTip.Visible = args.Text == string.Empty;
            if (args.Text.Length > 32)
                ObjectiveEdit.SetText(args.Text.Substring(0, 32));
        };

        ObjectiveEdit.OnTextEntered += args => ObjectiveSet?.Invoke(group, args.Text);
    }
}
