using System.Linq;
using Content.Client.Friends;
using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI.Elements;

/// <summary>
/// Панель, содержащая всю необходимую информацию о члене фракции
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionMenuEntry : Control
{
    public Action<int, string>? ObjectiveSet;
    public Action<int, FactionMemberGroup>? GroupSet;
    public Action<int>? RemoveButtonPressed;

    public FactionMenuEntry(int ent, FactionMemberData data, string objective)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NameLabel.SetMessage($"{data.JobPrefix} {data.Name}");
        if (data.Group == FactionMemberGroup.None)
        {
            for (var i = 0; i < FriendsSystem.FactionGroups.Count; i++)
            {
                if (FriendsSystem.FactionGroups.ElementAt(i).Key == FactionMemberGroup.None)
                    continue;

                var item = FriendsSystem.FactionGroups.ElementAt(i).Value;
                GroupSelector.AddItem(item.Item2, item.Item1, i);
            }
            GroupSelector.Select(0);
            Objective.Visible = false;
            GroupSelector.OnItemSelected += args => GroupSet?.Invoke(ent, FriendsSystem.FactionGroups.ElementAt(args.Id).Key);
        }
        else
        {
            // Переключение видимости элементов
            GroupRemoveButton.Visible = true;
            GroupSelector.Visible = false;
            Objective.Visible = objective != string.Empty;

            Objective.Text = objective;

            // Кнопка исключения из группы
            GroupRemoveButtonText.Text = FriendsSystem.FactionGroups[data.Group].Item2;
            GroupRemoveButton.ModulateSelfOverride = FriendsSystem.FactionGroups[data.Group].Item1;
            GroupRemoveButton.OnPressed += args => GroupSet?.Invoke(ent, FactionMemberGroup.None);
        }

        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke(ent);
    }
}

public sealed class ColoredOptionButton : OptionButton
{
    private Color? _cachedColor;
    public void AddItem(string label, Color color, int? id = null)
    {
        _cachedColor = color;
        AddItem(label, id);
    }

    public override void ButtonOverride(Button button)
    {
        base.ButtonOverride(button);

        button.ModulateSelfOverride = _cachedColor;
        _cachedColor = null;
    }
}
