using System;
using Content.Shared.Imperial.Medieval.Ships.Helm;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;

namespace Content.Client.Imperial.Medieval.Ships.Helm;

[UsedImplicitly]
[GenerateTypedNameReferences]
public sealed partial class HelmMenu : DefaultWindow
{
    private readonly SharedAudioSystem _audio;
    private readonly IPlayerManager _playerManager;

    private TextureRect HelmBackgroundRect => FindControl<TextureRect>("HelmBackground");
    private TextureRect HelmIndicatorRect => FindControl<TextureRect>("HelmIndecator");

    private bool _isIndicatorOutOfCenter = false;
    private bool _isWheelOutOfMaxed = false;

    private float _lastRotation = 0f;

    public HelmMenu()
    {
        RobustXamlLoader.Load(this);

        _playerManager = IoCManager.Resolve<IPlayerManager>();

        var systemManager = IoCManager.Resolve<IEntitySystemManager>();
        _audio = systemManager.GetEntitySystem<SharedAudioSystem>();

        OnResized += () => ArrangeIndicator(_lastRotation);
    }

    public void UpdateState(HelmBoundUserInterfaceState state)
    {
        _lastRotation = state.HelmRotation;

        ArrangeIndicator(_lastRotation);

        if (_playerManager.LocalSession is not { } localSession)
            return;

        bool currentlyInCenter = _lastRotation < 5f && _lastRotation > -5f;

        if (currentlyInCenter)
        {
            if (_isIndicatorOutOfCenter)
            {
                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Imperial/Medieval/jumping_on_wooden_floor.ogg"), localSession);
                _isIndicatorOutOfCenter = false;
            }
        }
        else
        {
            _isIndicatorOutOfCenter = true;
        }

        bool currentlyMaxed = Math.Abs(_lastRotation) == 180f;

        if (currentlyMaxed)
        {
            if (_isWheelOutOfMaxed)
            {
                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Imperial/Medieval/wooden_door_slamming_open.ogg"), localSession);
                _isWheelOutOfMaxed = false;
            }
        }
        else
        {
            _isWheelOutOfMaxed = true;
        }
    }

    private void ArrangeIndicator(float rotation)
    {
        float pct = (rotation + 180f) / 360f;
        pct = Math.Clamp(pct, 0f, 1f);

        float bgWidth = HelmBackgroundRect.Width > 0
            ? HelmBackgroundRect.Width
            : (HelmBackgroundRect.Texture?.Width * HelmBackgroundRect.TextureScale.X ?? 200f);

        float indicatorWidth = HelmIndicatorRect.Width > 0
            ? HelmIndicatorRect.Width
            : (HelmIndicatorRect.Texture?.Width * HelmIndicatorRect.TextureScale.X ?? 16f);

        float bgHeight = HelmBackgroundRect.Height > 0
            ? HelmBackgroundRect.Height
            : (HelmBackgroundRect.Texture?.Height * HelmBackgroundRect.TextureScale.Y ?? 16f);

        float indicatorHeight = HelmIndicatorRect.Height > 0
            ? HelmIndicatorRect.Height
            : (HelmIndicatorRect.Texture?.Height * HelmIndicatorRect.TextureScale.Y ?? 32f);

        // --- НАЧАЛО НАСТРОЙКИ ОГРАНИЧЕНИЯ ХОДА ---

        // Отступ от фактического края полосы до центра крайнего положения штурвала (в пикселях).
        float edgeOffset = 30f;

        // Доступная ширина для перемещения центра штурвала (общая ширина минус два отступа по краям)
        float walkableWidth = bgWidth - (edgeOffset * 2f);

        // Итоговая позиция: минимальный отступ + доля от доступной дорожки - половина ширины самого штурвала
        float targetLeftMargin = edgeOffset + (walkableWidth * pct) - (indicatorWidth / 2f);

        // --- КОНЕЦ НАСТРОЙКИ ---

        float targetTopMargin = (bgHeight / 2f) - (indicatorHeight / 2f);

        LayoutContainer.SetMarginTop(HelmIndicatorRect, targetTopMargin);
        LayoutContainer.SetMarginLeft(HelmIndicatorRect, targetLeftMargin);
    }
}
