using System;
using Content.Shared.Imperial.Medieval.Ships.Helm;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Ships.Helm;

[UsedImplicitly]
[GenerateTypedNameReferences]
public sealed partial class HelmMenu : DefaultWindow
{
    public event Action? OnRotateLeft;
    public event Action? OnRotateRight;
    public event Action? OnCenter;

    public HelmMenu()
    {
        RobustXamlLoader.Load(this);

        RotateLeftButton.OnButtonDown += _ => OnRotateLeft?.Invoke();
        RotateRightButton.OnButtonDown += _ => OnRotateRight?.Invoke();
        CenterButton.OnButtonDown += _ => OnCenter?.Invoke();
    }

    public void UpdateState(HelmBoundUserInterfaceState state)
    {
        var rotation = state.HelmRotation;

        if (rotation < 0f)
            DirectionLabel.Text = Loc.GetString("helm-ui-direction-left");
        else if (rotation > 0f)
            DirectionLabel.Text = Loc.GetString("helm-ui-direction-right");
        else
            DirectionLabel.Text = Loc.GetString("helm-ui-direction-center");

        RotationLabel.Text = $"{MathF.Abs(rotation):0.##}°";
    }
}
