using Content.Shared.Imperial.Medieval.PlayerCreations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class BookEntry : Control
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public BookEntry(CreationBook book, Action? onAccept = null, Action? onDecline = null, bool acceptEnabled = true)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BookName.SetMessage(book.Name);
        BookAuthor.SetMessage(book.Author);

        ReadButton.OnPressed += _ =>
        {
            var window = new BookPreviewWindow(book.Text);
            window.Open();
        };

        MoreButton.OnPressed += _ => OpenMoreWindow(book);

        DeclineButton.OnPressed += _ => onDecline?.Invoke();

        if (!acceptEnabled)
            AcceptButton.Visible = false;
        else
            AcceptButton.OnPressed += _ => onAccept?.Invoke();
    }

    private void OpenMoreWindow(CreationBook book)
    {
        var moreWindow = new MoreWindow();

        var moreDict = new Dictionary<string, string>();
        moreDict.Add(Loc.GetString("creations-info-name"), book.Name);
        moreDict.Add(Loc.GetString("creations-info-description"), book.Description);
        moreDict.Add(Loc.GetString("creations-info-author"), book.Author);
        var data = _playerManager.GetPlayerData(book.SenderUserId);
        moreDict.Add(Loc.GetString("creations-info-author-nick"), data.UserName);
        var utc = DateTime.SpecifyKind(book.CreationTime, DateTimeKind.Utc);
        var offset = new DateTimeOffset(utc).ToOffset(TimeSpan.FromHours(3));
        moreDict.Add(Loc.GetString("creations-info-creation-time"), offset.ToString("dd.MM.yyyy HH:mm"));

        moreWindow.Populate(moreDict);
        moreWindow.Open();
    }
}
