using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class BookPreviewWindow : DefaultWindow
{
    public BookPreviewWindow(string text)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Populate(text);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        if (!TextContent.TryGetStyleProperty<Font>("font", out var font))
            return;

        float descent = font.GetDescent(UIScale);

        TextContent.Margin = new Thickness(0, descent, 0, 0);

    }



    public void Populate(string text)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(text);

        msg.AddMarkupPermissive("\r\n");

        TextContent.SetMessage(msg);

    }

}
