using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class BookTab : Control
{
    public BookTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddEntry(BookEntry entry)
    {
        BookContainer.AddChild(entry);
    }

    public void RemoveEntry(BookEntry entry)
    {
        BookContainer.RemoveChild(entry);
        entry.Dispose();
    }
}
