using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class CreationsPanel : DefaultWindow
{
    public CreationsPanel()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("creations-panel-tab-paintings-incoming"));
    }

    public PaintingTab IncomingPaintingsTab => IncomingPaintings;
}
