using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.PlayerCreations.Paintings;
using OpenToolkit.GraphicsLibraryFramework;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;
using YamlDotNet.Core.Tokens;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class MoreWindow : DefaultWindow
{
    public MoreWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate(Dictionary<string, string> content)
    {
        foreach (var (key, value) in content)
        {
            var keyLabel = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Stretch,
                SetWidth = 150,
            };
            var valueLabel = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Stretch,
                SetWidth = 150,
            };

            keyLabel.Margin = new Thickness(0, 0, 5, 20);
            valueLabel.Margin = new Thickness(0, 0, 0, 20);

            Contents.AddChild(keyLabel);
            Contents.AddChild(valueLabel);

            keyLabel.SetMessage(key);
            valueLabel.SetMessage(value);
        }
    }

}
