using Content.Shared.Imperial.Medieval.PlayerCreations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class PaintingEntry : Control
{
    public PaintingEntry(CreationPaintingMessage message, Action? onAccept = null, Action? onDecline = null)
    {
        RobustXamlLoader.Load(this);

        PaintingView.SetEntity(message.Painting);

        PaintingName.SetMessage(message.Name);
        PaintingAuthor.SetMessage(message.Author);

        AcceptButton.OnPressed += _ => onAccept?.Invoke();
        DeclineButton.OnPressed += _ => onDecline?.Invoke();
    }
}
