using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class PaintingTab : Control
{
    public PaintingTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddEntry(PaintingEntry entry)
    {
        PaintingContainer.AddChild(entry);

        PaintingContainer.InvalidateArrange();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        PaintingContainer.InvalidateMeasure();
        PaintingContainer.InvalidateArrange();
    }

    public void RemoveEntry(PaintingEntry entry)
    {
        PaintingContainer.RemoveChild(entry);
        entry.Dispose();
    }
}
