using Content.Shared.Imperial.Medieval.PlayerCreations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Administration;

[GenerateTypedNameReferences]
public sealed partial class PaintingEntry : Control
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public PaintingEntry(IClyde clyde, CreationPaintingMessage message, Action? onAccept = null, Action? onDecline = null, bool acceptEnabled = true, bool editable = false, Action<EditedCreationData>? onEdit = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var texture = PaintingHelper.GetTextureFromColorArray(clyde, message.Painting);

        PaintingView.Texture = texture;

        PaintingName.SetMessage(message.Name);
        PaintingAuthor.SetMessage(message.Author);

        MoreButton.OnPressed += _ => OpenMoreWindow(message, editable, onEdit);

        DeclineButton.OnPressed += _ => onDecline?.Invoke();

        if (!acceptEnabled)
            AcceptButton.Visible = false;
        else
            AcceptButton.OnPressed += _ => onAccept?.Invoke();
    }

    private void OpenMoreWindow(CreationPaintingMessage message, bool editable, Action<EditedCreationData>? onEdit)
    {
        var moreWindow = new MoreWindow();

        var moreDict = new Dictionary<string, string>();
        moreDict.Add(Loc.GetString("creations-info-name"), message.Name);
        moreDict.Add(Loc.GetString("creations-info-description"), message.Description);
        moreDict.Add(Loc.GetString("creations-info-author"), message.Author);
        moreDict.Add(Loc.GetString("creations-info-author-nick"), message.SenderUserName);
        var utc = DateTime.SpecifyKind(message.CreationTime, DateTimeKind.Utc);
        var offset = new DateTimeOffset(utc).ToOffset(TimeSpan.FromHours(3));
        moreDict.Add(Loc.GetString("creations-info-creation-time"), offset.ToString("dd.MM.yyyy HH:mm"));

        moreWindow.PopulatePainting(message, editable, onEdit);
        moreWindow.OpenCentered();
    }
}
