using Content.Shared.Imperial.Medieval.Waystones;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.State;

namespace Content.Client.Imperial.Medieval.Waystones.UI;

[GenerateTypedNameReferences]
public sealed partial class WaystoneAdminMenu : DefaultWindow
{
    public event Action<int, int, bool>? OnApplyPressed;

    public WaystoneAdminMenu()
    {
        RobustXamlLoader.Load(this);

        ApplyButton.OnPressed += _ =>
        {
            if (int.TryParse(DeparturePriceInput.Text, out var depPrice) &&
                int.TryParse(ArrivalPriceInput.Text, out var arrPrice))
            {
                OnApplyPressed?.Invoke(depPrice, arrPrice, StateToggle.Pressed);
                Close();
            }
        };
    }

    public void UpdateValues(int departurePrice, int arrivalPrice, bool isEnable)
    {
        DeparturePriceInput.Text = departurePrice.ToString();
        ArrivalPriceInput.Text = arrivalPrice.ToString();
        StateToggle.Pressed = isEnable;
    }
}
