using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.WarningOnAttach
{
    [GenerateTypedNameReferences]
    public sealed partial class AttachWarningWindow : DefaultWindow
    {
        public AttachWarningWindow(string rules)
        {
            RobustXamlLoader.Load(this);

            CloseButton.Visible = false;

            RequestButton.Text = "Сначала прочитайте текст выше";
            TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(rules));
            RequestButton.Disabled = true;

            Checkbox.OnToggled += args =>
            {
                RequestButton.Disabled = !args.Pressed;
                RequestButton.Text = args.Pressed ? "Закрыть" : "Сначала прочитайте текст выше";
            };

            RequestButton.OnPressed += _ => Close();
        }
    }
}
