using Content.Client.Imperial.UI.Windows;
using Content.Shared.Imperial.Medieval.Exam.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamStartWindow : BaseImperialWindow
{
    private const string Text = """
        "Вы собираетесь начать тест. Вам будет дано 20 вопросов с несколькими вариантами ответов. Для успешного
        прохождения теста, вы должны допустить не более 2-х ошибок. Если вы
        завалите тест - следующая попытка будет доступна не ранее, чем через 24 часа.

        У вас есть неограниченное время на прохождение теста, однако если вы закроете
        тест раньше, чем ответите на все вопросы - вам будет засчитан провал.

        Для справки используйте материалы из wiki.imperialspace.net, а именно:
        СРП отделов, СРП командования, СРП Службы безопасности, КЗ, ОПРС, Страница ГСБ
        и гайдлайны по редактированию Индекса Продуктивности. Также не забывайте
        про здравый смысл!"
        """;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _userInterface = default!;

    private readonly ExamSystem _exam;

    private ExamUIController Exam => _userInterface.GetUIController<ExamUIController>();

    public ExamStartWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _exam = _entity.System<ExamSystem>();
    }

    public void Refresh(string prototype)
    {
        if (!_prototype.TryIndex<ExamPrototype>(prototype, out var exam))
            return;

        if (exam.IconPath != ResPath.Empty)
            Icon.TexturePath = exam.IconPath.ToString();

        StartButton.Text = "Я готов, начинаем тестирование!";
        StartButton.OnPressed += _ =>
        {
            Exam.OpenWindow(prototype);
            Close();
        };

        var message = new FormattedMessage();
        message.TryAddMarkup(Text, out _);
        TextLabel.SetMessage(message);

        if (!_exam.LastAttempts.TryGetValue(prototype, out var date))
            return;

        var timeSinceLastAttempt = DateTime.Now - date;
        var cooldown = TimeSpan.FromHours(24);

        if (timeSinceLastAttempt >= cooldown)
            return;

        var remaining = cooldown - timeSinceLastAttempt;
        StartButton.Text = $"Осталось {Math.Floor(remaining.TotalHours)} часов {remaining.Minutes} минут до следующей попытки";
        StartButton.Disabled = true;
    }
}
