using Content.Shared.Imperial.Medieval.Exam.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamTaskControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IRobustRandom _random = default!;

    public event Action<ProtoId<ExamTaskPrototype>, int>? Pressed;

    private readonly List<ExamTaskInputControl> _controls = new();
    private readonly ProtoId<ExamTaskPrototype> _protoId;

    public ExamTaskControl(ProtoId<ExamTaskPrototype> protoProtoId, int id)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _protoId = protoProtoId;

        if (!_prototype.TryIndex(protoProtoId, out var prototype))
            return;

        SetDescription(Loc.GetString("ui-imperial-exam-task-label", ("index", id + 1), ("description", prototype.Description)));
        Container.Children.Clear();

        var inputs = new List<ExamTaskInputControl>();
        var controlIndex = 0;
        foreach (var answer in prototype.Answers)
        {
            var input = new ExamTaskInputControl(answer, controlIndex);
            input.OnPressed += OnPressed;

            _controls.Add(input);
            inputs.Add(input);

            controlIndex++;
        }

        _random.Shuffle(inputs);
        foreach (var input in inputs)
        {
            Container.AddChild(input);
        }
    }

    private void SetDescription(string text)
    {
        var message = new FormattedMessage();
        message.TryAddMarkup(Loc.GetString(text), out _);
        DescriptionLabel.SetMessage(message);
    }

    private void OnPressed(int answer)
    {
        for (var i = 0; i < _controls.Count; i++)
        {
            if (i != answer)
                _controls[i].SetToggled(false);
        }

        Pressed?.Invoke(_protoId, answer);
    }
}
