using Content.Client.Imperial.UI.Windows;
using Content.Shared.Imperial.Medieval.Exam;
using Content.Shared.Imperial.Medieval.Exam.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamWindow : BaseImperialWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<ProtoId<ExamPrototype>, IReadOnlyDictionary<string, int>>? Sent;

    private readonly Dictionary<string, int> _answers = new();
    private ProtoId<ExamPrototype>? _exam;
    private int _answerCount;

    public ExamWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetExam(null);

        SendButton.OnPressed += OnSendPress;

        foreach (var exam in _prototype.EnumeratePrototypes<ExamPrototype>())
        {
            var button = new Button();
            button.Text = Loc.GetString(exam.Name);
            button.OnPressed += _ => OnExamSelected(exam);
            ExamsScroll.AddChild(button);
        }
    }

    public override void Close()
    {
        base.Close();

        SetExam(null);
    }

    private void OnExamSelected(ExamPrototype exam)
    {
        SetExam(exam);
    }

    private void SetExam(ExamPrototype? exam)
    {
        // Menu state
        ExamsContainer.Visible = exam is not null;
        ExamsSelectionContainer.Visible = exam is null;

        if (exam is null)
            return;

        _exam = exam.ID;

        ExamName.Text = Loc.GetString(exam.Name);
        if (exam.IconPath != ResPath.Empty)
            ExamIcon.TexturePath = exam.IconPath.ToString();

        TaskContainers.Children.Clear();

        _answerCount = exam.Tasks.Count;

        var index = 0;
        foreach (var taskId in exam.Tasks)
        {
            var task = new ExamTaskControl(taskId, index);
            task.Pressed += OnTaskPressed;

            TaskContainers.AddChild(task);
            index++;
        }
    }

    private void OnSendPress(BaseButton.ButtonEventArgs _)
    {
        if (_exam is null)
            return;

        Sent?.Invoke(_exam.Value, _answers);
    }

    private void OnTaskPressed(ProtoId<ExamTaskPrototype> task, int answer)
    {
        _answers[task] = answer;
        SendButton.Disabled = _answers.Count != _answerCount;
    }
}
