using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[PublicAPI]
[GenerateTypedNameReferences]
public sealed partial class ExamTaskInputControl : Control
{
    public event Action<int>? OnPressed;

    public ExamTaskInputControl(LocId text, int index)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetMessage(text);
        Checkbox.OnPressed += _ => OnPressed?.Invoke(index);
    }

    public void SetMessage(string text)
    {
        var message = new FormattedMessage();
        message.TryAddMarkup(Loc.GetString(text), out _);
        Label.SetMessage(message);
    }

    public void SetToggled(bool value)
    {
        Checkbox.Pressed = value;
    }
}
