using Content.Shared.Imperial.Medieval.Exam;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamTaskControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<LocId>? Pressed;

    private readonly List<ExamTaskInputControl> _controls = new();

    public ExamTaskControl(ProtoId<ExamTaskPrototype> protoId, int index)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!_prototype.TryIndex(protoId, out var prototype))
            return;

        DescriptionLabel.Text = $"{index + 1}. {Loc.GetString(prototype.Description)}";

        Container.Children.Clear();
        foreach (var answer in prototype.Answers)
        {
            var input = new ExamTaskInputControl(answer);
            input.OnPressed += () => OnPressed(input, answer);
            _controls.Add(input);
            Container.AddChild(input);
        }
    }

    private void OnPressed(ExamTaskInputControl checkBox, LocId answer)
    {
        foreach (var box in _controls)
        {
            if (box != checkBox)
                box.SetToggled(false);
        }

        Pressed?.Invoke(answer);
    }
}
