using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamTaskInputControl : Control
{
    public event Action? OnPressed;

    public ExamTaskInputControl(LocId text)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Label.Text = Loc.GetString(text);
        Checkbox.OnCheckboxToggled += _ => OnPressed?.Invoke();
    }

    public void SetToggled(bool value)
    {
        Checkbox.Toggled = value;
    }
}
