using Content.Client.Imperial.UI.Windows;
using Content.Shared.Imperial.Medieval.Exam;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Exam.UI;

[GenerateTypedNameReferences]
public sealed partial class ExamWindow : BaseImperialWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly Dictionary<ExamTaskControl, LocId> _answers = new();
    private int _answerCount;
    private ExamPrototype? _selectedExam;

    public ExamWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetExam(null);

        foreach (var exam in _prototype.EnumeratePrototypes<ExamPrototype>())
        {
            var button = new Button();
            button.Text = Loc.GetString(exam.Name);
            button.OnPressed += _ => OnExamSelected(exam);
            ExamsScroll.AddChild(button);
        }
    }

    public override void Close()
    {
        base.Close();

        SetExam(null);
    }

    public void UpdateState(ExamBuiState state)
    {

    }

    private void OnExamSelected(ExamPrototype exam)
    {
        SetExam(exam);
    }

    private void SetExam(ExamPrototype? exam)
    {
        _selectedExam = exam;

        // Menu state
        ExamsContainer.Visible = exam is not null;
        ExamsSelectionContainer.Visible = exam is null;

        if (exam is null)
            return;

        ExamName.Text = Loc.GetString(exam.Name);
        if (exam.IconPath != ResPath.Empty)
            ExamIcon.TexturePath = exam.IconPath.ToString();

        TaskContainers.Children.Clear();

        var index = 0;
        foreach (var taskId in exam.Tasks)
        {
            var task = new ExamTaskControl(taskId, index);
            task.Pressed += answer => OnTaskPressed(task, answer);

            TaskContainers.AddChild(task);
            index++;
        }
    }

    private void OnTaskPressed(ExamTaskControl task, LocId answer)
    {
        _answers[task] = answer;
    }
}
