"Sprite":
- changed-files:
  - any-glob-to-any-file:
    - "**/Imperial/**/*.png"
    - "**/Imperial/*.png"

"Grid":
- changed-files:
  - any-glob-to-any-file:
    - "Resources/Maps/Imperial/**/*.yml"
    - "Resources/Prototypes/Imperial/Maps/**/*.yml"

"UI":
- changed-files:
  - any-glob-to-any-file: "**/*.xaml*"

"Shaders":
- changed-files:
  - any-glob-to-any-file: "**/*.swsl"

"Audio":
- changed-files:
  - any-glob-to-any-file: "**/Imperial/**/*.ogg"

"C#":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

"Prototypes":
- changed-files:
  - any-glob-to-any-file: "Resources/Prototypes/Imperial/**/*.yml"

# Wiz Changes

"Resprite":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.png"
    - any-glob-to-any-file:
      - "!**/Imperial/**/*.png"
      - "!**/Imperial/*.png"

"Change Wiz Code":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.cs"
    - any-glob-to-any-file: "!*/Imperial/**"

"Change Wiz Prototypes":
- all:
  - changed-files:
    - any-glob-to-any-file: "Resources/Prototypes/**/*.yml"
    - any-glob-to-any-file: "!Resources/Prototypes/Imperial/**"

"Change Wiz Audio":
- all:
  - changed-files:
    - any-glob-to-any-file: "**/*.ogg"
    - any-glob-to-any-file: "!**/Imperial/**"
