using System.Numerics;
using Content.Shared.Imperial.Medieval.RemoteStore;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;

namespace Content.Client.Imperial.Medieval.RemoteStore;

[GenerateTypedNameReferences]
public sealed partial class StoreChangerWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;
    private readonly SpriteSystem _sprite;
    public event Action<EntityUid>? OnStoreClicked;

    public StoreChangerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _ent.System<SpriteSystem>();
    }

    /// <summary>
    /// Обновляет сетку магазинов на основе полученного состояния.
    /// </summary>
    public void UpdateStores(RemoteStoreUIState state)
    {
        StoreGrid.RemoveAllChildren();
        foreach (var entry in state.Stores)
        {
            // Создаем кнопку с текстурой
            var button = new TextureButton
            {
                // Устанавливаем текстуру из SpriteSpecifier
                TextureNormal = _sprite.Frame0(entry.Icon),
                ToolTip = entry.Name,
                Scale = new Vector2(1.2f, 1.2f),
                MinSize = new Vector2(48, 48), // Фиксированный размер для единообразия сетки
            };

            // При нажатии отправляем Uid магазина
            button.OnPressed += _ => OnStoreClicked?.Invoke(entry.Uid);

            // Добавляем кнопку в сетку
            StoreGrid.AddChild(button);
        }
    }
}
