using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.PlayerCreations.Paintings;
using OpenToolkit.GraphicsLibraryFramework;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Paintings;

[GenerateTypedNameReferences]
public sealed partial class EaselWindow : DefaultWindow
{
    public Color[] CanvasTexture => CanvasControl.Pixels;
    public CanvasDrawControl Canvas => CanvasControl;

    public Action<string, string>? OnSend;

    public EaselWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CanvasColor.OnColorChanged += OnColorChanged;
        CanvasColor.Color = Color.Black;

        CanvasControl.SelectorSliders = CanvasColor;

        Send.OnPressed += _ =>
        {
            var sendDialog = new PaintingSendDialogWindow(OnSend);
            OnClose += () => sendDialog.Close();
            sendDialog.OpenCentered();
        };
    }

    public static List<List<T>> To2DList<T>(List<T> flatList, int width)
    {
        var result = new List<List<T>>();
        for (int i = 0; i < flatList.Count; i += width)
        {
            var row = flatList.Skip(i).Take(width).ToList();
            result.Add(row);
        }
        return result;
    }

    public void Populate(EaselBoundUserInterfaceState state)
    {
        var pixels = state.Texture;

        CanvasControl.Pixels = pixels;
    }

    private void OnColorChanged(Color color)
    {
        CanvasControl.DrawColor = color;
    }

    protected override void Resized()
    {
        base.Resized();

        CanvasControl.SetSize = new Vector2(Height / 1.5f, Height / 1.5f);
    }

}
