using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Paintings;

[GenerateTypedNameReferences]
public sealed partial class PaintingWindow : DefaultWindow
{
    public PaintingWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate(Texture texture)
    {
        PaintingTexture.Texture = texture;
    }

}
