using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.PlayerCreations.Paintings;
using OpenToolkit.GraphicsLibraryFramework;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Paintings;

[GenerateTypedNameReferences]
public sealed partial class PaintingWindow : DefaultWindow
{
    public PaintingWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate(Texture texture)
    {
        PaintingTexture.Texture = texture;
    }

}
