using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Paintings;

[GenerateTypedNameReferences]
public sealed partial class PaintingSendDialogWindow : DefaultWindow
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;

    private SharedPopupSystem _popup;

    public PaintingSendDialogWindow(Action<string, string, string>? onConfirm)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _popup = _systemManager.GetEntitySystem<SharedPopupSystem>();

        PaintingNameField.Placeholder = new Rope.Leaf(Loc.GetString("easel-window-confirmation-name-placeholder"));
        PaintingDescriptionField.Placeholder = new Rope.Leaf(Loc.GetString("easel-window-confirmation-description-placeholder"));
        PaintingAuthorField.Placeholder = new Rope.Leaf(Loc.GetString("easel-window-confirmation-author-placeholder"));


        SendButton.OnPressed += _ =>
        {
            if (PaintingNameField.TextLength is < 3 or >= 20)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("easel-window-confirmation-name-length", ("min", 3), ("max", 20)),
                        _playerManager.LocalSession);
                }

                return;
            }

            if (PaintingDescriptionField.TextLength >= 200)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("easel-window-confirmation-description-length", ("max", 200)),
                        _playerManager.LocalSession);
                }

                return;
            }

            if (PaintingAuthorField.TextLength is < 5 or >= 40)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("easel-window-confirmation-author-length", ("min", 5), ("max", 40)),
                        _playerManager.LocalSession);
                }

                return;
            }

            var name = Rope.Collapse(PaintingNameField.TextRope);
            var description = Rope.Collapse(PaintingDescriptionField.TextRope);
            var author = Rope.Collapse(PaintingAuthorField.TextRope);

            onConfirm?.Invoke(name, description, author);
            Close();
        };

    }


}
