using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using Content.Client.Popups;
using Content.Shared.Imperial.Medieval.PlayerCreations.Paintings;
using Content.Shared.Popups;
using OpenToolkit.GraphicsLibraryFramework;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Paintings;

[GenerateTypedNameReferences]
public sealed partial class PaintingSendDialogWindow : DefaultWindow
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IEntitySystemManager _systemManager = default!;

    private SharedPopupSystem _popup;

    public PaintingSendDialogWindow(Action<string, string>? onConfirm)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _popup = _systemManager.GetEntitySystem<SharedPopupSystem>();

        PaintingNameField.Placeholder = new Rope.Leaf(Loc.GetString("easel-window-confirmation-name-placeholder"));
        PaintingAuthorField.Placeholder = new Rope.Leaf(Loc.GetString("easel-window-confirmation-author-placeholder"));


        SendButton.OnPressed += _ =>
        {
            if (PaintingNameField.TextLength is < 3 or >= 20)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("easel-window-confirmation-name-length"),
                        _playerManager.LocalSession);
                }

                return;
            }

            if (PaintingAuthorField.TextLength is < 5 or >= 40)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("easel-window-confirmation-author-length"),
                        _playerManager.LocalSession);
                }

                return;
            }

            var name = Rope.Collapse(PaintingNameField.TextRope);
            var author = Rope.Collapse(PaintingAuthorField.TextRope);

            onConfirm?.Invoke(name, author);
            Logger.Debug("Invoked");
            Logger.Debug($"{onConfirm != null}");
            Close();
        };

    }


}
