using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Alchemy;

[GenerateTypedNameReferences]
public sealed partial class AlchemyWindow : FancyWindow
{
    public AlchemyWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
