using Content.Client.IoC;
using Content.Client.Resources;
using Content.Shared.Imperial.Medieval.Trading;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class GuildCardControl : Control
{
    public Guild Guild;
    public Action? OnPressed;

    private readonly NetEntity? _user;

    public GuildCardControl(Guild guild, NetEntity? user)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Guild = guild;
        _user = user;

        GuildName.SetMessage(guild.Name);
        var guildType = Loc.GetString($"trading-guild-type-{guild.TypePrototype.Id}");
        GuildType.Text = Loc.GetString("trading-ui-guild-type", ("type", guildType));

        // вероятно не лучшая идея, лучше загружать rsi
        GuildIcon.Texture = StaticIoC.ResC.GetTexture(Guild.IconPath);

        GuildButton.OnPressed += _ => OnPressed?.Invoke();
        ReputationBarContainer.OnResized += ResizeReputationBar;
    }

    private void ResizeReputationBar()
    {
        if (_user == null)
            return;

        var fraction = Math.Min(Guild.GetReputation(_user.Value), 100) / 100f;
        ReputationBar.SetHeight = ReputationBarContainer.Size.Y * fraction;
        RecolorReputationBar(fraction);
    }

    public void RecolorReputationBar(float fraction)
    {
        fraction = Math.Clamp(fraction, 0f, 1f);

        // здесь высчитывается цвет
        // меньше 0.5 -> увеличивается g. цвет из красного переходит в жёлтый
        // больше 0.5 -> уменьшается r. цвет из жёлтого переходит в зелёный
        var color = fraction < 0.5f
            ? new Color(1f, fraction * 2f, 0f)
            : new Color(2f * (1f - fraction), 1f, 0f);

        ReputationBar.Modulate = color;
    }
}
