using System.Linq;
using System.Numerics;
using Content.Client.Hands.Systems;
using Content.Client.Message;
using Content.Client.Popups;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Hands.Components;
using Content.Shared.Imperial.Medieval.Trading;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Input;
using Content.Shared.Inventory.VirtualItem;
using Content.Shared.Item;
using Content.Shared.Popups;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly HandsSystem _hands;

    public event Action<Guid>? OnBuy;
    public event Action<Guid>? OnSell;
    public event Action<Guid>? OnBuyOffer;
    public event Action<Guid>? OnSellOffer;
    public event Action<Guid>? OnSelectCommodity;
    public event Action<Guid>? OnSelectOffer;
    public event Action<int>? OnCreateSellOffer;
    public event Action<int>? OnPrepareUnitSellOffer;
    public event Action<Guid, int>? OnCreateUnitSellOffers;
    public event Action<Guid, int>? OnCreateBuyOffer;
    public event Action<int>? OnCreateBuyOfferFromHeld;
    public event Action<Guid>? OnCancelOffer;
    public event Action<Guid, int>? OnCreateBidReceipt;
    public event Action<NetEntity>? OnCollectStoredItem;
    public event Action<Guid>? OnCollectSaleRevenue;
    public event Action<NetEntity>? OnExamineItem;
    public event Action<Guid, EntProtoId>? OnExamineCommodity;
    public event Action<int>? OnWithdraw;
    public event Action<Guid>? OnBuyPublicListing;
    public event Action<Guid>? OnCancelPublicListing;
    public event Action<Guid, int>? OnListStagedItem;
    public event Action<Guid>? OnSellStagedItem;
    public event Action<Guid>? OnFulfillStagedItem;
    public event Action<Guid>? OnWithdrawStagedItem;
    public event Action<Guid>? OnCollectPublicSaleRevenue;

    private TradingUpdateState? _state;
    private TradingMarketSection _section = TradingMarketSection.Common;
    private ProtoId<GuildTypePrototype>? _category;
    private Guid? _selected;
    private Guid? _selectedOffer;
    private bool _updateSelectedPrice = true;
    private CurrencyPrototype? _currency;
    private StoreWithdrawWindow? _withdrawWindow;
    private TradingUnitSellWindow? _unitSellWindow;
    private Guid? _unitSellRequest;
    private TradingBidReceiptWindow? _bidReceiptWindow;
    private Guid? _bidReceiptOffer;
    private TradingHelpWindow? _helpWindow;
    private bool _management;
    private bool _archive;
    private bool _publicSellView;
    private readonly Dictionary<Guid, string> _stagedPriceText = new();
    private string? _heldItemName;
    private bool _trackingHands = true;
    private readonly Dictionary<EntProtoId, EntityUid> _prototypeExamineEntities = new();

    public TradingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _hands = _entities.System<HandsSystem>();
        _hands.OnPlayerSetActiveHand += OnActiveHandChanged;
        _hands.OnPlayerItemAdded += OnHeldItemChanged;
        _hands.OnPlayerItemRemoved += OnHeldItemChanged;
        _hands.OnPlayerHandsAdded += OnHandsAdded;
        _hands.OnPlayerHandsRemoved += OnHandsRemoved;

        CommonButton.OnPressed += _ => SelectSection(TradingMarketSection.Common);
        UniqueButton.OnPressed += _ => SelectSection(TradingMarketSection.Unique);
        ManagementButton.OnPressed += _ => SelectManagement();
        ArchiveButton.OnPressed += _ => SelectArchive();
        SearchBar.OnTextChanged += _ => RebuildItems();
        HelpButton.OnPressed += _ => OpenHelpWindow();
        WithdrawButton.OnPressed += _ => OpenWithdrawWindow();
        CreateBuyOrderButton.OnPressed += _ => CreateSelectedBuyOrder();
        CreateSellOfferButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateSellOffer, true);
        CreateUnitSellOfferButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnPrepareUnitSellOffer, true);
        CreateHeldBuyOrderButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateBuyOfferFromHeld);
        PublicBrowseButton.OnPressed += _ => SelectSection(TradingMarketSection.Common);
        PublicSellButton.OnPressed += _ => SelectPublicSell();
        OnResized += UpdateColumns;
    }

    public void UpdateState(TradingUpdateState state)
    {
        _state = state;
        Title = Loc.GetString(state.IsPublic
            ? "trading-ui-public-window-title"
            : "trading-ui-window-title");
        SearchBar.PlaceHolder = Loc.GetString(state.IsPublic
            ? "trading-ui-public-search-placeholder"
            : "trading-ui-market-search-placeholder");
        MarketOffersTitle.Text = Loc.GetString(state.IsPublic
            ? "trading-ui-public-market-offers-title"
            : "trading-ui-market-offers-title");
        if (state.IsPublic)
        {
            _section = TradingMarketSection.Common;
            _category = null;
            _management = false;
            _archive = false;
            _withdrawWindow?.Close();
            _unitSellWindow?.Close();
            _unitSellRequest = null;
            _bidReceiptWindow?.Close();
            _bidReceiptOffer = null;
        }
        else if (!state.IsOwner)
        {
            _section = TradingMarketSection.Unique;
            _category = null;
            _management = false;
            _archive = false;
            _withdrawWindow?.Close();
            _unitSellWindow?.Close();
            _unitSellRequest = null;
            _bidReceiptWindow?.Close();
            _bidReceiptOffer = null;
        }

        UpdateBalance();
        RebuildCategories();

        var previousSelection = _selected;
        if (_selected == null || state.Items.All(item => item.CommodityId != _selected.Value))
        {
            _selected = state.Items
                .FirstOrDefault(item => state.IsPublic || HasSection(item, _section))?.CommodityId;
        }

        if (_selected != previousSelection)
        {
            _selectedOffer = null;
            _updateSelectedPrice = true;
            if (_selected is { } selected)
                OnSelectCommodity?.Invoke(selected);
        }

        if (_selectedOffer is { } selectedOffer &&
            state.Offers.All(offer => offer.Id != selectedOffer))
        {
            _selectedOffer = null;
            _updateSelectedPrice = true;
        }

        RebuildItems();
        RebuildSelected();
        RebuildManagement();
        RebuildArchive();
        RebuildPublicSell();
        UpdateSectionVisibility();
        UpdateHeldItem();
        UpdateBidReceiptWindow();
    }

    private void SelectSection(TradingMarketSection section)
    {
        _management = false;
        _archive = false;
        _publicSellView = false;
        _section = section;
        _category = null;
        _selected = _state?.Items.FirstOrDefault(item => HasSection(item, section))?.CommodityId;
        _selectedOffer = null;
        _updateSelectedPrice = true;
        if (_selected is { } selected)
            OnSelectCommodity?.Invoke(selected);
        RebuildCategories();
        RebuildItems();
        RebuildSelected();
        UpdateSectionVisibility();
    }

    private void SelectManagement()
    {
        _management = true;
        _archive = false;
        _publicSellView = false;
        RebuildManagement();
        UpdateSectionVisibility();
    }

    private void SelectArchive()
    {
        _management = false;
        _archive = true;
        _publicSellView = false;
        RebuildArchive();
        UpdateSectionVisibility();
    }

    private void SelectPublicSell()
    {
        _management = false;
        _archive = false;
        _publicSellView = true;
        RebuildPublicSell();
        UpdateSectionVisibility();
    }

    private void UpdateSectionVisibility()
    {
        if (_state is { IsPublic: true })
        {
            _section = TradingMarketSection.Common;
            _management = false;
            _archive = false;
        }
        else if (_state is not { IsOwner: true })
        {
            _section = TradingMarketSection.Unique;
            _management = false;
            _archive = false;
        }

        var marketVisible = !_management && !_archive && !_publicSellView;
        MarketView.Visible = marketVisible;
        ManagementView.Visible = _management;
        ArchiveView.Visible = _archive;
        PublicSellView.Visible = _publicSellView;
        SearchBar.Visible = marketVisible;
        BalancePanel.Visible = _state is { IsOwner: true } or { IsPublic: true };
        HelpButton.Visible = _state?.IsOwner == true;
        WithdrawButton.Visible = _state?.IsOwner == true;
        CommonButton.Visible = _state?.IsOwner == true;
        UniqueButton.Visible = _state?.IsPublic != true;
        ManagementButton.Visible = _state?.IsOwner == true;
        ArchiveButton.Visible = _state?.IsOwner == true;
        PublicBrowseButton.Visible = _state?.IsPublic == true;
        PublicSellButton.Visible = _state?.IsPublic == true;
        OfferCreationPanel.Visible = marketVisible && _state?.IsOwner == true;
        BuyOrderPanel.Visible = _state?.IsOwner == true;
        CategoryPanel.Visible = marketVisible &&
                                _state?.IsOwner == true &&
                                _section == TradingMarketSection.Common;
    }

    private void UpdateBalance()
    {
        if (_state == null)
            return;

        _prototypes.TryIndex(_state.Currency, out _currency);
        var text = _state.Balance.ToString();
        if (_state.IsPublic)
            text = Loc.GetString("trading-ui-public-balance", ("amount", _state.Balance));
        else if (_currency != null)
            text = $"{Loc.GetString(_currency.DisplayName, ("amount", _state.Balance))}: {_state.Balance}";

        BalanceInfo.SetMarkup(text);
        WithdrawButton.Disabled = _state.Balance <= 0 || _currency?.CanWithdraw != true;
    }

    private void RebuildCategories()
    {
        CategoryContainer.DisposeAllChildren();
        CategoryContainer.Visible = !_management &&
                                    !_archive &&
                                    _section == TradingMarketSection.Common &&
                                    _state?.IsPublic != true;
        if (_management ||
            _archive ||
            _section != TradingMarketSection.Common ||
            _state == null ||
            _state.IsPublic)
        {
            return;
        }

        var all = new Button
        {
            Text = Loc.GetString("trading-ui-all-categories"),
            HorizontalExpand = true,
        };
        all.OnPressed += _ =>
        {
            _category = null;
            RebuildItems();
        };
        CategoryContainer.AddChild(all);

        var categories = _state.Items
            .Where(item => HasSection(item, TradingMarketSection.Common))
            .SelectMany(item => item.Categories)
            .Distinct()
            .OrderBy(GetCategoryName);
        foreach (var category in categories)
        {
            var captured = category;
            var button = new Button
            {
                Text = GetCategoryName(category),
                HorizontalExpand = true,
            };
            button.OnPressed += _ =>
            {
                _category = captured;
                RebuildItems();
            };
            CategoryContainer.AddChild(button);
        }
    }

    private string GetCategoryName(ProtoId<GuildTypePrototype> category)
    {
        return Loc.GetString($"trading-guild-type-{category.Id}");
    }

    private void RebuildItems()
    {
        ItemsGrid.DisposeAllChildren();
        if (_management || _archive || _state == null)
            return;

        var search = SearchBar.Text.Trim();
        var filtered = _state.Items
            .Where(item => _state.IsPublic
                ? string.IsNullOrEmpty(search) ||
                  item.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase)
                : string.IsNullOrEmpty(search)
                ? HasSection(item, _section) &&
                  (_section == TradingMarketSection.Unique || _category == null || item.Categories.Contains(_category.Value))
                : item.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(item => item.DisplayName);

        foreach (var item in filtered)
        {
            ItemsGrid.AddChild(CreateCard(item));
        }

        if (_state.IsPublic)
        {
            var filteredListings = _state.PublicListings
                .Where(listing => string.IsNullOrEmpty(search) ||
                                   listing.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase))
                .OrderBy(listing => listing.DisplayName);

            foreach (var listing in filteredListings)
            {
                ItemsGrid.AddChild(CreatePublicListingCard(listing));
            }
        }

        UpdateColumns();
    }

    private Control CreatePublicListingCard(PublicListingState listing)
    {
        var panel = CreateCardPanel("#4e4638");
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var previewSlot = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            MinHeight = 100,
            SetHeight = 100,
            Align = BoxContainer.AlignMode.Center,
        };
        var preview = CreateItemPreview(listing.ProductEntity, listing.PreviewEntity, new Vector2(80, 80), null);
        preview.HorizontalAlignment = HAlignment.Center;
        previewSlot.AddChild(preview);
        content.AddChild(previewSlot);
        content.AddChild(CreateCardNamePanel(
            listing.DisplayName,
            Loc.GetString("trading-ui-public-listing-seller", ("seller", listing.SellerName)),
            Color.White));

        var actions = CreateCardActionsRow();
        if (listing.IsOwn)
        {
            var cancel = new Button
            {
                Text = Loc.GetString("trading-ui-cancel-button"),
                HorizontalExpand = true,
            };
            cancel.OnPressed += _ => OnCancelPublicListing?.Invoke(listing.Id);
            actions.AddChild(cancel);
        }
        else
        {
            var buy = new Button
            {
                Text = listing.Price.ToString(),
                Disabled = listing.Price > _state!.Balance,
                HorizontalExpand = true,
                StyleBoxOverride = CreateActionButtonStyle("#c79612", "#f0d36f"),
            };
            buy.Label.FontColorOverride = Color.White;
            buy.OnPressed += _ => OnBuyPublicListing?.Invoke(listing.Id);
            actions.AddChild(buy);
        }
        content.AddChild(actions);
        panel.AddChild(content);
        return panel;
    }

    private static PanelContainer CreateCardPanel(string borderColor)
    {
        return new PanelContainer
        {
            SetSize = new Vector2(176, 200),
            MinSize = new Vector2(176, 200),
            Margin = new Thickness(3),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#171512"),
                BorderColor = Color.FromHex(borderColor),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 5,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            },
        };
    }

    private static PanelContainer CreateCardNamePanel(string displayName, string toolTip, Color color)
    {
        var namePanel = new PanelContainer
        {
            MinHeight = 48,
            SetHeight = 48,
            HorizontalExpand = true,
            Margin = new Thickness(0, 3, 0, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#29251f"),
                BorderColor = Color.FromHex("#554b3d"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            },
        };
        var name = new RichTextLabel
        {
            ToolTip = toolTip,
            MinSize = new Vector2(154, 42),
            SetSize = new Vector2(154, 42),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            RectClipContent = true,
        };
        name.SetMessage(displayName, defaultColor: color);
        namePanel.AddChild(name);
        return namePanel;
    }

    private static BoxContainer CreateCardActionsRow()
    {
        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinHeight = 30,
            SetHeight = 30,
            Margin = new Thickness(0, 4, 0, 0),
        };
    }

    private Control CreateCard(TradingMarketItemState item)
    {
        var panel = CreateCardPanel(_selected == item.CommodityId ? "#d1a64b" : "#4e4638");
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var select = new Button
        {
            HorizontalExpand = true,
            MinHeight = 100,
            SetHeight = 100,
        };
        select.AddChild(CreateItemPreview(item, new Vector2(80, 80)));
        select.OnPressed += _ =>
        {
            _selected = item.CommodityId;
            _selectedOffer = null;
            _updateSelectedPrice = true;
            OnSelectCommodity?.Invoke(item.CommodityId);
            RebuildItems();
            RebuildSelected();
        };
        content.AddChild(select);
        content.AddChild(CreateCardNamePanel(
            item.DisplayName,
            item.DisplayName,
            item.IsDamagedEquipment ? Color.FromHex("#e65353") : Color.White));

        var actions = CreateCardActionsRow();
        var buy = new Button
        {
            Text = item.LowestSellPrice?.ToString() ?? "—",
            Disabled = (!_state!.IsOwner && !_state.IsPublic) ||
                       item.LowestSellPrice == null ||
                       item.LowestSellPrice > _state.Balance,
            HorizontalExpand = true,
            StyleBoxOverride = CreateActionButtonStyle("#c79612", "#f0d36f"),
        };
        buy.Label.FontColorOverride = Color.White;
        buy.OnPressed += _ => OnBuy?.Invoke(item.CommodityId);
        actions.AddChild(buy);
        if (!_state.IsPublic && HasSection(item, TradingMarketSection.Unique))
        {
            var sell = new Button
            {
                Text = item.HighestBuyPrice?.ToString() ?? "—",
                Disabled = !_state.IsOwner || item.HighestBuyPrice == null,
                HorizontalExpand = true,
                Margin = new Thickness(4, 0, 0, 0),
                StyleBoxOverride = CreateActionButtonStyle("#b13a3a", "#e66b63"),
            };
            sell.Label.FontColorOverride = Color.White;
            sell.OnPressed += _ => OnSell?.Invoke(item.CommodityId);
            actions.AddChild(sell);
        }
        content.AddChild(actions);
        panel.AddChild(content);
        return panel;
    }

    private static StyleBoxFlat CreateActionButtonStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }

    private void RebuildSelected()
    {
        OffersContainer.DisposeAllChildren();
        if (_management || _archive || _state == null || _selected == null)
        {
            SelectedName.Text = Loc.GetString("trading-ui-select-item");
            SelectedName.FontColorOverride = null;
            SelectedPreview.DisposeAllChildren();
            SelectedStats.SetMarkup(string.Empty);
            CreateBuyOrderButton.Disabled = true;
            return;
        }

        var item = _state.Items.FirstOrDefault(value => value.CommodityId == _selected.Value);
        if (item == null)
            return;

        var selectedOffer = _selectedOffer is { } selectedOfferId
            ? _state.Offers.FirstOrDefault(offer =>
                offer.Id == selectedOfferId &&
                offer.CommodityId == item.CommodityId)
            : null;
        if (_selectedOffer != null && selectedOffer == null)
        {
            _selectedOffer = null;
            _updateSelectedPrice = true;
        }

        SelectedName.Text = selectedOffer?.DisplayName ?? item.DisplayName;
        SelectedName.FontColorOverride = item.IsDamagedEquipment ? Color.FromHex("#e65353") : null;
        SelectedPreview.DisposeAllChildren();
        SelectedPreview.AddChild(selectedOffer == null
            ? CreateItemPreview(item, new Vector2(96, 96))
            : CreateItemPreview(
                selectedOffer.ProductEntity,
                selectedOffer.PreviewEntity,
                new Vector2(96, 96),
                selectedOffer.CommodityId));
        if (_updateSelectedPrice)
        {
            BuyPrice.Text = (selectedOffer?.Price ?? item.LowestSellPrice)?.ToString() ?? string.Empty;
            _updateSelectedPrice = false;
        }
        SelectedStats.SetMarkup(_state.IsPublic
            ? Loc.GetString("trading-ui-public-offer-count", ("count", item.SellOfferCount))
            : Loc.GetString(
                "trading-ui-offer-counts",
                ("sellCount", item.SellOfferCount),
                ("buyCount", item.BuyOfferCount)));
        CreateBuyOrderButton.Disabled = !_state.IsOwner;

        var offers = _state.Offers
            .Where(offer => offer.CommodityId == item.CommodityId)
            .OrderBy(offer => offer.Side)
            .ThenBy(offer => offer.Side == TradingOfferSide.Sell ? offer.Price : -offer.Price);
        foreach (var offer in offers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };
            row.AddChild(new Label
            {
                Text = GetOfferSideText(offer.Side),
                MinWidth = 54,
            });
            var selectOffer = new Button
            {
                Text = offer.ParticipantName,
                HorizontalExpand = true,
                ClipText = true,
            };
            selectOffer.OnPressed += _ =>
            {
                _selectedOffer = offer.Id;
                _updateSelectedPrice = true;
                OnSelectOffer?.Invoke(offer.Id);
            };
            row.AddChild(selectOffer);

            if (offer.Side == TradingOfferSide.Buy &&
                offer.ParticipantKind == TradingParticipantKind.Guild)
            {
                row.AddChild(new Label
                {
                    Text = offer.Price.ToString(),
                    MinWidth = 76,
                    Align = Label.AlignMode.Center,
                    VAlign = Label.VAlignMode.Center,
                });
            }
            else
            {
                var action = new Button
                {
                    Text = offer.Price.ToString(),
                    MinWidth = 76,
                    Disabled = (!_state.IsOwner &&
                                !(_state.IsPublic && offer.Side == TradingOfferSide.Sell)) ||
                               offer.IsOwn ||
                               offer.Side == TradingOfferSide.Sell && offer.Price > _state.Balance,
                    StyleBoxOverride = offer.Side == TradingOfferSide.Sell
                        ? CreateActionButtonStyle("#c79612", "#f0d36f")
                        : CreateActionButtonStyle("#b13a3a", "#e66b63"),
                };
                action.Label.FontColorOverride = Color.White;
                action.OnPressed += _ =>
                {
                    if (offer.Side == TradingOfferSide.Sell)
                        OnBuyOffer?.Invoke(offer.Id);
                    else
                        OnSellOffer?.Invoke(offer.Id);
                };
                row.AddChild(action);
            }

            if (offer.IsOwn)
            {
                var cancel = new Button { Text = "×", MinWidth = 28 };
                cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
                row.AddChild(cancel);
            }
            OffersContainer.AddChild(row);
        }
    }

    private void CreateSelectedBuyOrder()
    {
        if (_state is not { IsOwner: true } || _selected == null)
            return;

        if (!TryParsePrice(BuyPrice.Text, out var price))
        {
            ShowInvalidOfferPricePopup();
            return;
        }

        OnCreateBuyOffer?.Invoke(_selected.Value, price);
    }

    private void RebuildManagement()
    {
        ManagedOffersContainer.DisposeAllChildren();
        PendingSalesContainer.DisposeAllChildren();
        StoredItemsContainer.DisposeAllChildren();
        if (_state == null)
            return;

        var ownOffers = _state.Offers.Where(offer => offer.IsOwn).ToList();
        if (ownOffers.Count == 0)
        {
            ManagedOffersContainer.AddChild(new Label
            {
                Text = Loc.GetString("trading-ui-no-active-offers"),
            });
        }

        foreach (var offer in ownOffers)
        {
            var status = Loc.GetString(
                "trading-ui-managed-offer-status",
                ("side", GetOfferSideText(offer.Side)),
                ("price", offer.Price));
            if (offer.Side == TradingOfferSide.Sell)
            {
                status += "\n" + Loc.GetString(
                    "trading-ui-managed-offer-seller-revenue",
                    ("amount", Math.Max(0, offer.Price - offer.ReceiptAmount)));
                if (offer.ReceiptAmount > 0)
                {
                    status += "\n" + Loc.GetString(
                        "trading-ui-managed-offer-receipt-revenue",
                        ("amount", offer.ReceiptAmount));
                }
            }

            var row = CreateManagementRow(
                offer.ProductEntity,
                offer.PreviewEntity,
                offer.CommodityId,
                offer.DisplayName,
                status);
            if (offer.Side == TradingOfferSide.Sell)
            {
                var available = Math.Max(0, offer.Price - offer.ReceiptAmount);
                var createReceipt = new Button
                {
                    Text = Loc.GetString("trading-ui-create-bid-receipt-button"),
                    MinWidth = 150,
                    Disabled = available <= 0,
                };
                createReceipt.OnPressed += _ => OpenBidReceiptWindow(offer, available);
                row.AddChild(createReceipt);
            }

            var cancel = new Button
            {
                Text = Loc.GetString(offer.Side == TradingOfferSide.Sell
                    ? "trading-ui-cancel-and-collect-button"
                    : "trading-ui-cancel-button"),
                MinWidth = 150,
            };
            cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
            row.AddChild(cancel);
            ManagedOffersContainer.AddChild(row);
        }

        if (_state.PendingSales.Count == 0)
        {
            PendingSalesContainer.AddChild(new Label
            {
                Text = Loc.GetString("trading-ui-no-pending-sales"),
            });
        }

        foreach (var sale in _state.PendingSales)
        {
            var message = Loc.GetString(
                "trading-ui-pending-sale-entry",
                ("item", sale.ItemName),
                ("trader", sale.BuyerName),
                ("price", sale.Price));
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4),
            };
            var labels = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };
            labels.AddChild(new Label
            {
                Text = message,
                ToolTip = message,
                ClipText = true,
            });
            labels.AddChild(new Label
            {
                Text = Loc.GetString(
                    "trading-ui-pending-sale-seller-revenue",
                    ("amount", sale.SellerRevenue)),
                StyleClasses = { "LabelSubText" },
            });
            if (sale.ReceiptAmount > 0)
            {
                labels.AddChild(new Label
                {
                    Text = Loc.GetString(
                        "trading-ui-pending-sale-receipt-revenue",
                        ("amount", sale.ReceiptAmount)),
                    StyleClasses = { "LabelSubText" },
                });
            }

            row.AddChild(labels);
            var collect = new Button
            {
                Text = Loc.GetString("trading-ui-collect-sale-revenue-button"),
                MinWidth = 150,
            };
            collect.OnPressed += _ => OnCollectSaleRevenue?.Invoke(sale.Id);
            row.AddChild(collect);
            PendingSalesContainer.AddChild(row);
        }

        if (_state.StoredItems.Count == 0)
        {
            StoredItemsContainer.AddChild(new Label
            {
                Text = Loc.GetString("trading-ui-no-stored-items"),
            });
        }

        foreach (var stored in _state.StoredItems)
        {
            var row = CreateManagementRow(
                stored.ProductEntity,
                stored.Item,
                null,
                stored.DisplayName,
                Loc.GetString("trading-ui-received-from-order"));
            var collect = new Button
            {
                Text = Loc.GetString("trading-ui-collect-button"),
                MinWidth = 150,
            };
            collect.OnPressed += _ => OnCollectStoredItem?.Invoke(stored.Item);
            row.AddChild(collect);
            StoredItemsContainer.AddChild(row);
        }
    }

    private void RebuildArchive()
    {
        ArchiveContainer.DisposeAllChildren();
        if (_state == null)
            return;

        if (_state.Archive.Count == 0)
        {
            ArchiveContainer.AddChild(new Label
            {
                Text = Loc.GetString("trading-ui-empty-archive"),
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var message in _state.Archive.AsEnumerable().Reverse())
        {
            ArchiveContainer.AddChild(new Label
            {
                Text = message,
                ToolTip = message,
                HorizontalExpand = true,
                ClipText = true,
                Margin = new Thickness(4, 2),
            });
        }
    }

    private void RebuildPublicSell()
    {
        PublicStagedItemsContainer.DisposeAllChildren();
        PublicListingsContainer.DisposeAllChildren();
        PublicPendingSalesContainer.DisposeAllChildren();
        if (_state == null)
            return;

        BuildStagedItemRows(_state);
        BuildOwnListingRows(_state);
        BuildPendingSaleRows(_state);
    }

    private void BuildStagedItemRows(TradingUpdateState state)
    {
        _stagedPriceText.Keys.Where(id => state.PublicStagedItems.All(staged => staged.Id != id)).ToList()
            .ForEach(id => _stagedPriceText.Remove(id));

        if (state.PublicStagedItems.Count == 0)
        {
            PublicStagedItemsContainer.AddChild(new Label { Text = Loc.GetString("trading-ui-no-staged-items") });
            return;
        }

        foreach (var staged in state.PublicStagedItems)
        {
            PublicStagedItemsContainer.AddChild(CreateStagedItemRow(staged, state.IsMerchantOnline));
        }
    }

    private BoxContainer CreateStagedItemRow(PublicStagedItemState staged, bool listingBlocked)
    {
        var stagedId = staged.Id;
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4),
        };
        row.AddChild(CreateItemPreview(staged.ProductEntity, staged.PreviewEntity, new Vector2(54, 54), null));

        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        };
        labels.AddChild(new Label { Text = staged.DisplayName, ClipText = true });
        row.AddChild(labels);

        var priceEdit = new LineEdit
        {
            PlaceHolder = Loc.GetString("trading-ui-price-placeholder"),
            Text = _stagedPriceText.GetValueOrDefault(stagedId, string.Empty),
            MinWidth = 110,
            HorizontalExpand = false,
        };
        priceEdit.OnTextChanged += args => _stagedPriceText[stagedId] = args.Text;
        row.AddChild(priceEdit);

        var listButton = new Button
        {
            Text = Loc.GetString("trading-ui-list-public-item-button"),
            MinWidth = 130,
            Margin = new Thickness(4, 0, 0, 0),
            Disabled = listingBlocked,
            ToolTip = listingBlocked ? Loc.GetString("trading-ui-merchant-online-blocked") : null,
        };
        listButton.OnPressed += _ =>
        {
            if (!TryParsePrice(priceEdit.Text, out var price))
            {
                ShowInvalidOfferPricePopup();
                return;
            }

            OnListStagedItem?.Invoke(stagedId, price);
        };
        row.AddChild(listButton);

        if (staged.InstantSellValue > 0)
        {
            var sellButton = new Button
            {
                Text = Loc.GetString("trading-ui-instant-sell-button-value", ("value", staged.InstantSellValue)),
                MinWidth = 170,
                Margin = new Thickness(4, 0, 0, 0),
                ToolTip = Loc.GetString("trading-ui-instant-sell-tooltip"),
            };
            sellButton.OnPressed += _ => OnSellStagedItem?.Invoke(stagedId);
            row.AddChild(sellButton);
        }

        if (staged.FulfillableBuyOrderPrice is { } fulfillPrice)
        {
            var fulfillButton = new Button
            {
                Text = Loc.GetString("trading-ui-fulfill-button-value", ("value", fulfillPrice)),
                MinWidth = 170,
                Margin = new Thickness(4, 0, 0, 0),
                StyleBoxOverride = CreateActionButtonStyle("#2c7a4b", "#5fd18d"),
            };
            fulfillButton.Label.FontColorOverride = Color.White;
            fulfillButton.OnPressed += _ => OnFulfillStagedItem?.Invoke(stagedId);
            row.AddChild(fulfillButton);
        }

        var withdrawButton = new Button
        {
            Text = "×",
            MinWidth = 28,
            Margin = new Thickness(4, 0, 0, 0),
            ToolTip = Loc.GetString("trading-ui-withdraw-staged-item-button"),
        };
        withdrawButton.OnPressed += _ => OnWithdrawStagedItem?.Invoke(stagedId);
        row.AddChild(withdrawButton);

        return row;
    }

    private void BuildOwnListingRows(TradingUpdateState state)
    {
        var ownListings = state.PublicListings.Where(listing => listing.IsOwn).ToList();
        if (ownListings.Count == 0)
        {
            PublicListingsContainer.AddChild(new Label { Text = Loc.GetString("trading-ui-no-public-listings") });
            return;
        }

        foreach (var listing in ownListings)
        {
            var status = Loc.GetString("trading-ui-public-listing-status", ("price", listing.Price));
            var row = CreateManagementRow(listing.ProductEntity, listing.PreviewEntity, null, listing.DisplayName, status);
            var cancel = new Button
            {
                Text = Loc.GetString("trading-ui-cancel-button"),
                MinWidth = 150,
            };
            cancel.OnPressed += _ => OnCancelPublicListing?.Invoke(listing.Id);
            row.AddChild(cancel);
            PublicListingsContainer.AddChild(row);
        }
    }

    private void BuildPendingSaleRows(TradingUpdateState state)
    {
        if (state.PublicPendingSales.Count == 0)
        {
            PublicPendingSalesContainer.AddChild(new Label { Text = Loc.GetString("trading-ui-no-pending-sales") });
            return;
        }

        foreach (var sale in state.PublicPendingSales)
        {
            var message = Loc.GetString(
                "trading-ui-pending-sale-entry",
                ("item", sale.ItemName),
                ("trader", sale.BuyerName),
                ("price", sale.Price));
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4),
            };
            row.AddChild(new Label
            {
                Text = message,
                ToolTip = message,
                HorizontalExpand = true,
                ClipText = true,
            });
            var collect = new Button
            {
                Text = Loc.GetString("trading-ui-collect-sale-revenue-button"),
                MinWidth = 150,
            };
            collect.OnPressed += _ => OnCollectPublicSaleRevenue?.Invoke(sale.Id);
            row.AddChild(collect);
            PublicPendingSalesContainer.AddChild(row);
        }
    }

    private BoxContainer CreateManagementRow(
        EntProtoId product,
        NetEntity? preview,
        Guid? commodityId,
        string displayName,
        string status)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4),
        };
        row.AddChild(CreateItemPreview(product, preview, new Vector2(54, 54), commodityId));
        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        };
        labels.AddChild(new Label { Text = displayName, ClipText = true });
        labels.AddChild(new Label { Text = status, StyleClasses = { "LabelSubText" } });
        row.AddChild(labels);
        return row;
    }

    private void SubmitPrice(string text, Action<int>? action, bool allowZero = false)
    {
        if (!TryParsePrice(text, out var price, allowZero))
        {
            ShowInvalidOfferPricePopup();
            return;
        }

        action?.Invoke(price);
    }

    private void ShowInvalidOfferPricePopup()
    {
        _entities.System<PopupSystem>().PopupCursor(
            Loc.GetString("trading-ui-invalid-offer-price"),
            PopupType.SmallCaution);
    }

    private static bool TryParsePrice(string text, out int price, bool allowZero = false)
    {
        return int.TryParse(text, out price) && (price > 0 || allowZero && price == 0);
    }

    private Control CreateItemPreview(TradingMarketItemState item, Vector2 size)
    {
        return CreateItemPreview(item.ProductEntity, item.PreviewEntity, size, item.CommodityId);
    }

    private Control CreateItemPreview(
        EntProtoId product,
        NetEntity? preview,
        Vector2 size,
        Guid? commodityId)
    {
        if (preview is { } netEntity)
        {
            var view = new SpriteView
            {
                MinSize = size,
                SetSize = size,
                Stretch = SpriteView.StretchMode.Fill,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Pass,
            };
            view.SetEntity(netEntity);
            view.OnKeyBindDown += args =>
            {
                if (args.Function != ContentKeyFunctions.ExamineEntity)
                    return;

                OnExamineItem?.Invoke(netEntity);
                args.Handle();
            };
            return view;
        }

        if (_prototypes.HasIndex(product))
        {
            var icon = new TextureRect
            {
                Texture = _entities.System<SpriteSystem>().GetPrototypeIcon(product).Default,
                MinSize = size,
                SetSize = size,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Pass,
            };
            icon.OnKeyBindDown += args =>
            {
                if (args.Function != ContentKeyFunctions.ExamineEntity)
                    return;

                if (commodityId is { } id)
                    OnExamineCommodity?.Invoke(id, product);
                args.Handle();
            };
            return icon;
        }

        return new Control
        {
            MinSize = size,
            SetSize = size,
        };
    }

    public EntityUid GetPrototypeExamineEntity(EntProtoId product)
    {
        if (_prototypeExamineEntities.TryGetValue(product, out var entity) &&
            _entities.EntityExists(entity))
        {
            return entity;
        }

        entity = _entities.SpawnEntity(product, MapCoordinates.Nullspace);
        _prototypeExamineEntities[product] = entity;
        return entity;
    }

    private static bool HasSection(TradingMarketItemState item, TradingMarketSection section)
    {
        return (item.Sections & section) != 0;
    }

    private void OnActiveHandChanged(string? _)
    {
        UpdateHeldItem();
    }

    private void OnHeldItemChanged(string _, EntityUid __)
    {
        UpdateHeldItem();
    }

    private void OnHandsAdded(Entity<HandsComponent> _)
    {
        UpdateHeldItem();
    }

    private void OnHandsRemoved()
    {
        UpdateHeldItem();
    }

    private void UpdateHeldItem()
    {
        var itemName = "—";
        var canOffer = false;
        if (_state is { IsOwner: true } &&
            _hands.GetActiveHandEntity() is { } held &&
            _entities.EntityExists(held) &&
            !_entities.HasComponent<VirtualItemComponent>(held) &&
            _entities.TryGetComponent<MetaDataComponent>(held, out var metadata))
        {
            itemName = metadata.EntityName;
            if (metadata.EntityPrototype?.ID is { } product &&
                _entities.HasComponent<ItemComponent>(held))
            {
                canOffer = true;
            }
        }

        if (_heldItemName != itemName)
        {
            _heldItemName = itemName;
            HeldItemName.SetMessage(
                Loc.GetString("trading-ui-held-item", ("item", itemName)),
                defaultColor: Color.White);
            HeldItemName.ToolTip = itemName;
        }

        UpdateHeldItemAvailability(canOffer);
    }

    private void UpdateHeldItemAvailability(bool canOffer)
    {
        CreateSellOfferButton.Disabled = !canOffer;
        CreateUnitSellOfferButton.Disabled = !canOffer;
        CreateHeldBuyOrderButton.Disabled = !canOffer;
    }

    public void OpenUnitSellWindow(TradingUnitSellOfferPreparedMessage message)
    {
        if (_state is not { IsOwner: true })
            return;

        _unitSellWindow?.Close();
        _unitSellRequest = message.RequestId;
        _unitSellWindow = new TradingUnitSellWindow(
            message.ItemName,
            message.Price,
            message.MaximumAmount);
        _unitSellWindow.OnConfirm += amount =>
        {
            if (_unitSellRequest is not { } requestId)
                return;

            _unitSellRequest = null;
            OnCreateUnitSellOffers?.Invoke(requestId, amount);
        };
        _unitSellWindow.OpenCentered();
    }

    private void OpenBidReceiptWindow(TradingMarketOfferState offer, int maximumAmount)
    {
        if (_state is not { IsOwner: true } || maximumAmount <= 0)
            return;

        if (_bidReceiptWindow is { IsOpen: true } && _bidReceiptOffer == offer.Id)
        {
            _bidReceiptWindow.SetMaximumAmount(maximumAmount);
            _bidReceiptWindow.MoveToFront();
            return;
        }

        _bidReceiptWindow?.Close();
        _bidReceiptOffer = offer.Id;
        _bidReceiptWindow = new TradingBidReceiptWindow(maximumAmount);
        _bidReceiptWindow.OnConfirm += amount =>
        {
            if (_bidReceiptOffer is not { } offerId)
                return;

            _bidReceiptOffer = null;
            OnCreateBidReceipt?.Invoke(offerId, amount);
        };
        _bidReceiptWindow.OpenCentered();
    }

    private void UpdateBidReceiptWindow()
    {
        if (_bidReceiptWindow is not { IsOpen: true } ||
            _state is not { IsOwner: true } ||
            _bidReceiptOffer is not { } offerId)
        {
            return;
        }

        var offer = _state.Offers.FirstOrDefault(candidate => candidate.Id == offerId);
        var maximumAmount = offer == null ? 0 : Math.Max(0, offer.Price - offer.ReceiptAmount);
        if (offer == null || offer.Side != TradingOfferSide.Sell || maximumAmount <= 0)
        {
            _bidReceiptWindow.Close();
            _bidReceiptOffer = null;
            return;
        }

        _bidReceiptWindow.SetMaximumAmount(maximumAmount);
    }

    private void OpenWithdrawWindow()
    {
        if (_state is not { IsOwner: true } || _currency == null)
            return;

        if (_withdrawWindow is { IsOpen: true })
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2>
        {
            { _currency, _state.Balance },
        });
        _withdrawWindow.OnWithdrawAttempt += (_, _, amount) => OnWithdraw?.Invoke(amount);
    }

    private void OpenHelpWindow()
    {
        if (_helpWindow is { IsOpen: true })
        {
            _helpWindow.MoveToFront();
            return;
        }

        _helpWindow = new TradingHelpWindow();
        _helpWindow.OpenCentered();
    }

    private static string GetOfferSideText(TradingOfferSide side)
    {
        return Loc.GetString(side == TradingOfferSide.Sell
            ? "trading-ui-sell-offer"
            : "trading-ui-buy-order");
    }

    private void UpdateColumns()
    {
        ItemsGrid.Columns = Math.Max(1, (int) (ItemsGrid.Width / 185));
    }

    public override void Close()
    {
        StopTrackingHands();

        base.Close();
        _withdrawWindow?.Close();
        _unitSellWindow?.Close();
        _bidReceiptWindow?.Close();
        _helpWindow?.Close();

        foreach (var entity in _prototypeExamineEntities.Values)
        {
            if (_entities.EntityExists(entity))
                _entities.QueueDeleteEntity(entity);
        }

        _prototypeExamineEntities.Clear();
    }

    public void StopTrackingHands()
    {
        if (!_trackingHands)
            return;

        _trackingHands = false;
        _hands.OnPlayerSetActiveHand -= OnActiveHandChanged;
        _hands.OnPlayerItemAdded -= OnHeldItemChanged;
        _hands.OnPlayerItemRemoved -= OnHeldItemChanged;
        _hands.OnPlayerHandsAdded -= OnHandsAdded;
        _hands.OnPlayerHandsRemoved -= OnHandsRemoved;
    }
}
