using Content.Client.Message;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingItemControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public TradingItemControl(
        GuildTradingItem data,
        string price,
        string discount,
        bool canBuy,
        Texture? texture = null,
        bool available = true,
        string unavailableReason = "")
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StoreItemName.Text = _prototypes.TryIndex(data.ProductEntity, out var prototype)
            ? Loc.GetString(prototype.Name)
            : data.Name ?? data.ProductEntity?.Id ?? string.Empty;
        StoreItemDescription.SetMarkup(data.Description ?? string.Empty);
        StoreItemTexture.Texture = texture;
        StoreItemBuyButton.Text = price;
        StoreItemBuyButton.Disabled = !canBuy || !available;
    }
}
