using Content.Client.GameTicking.Managers;
using Content.Shared.Imperial.Medieval.Trading;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Medieval.Trading;


[GenerateTypedNameReferences]
public sealed partial class TradingItemControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly GuildTradingItem _data;

    private readonly bool _hasBalance;
    private readonly string _price;
    private readonly string _discount;
    public TradingItemControl(GuildTradingItem data, string price, string discount, bool hasBalance, Texture? texture = null, bool available = true, string unavailableReason = "")
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _data = data;
        _hasBalance = hasBalance;
        _price = price;
        _discount = discount;

        StoreItemName.Text = TradingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemDescription.SetMessage(TradingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));

        UpdateBuyButtonText();
        StoreItemBuyButton.Disabled = !CanBuy();

        StoreItemTexture.Texture = texture;

        if (!available)
        {
            StoreItemBuyButton.Visible = false;
            UnavailableItemReason.Visible = true;
            UnavailableItemReason.Text = unavailableReason;
        }
    }

    private bool CanBuy()
    {
        return _hasBalance;
    }

    private void UpdateBuyButtonText()
    {
        DiscountSubText.Text = _discount;
        StoreItemBuyButton.Text = _price;
    }

    private void UpdateName()
    {
        var name = TradingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);

        StoreItemName.Text = name;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateBuyButtonText();
        UpdateName();
        StoreItemBuyButton.Disabled = !CanBuy();
    }
}
