using System.Linq;
using System.Text;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.Medieval.Trading;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private StoreWithdrawWindow? _withdrawWindow;
    private TradingStatsWindow? _statsWindow;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, GuildTradingItem>? OnItemButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;

    public FixedPoint2 Balance = new();
    public Guild? CurrentGuild = null!;

    public NetEntity? User;
    private CurrencyPrototype? _currency;
    public ProtoId<CurrencyPrototype>? CurrencyPrototype;

    private List<Guild> _cachedGuilds = new();

    public Action<Guild>? OnGuildSelect;

    public TradingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        ReputationLeaderboardButton.OnButtonDown += OnLeaderboardButtonDown;
        BackButton.OnButtonDown += _ => SelectGuildTab();
        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);

        OnResized += () => ControlContainer.Columns = (int)(Width / 215);
    }

    private void OnLeaderboardButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (CurrentGuild == null)
            return;

        var entries = CurrentGuild.Reputation
            .Select(kv =>
            {
                if (_entityManager.TryGetEntity(kv.Key, out var uid) &&
                    _entityManager.TryGetComponent<MetaDataComponent>(uid, out var meta))
                    return (meta.EntityName, kv.Value);

                if (CurrentGuild.ReputationNames.TryGetValue(kv.Key, out var name))
                    return (name, kv.Value);

                return ("???", kv.Value);
            })
            .ToDictionary(x => x.Item1, x => x.Item2);


        if (_statsWindow != null && _statsWindow.IsOpen)
        {
            _statsWindow.PopulateEntries(entries);
            _statsWindow.MoveToFront();
            return;
        }

        _statsWindow = new TradingStatsWindow();
        _statsWindow.PopulateEntries(entries);
        _statsWindow.OpenCentered();
    }

    public void PopulateGuilds(HashSet<Guild> guilds)
    {
        ControlContainer.DisposeAllChildren();
        foreach (var guild in guilds)
        {
            var guildControl = new GuildCardControl(guild, User);
            guildControl.OnPressed += () => OnGuildSelect?.Invoke(guild);
            ControlContainer.AddChild(guildControl);
        }
    }

    public void SelectGuildTab()
    {
        GuildTab.Visible = true;
        TradingTab.Visible = false;
    }

    public void SelectTradingTab()
    {
        GuildTab.Visible = false;
        TradingTab.Visible = true;
    }

    public void UpdateBalance(FixedPoint2 balance)
    {
        Balance = balance;

        var balanceStr = CurrencyPrototype != null && _prototypeManager.TryIndex(CurrencyPrototype, out _currency)
            ? $"{Loc.GetString(_currency.DisplayName)}: {balance}"
            : balance.ToString();

        BalanceInfo.SetMarkup(balanceStr.Trim());

        WithdrawButton.Disabled = false;
    }

    public void UpdateGuild() => SelectGuild();
    public void SelectGuild(Guild? guild = null, string? search = null)
    {
        if (guild != null)
            CurrentGuild = guild;

        if (guild != null)
            SearchBar.Text = "";

        var normalizedSearch = (search ?? SearchBar.Text).Trim().ToLowerInvariant();
        UpdateReputation(CurrentGuild);
        UpdateItems(CurrentGuild, normalizedSearch);
    }

    private void UpdateReputation(Guild? guild = null)
    {
        if (User == null)
            return;

        if (guild == null)
            return;

        var reputation = guild.GetReputation(User.Value);
        var reputationRounded = MathF.Round(reputation, 1);
        ReputationLabel.Text = Loc.GetString("trading-ui-reputation-text", ("rep", reputationRounded.ToString("0.0")));

        var discount = TradingHelpers.DiscountWithReputation(guild, User.Value) * 100f;
        ReputationDiscoundLabel.Text = discount >= 1
            ? $"-{MathF.Round(discount)}% скидка"
            : "";
    }

    private IEnumerable<GuildTradingItem> FilterItems(IEnumerable<GuildTradingItem>? items, string search = "")
    {
        var filteredItems = items?.Where(data =>
                            TradingLocalisationHelpers.GetLocalisedNameOrEntityName(data, _prototypeManager)
                                .Trim()
                                .ToLowerInvariant()
                                .Contains(search) ||
                            TradingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(data, _prototypeManager)
                                .Trim()
                                .ToLowerInvariant()
                                .Contains(search))
                        .OrderBy(itm => TradingLocalisationHelpers.GetLocalisedNameOrEntityName(itm, _prototypeManager))
                    ?? Enumerable.Empty<GuildTradingItem>();

        return filteredItems;
    }

    public void UpdateItems(Guild? guild = null, string search = "")
    {
        ClearItems();

        var guildType = guild != null ? _prototypeManager.Index(guild.TypePrototype) : null;
        var currency = guildType?.Currency;

        var items = FilterItems(guild?.Items, search);
        foreach (var item in items)
        {
            AddItemGui(item, currency);
        }


        var filteredUnavailableKeys = FilterItems(guild?.UnavailableItems.Keys, search).ToHashSet();
        var unavailableItems = guild?.UnavailableItems
            .Where(kv => filteredUnavailableKeys.Contains(kv.Key))
            .ToDictionary(kv => kv.Key, kv => kv.Value) ?? new();
        foreach (var (item, reason) in unavailableItems)
        {
            AddItemGui(item, currency, false, reason);
        }
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_currency == null)
            return;

        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2>() { {_currency, Balance} });
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    private void AddItemGui(GuildTradingItem item, string? currency = null, bool available = true, string unavailableReason = "")
    {
        var hasBalance = item.ChangedCost <= Balance;

        var texture = item.ProductEntity != null
            ? _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>()
                .GetPrototypeIcon(item.ProductEntity)
                .Default
            : null;

        var stockPrice = GetItemPriceString(item, currency);

        var newListing = new TradingItemControl(item, stockPrice,"", hasBalance, texture, available, unavailableReason);
        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnItemButtonPressed?.Invoke(args, item);

        TradingItemsContainer.AddChild(newListing);
    }

    private string GetItemPriceString(GuildTradingItem item, string? currency = null)
    {
        var currencyPrototype = currency != null ? _prototypeManager.Index<CurrencyPrototype>(currency) : null;

        var text = Loc.GetString("store-ui-price-display",
            ("amount", item.ChangedCost),
            ("currency", Loc.GetString(currencyPrototype?.DisplayName ?? "", ("amount", item.ChangedCost))));

        return text.Trim();
    }
    private void ClearItems()
    {
        TradingItemsContainer.Children.Clear();
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }
}
