using Content.Client.UserInterface.Controls;
using Content.Shared.Polymorph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.Imperial.Medieval.Lycantropy.UI;

[GenerateTypedNameReferences]
public sealed partial class SelectWerewolfFormMenu : Content.Client.UserInterface.Controls.RadialMenu
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<ProtoId<PolymorphPrototype>>? OnSelected;

    public SelectWerewolfFormMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate(Dictionary<string, ProtoId<PolymorphPrototype>> forms)
    {
        foreach (var item in forms)
        {
            var proto = _proto.Index(item.Value);
            var ent = _entityManager.Spawn(proto.Configuration.Entity);

            var button = new RadialMenuButtonWithSector()
            {
                SetSize = new Vector2(64, 64),
                ToolTip = Loc.GetString(item.Key),
            };// 123 2

            var entProtoView = new EntityPrototypeView()
            {
                SetSize = new Vector2(48, 48),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Stretch = SpriteView.StretchMode.Fill,
            };

            entProtoView.SetEntity(ent);
            button.AddChild(entProtoView);

            button.OnPressed += args =>
            {
                OnSelected?.Invoke(item.Value);
                Close();
            };

            Main.AddChild(button);
        }
    }
}
