using System.Globalization;
using Content.Client.Imperial.UI.Windows.BaseImperialWindow;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.ShiftFront.UI.Windows.Barracks
{
    [GenerateTypedNameReferences]
    public sealed partial class ShiftBarracks : BaseImperialWindow
    {
        public ShiftBarracks()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

        }

        //protected override void FrameUpdate(FrameEventArgs args)
        //{
        //    base.FrameUpdate(args);
        //}

        protected override void Opened()
        {
            base.Opened();
            for (int i = 0; i < 10; i++)
            {
                var newCard = new BarrackUnitCard();
                newCard.UnitCardName.SetMessage(FormattedMessage.FromMarkupOrThrow("[color=red]Г[/color][color=orange]о[/color][color=yellow]в[/color][color=green]н[/color][color=blue]о[/color] " + i.ToString()));
                newCard.UnitCarDesc.SetMessage(FormattedMessage.FromMarkupOrThrow("Описание"));
                newCard.UnitCardAvailable.SetMessage(FormattedMessage.FromMarkupOrThrow("Доступно: 999"));
                CardsBoxContainer.AddChild(newCard);

            }
        }

    }
}
