using System.Globalization;
using Content.Client.Imperial.UI.Windows.BaseImperialWindow;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Robust.Shared.Prototypes;
using Content.Shared.ShiftFrontResearch;

namespace Content.Client.Imperial.ShiftFront.UI.Windows.Barracks
{
    [GenerateTypedNameReferences]
    public sealed partial class ShiftBarracks : BaseImperialWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        public ShiftBarracks()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

        }

        //protected override void FrameUpdate(FrameEventArgs args)
        //{
        //    base.FrameUpdate(args);
        //}

        protected override void Opened()
        {
            base.Opened();
            var cards = _prototypeManager.EnumeratePrototypes<ShiftFrontUnitCardPrototype>();
            foreach (var card in cards)
            {
                var newCard = new BarrackUnitCard();
                newCard.UnitCardName.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(card.UnitName)));
                newCard.UnitCarDesc.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(card.UnitDesc)));
                newCard.UnitCardAvailable.SetMessage(FormattedMessage.FromMarkupOrThrow("Доступно: 999"));
                CardsBoxContainer.AddChild(newCard);
// "[color=red]Г[/color][color=orange]о[/color][color=yellow]в[/color][color=green]н[/color][color=blue]о[/color] "
            }
        }

    }
}
