using System.Numerics;
using System.Text;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Client.Imperial.Medieval.UserInterface.Elements;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.FixedPoint;
using Content.Shared.Kitchen;
using Content.Shared.Kitchen.Components;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Medieval.UserInterface.Windows;

/// <summary>
///     imperial medieval - the enchanted mortar: ingredients on a shelf on top, the mortar grinding on its own in
///     the middle, the vessel it pours into underneath. Talks to the stock ReagentGrinderSystem through
///     <see cref="MedievalMortarBoundUserInterface"/>; the stock auto mode is shown as the mortar's charm.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MedievalMortarMenu : MedievalWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    // matches the stock ReagentGrinderComponent.StorageMaxEntities the mortar uses
    private const int ChamberSlots = 6;

    // the stock grinder skips its "complete" message if the vessel is gone by the end; past this the window
    // unlocks on its own. Comfortably longer than the mortar's work time
    private static readonly TimeSpan UnlockGrace = TimeSpan.FromSeconds(15);

    private static readonly TimeSpan RecheckInterval = TimeSpan.FromSeconds(0.25);

    private static readonly Vector2 SlotSize = new(56, 52);
    private static readonly Vector2 SlotIconSize = new(32, 32);
    private static readonly Vector2 EmptyMarkSize = new(4, 4);

    private static readonly Vector2 SceneSize = new(336, 120);
    private static readonly Vector2 MortarSize = new(128, 128);
    // the auto mode toggle, in the top right corner of the scene
    private static readonly Vector2 AutoButtonSize = new(124, 24);

    // the mortar is drawn in the upper part of its 32x32 sprite and a touch to the left; this puts the drawing
    // itself in the middle of the scene (sprite pixels times the scale of 4)
    private static readonly Vector2 MortarDrawingOffset = new(2, 20);

    // while the pestle works the mortar slowly shimmers between its own colours and a magic tint
    private const float ShimmerSpeed = 3f;
    private const float ShimmerStrength = 0.6f;

    private const string ProblemNoGrind = "medieval-mortar-menu-slot-no-grind";
    private const string ProblemNoJuice = "medieval-mortar-menu-slot-no-juice";
    private const string ProblemWontFit = "medieval-mortar-menu-slot-wont-fit";
    private const string ProblemWontFitGrinding = "medieval-mortar-menu-slot-wont-fit-grinding";
    private const string ProblemWontFitPressing = "medieval-mortar-menu-slot-wont-fit-pressing";

    public event Action? OnGrind;
    public event Action? OnJuice;
    public event Action? OnVesselPressed;
    public event Action? OnToggleAuto;
    public event Action<EntityUid>? OnIngredientPressed;

    private readonly List<PlainButton> _slots = new();
    private readonly List<TextureRect> _slotIcons = new();
    private readonly List<PanelContainer> _slotEmptyMarks = new();
    private readonly List<PanelContainer> _slotWarnings = new();
    private readonly EntityUid?[] _slotEntities = new EntityUid?[ChamberSlots];

    private readonly SpriteView _mortarView;
    private readonly MedievalToggleButton _autoButton;
    private readonly PlainButton _vesselButton;
    private readonly SpriteView _vesselView;
    private readonly Label _vesselName;
    private readonly Label _vesselVolume;

    private EntityUid _mortar;
    private ReagentGrinderInterfaceState? _state;

    // what the window currently shows; items and the vessel can reach the client a moment after the state
    // that lists them, so the frame update re-checks until they match
    private EntityUid? _shownVessel;
    private bool _contentsPending;
    private TimeSpan _nextRecheck;

    // set by the work started/complete messages only: the state the server sends right after the work
    // still says "busy", because the active marker is removed a tick later
    private GrinderProgram? _working;
    private TimeSpan _workStarted;

    public MedievalMortarMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleFont = MedievalUiStyle.TitleFont(_resCache);
        MedievalUiStyle.ApplyTextFont(_resCache, StatusLabel, GrindButton, JuiceButton);

        GrindButton.OnPressed += _ => OnGrind?.Invoke();
        JuiceButton.OnPressed += _ => OnJuice?.Invoke();

        SceneLayout.SetSize = SceneSize;

        _mortarView = new SpriteView
        {
            Scale = new Vector2(4, 4),
            MouseFilter = MouseFilterMode.Ignore,
        };
        Place(_mortarView, (SceneSize - MortarSize) / 2 + MortarDrawingOffset, MortarSize);

        // a plain row: the vessel, its name, how full it is. Click takes it, or puts in the one from your hand
        _vesselView = new SpriteView
        {
            // scale 2 on purpose: cups are small sprites, the transparent edges may spill over the row
            Scale = new Vector2(2, 2),
            Stretch = SpriteView.StretchMode.None,
            SetSize = new Vector2(40, 40),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 8, 0),
        };
        _vesselName = new Label
        {
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
            ClipText = true,
        };
        _vesselVolume = new Label
        {
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = MedievalUiStyle.Text,
            Margin = new Thickness(8, 0, 4, 0),
        };
        MedievalUiStyle.ApplyTextFont(_resCache, _vesselName);

        var vesselRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        vesselRow.AddChild(_vesselView);
        vesselRow.AddChild(_vesselName);
        vesselRow.AddChild(_vesselVolume);

        _vesselButton = new PlainButton { SetHeight = 44 };
        _vesselButton.AddChild(vesselRow);
        _vesselButton.OnPressed += _ =>
        {
            if (_working == null)
                OnVesselPressed?.Invoke();
        };
        VesselBox.AddChild(_vesselButton);

        // the stock auto mode: the mortar starts on its own as soon as something is put in
        _autoButton = new MedievalToggleButton();
        _autoButton.OnPressed += _ => OnToggleAuto?.Invoke();
        Place(_autoButton, new Vector2(SceneSize.X - AutoButtonSize.X, 0), AutoButtonSize);

        BuildSlots();
        Refresh();
    }

    private void BuildSlots()
    {
        for (var i = 0; i < ChamberSlots; i++)
        {
            var index = i;

            var icon = new TextureRect
            {
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                SetSize = SlotIconSize,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            // a small dot where nothing lies yet, so the six places are visible
            var emptyMark = new PanelContainer
            {
                SetSize = EmptyMarkSize,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore,
                PanelOverride = new StyleBoxFlat { BackgroundColor = MedievalUiStyle.BackgroundHover },
            };

            // red line under an ingredient that is in the way
            var warning = new PanelContainer
            {
                Margin = new Thickness(10, 0, 10, 3),
                MouseFilter = MouseFilterMode.Ignore,
                Visible = false,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.Transparent,
                    BorderColor = MedievalUiStyle.Warning,
                    BorderThickness = new Thickness(0, 0, 0, 2),
                },
            };

            var slot = new PlainButton { SetSize = SlotSize };
            slot.AddChild(emptyMark);
            slot.AddChild(icon);
            slot.AddChild(warning);
            slot.OnPressed += _ =>
            {
                if (_working == null && _slotEntities[index] is { } uid)
                    OnIngredientPressed?.Invoke(uid);
            };

            SlotsBox.AddChild(slot);
            _slots.Add(slot);
            _slotIcons.Add(icon);
            _slotEmptyMarks.Add(emptyMark);
            _slotWarnings.Add(warning);
        }
    }

    // fixed box in the scene via margins
    private void Place(Control control, Vector2 position, Vector2 size)
    {
        SceneLayout.AddChild(control);
        LayoutContainer.SetMarginLeft(control, position.X);
        LayoutContainer.SetMarginTop(control, position.Y);
        LayoutContainer.SetMarginRight(control, position.X + size.X);
        LayoutContainer.SetMarginBottom(control, position.Y + size.Y);
    }

    public void SetMortar(EntityUid mortar)
    {
        _mortar = mortar;
        _mortarView.SetEntity(mortar);
    }

    public void UpdateState(ReagentGrinderInterfaceState state)
    {
        _state = state;

        // a state saying "not busy" is always right; one saying "busy" may be stale, so it never locks the window
        if (!state.IsBusy)
            _working = null;

        Refresh();
    }

    public void HandleMessage(BoundUserInterfaceMessage message)
    {
        switch (message)
        {
            case ReagentGrinderWorkStartedMessage started:
                _working = started.GrinderProgram;
                _workStarted = _timing.CurTime;
                Refresh();
                break;
            case ReagentGrinderWorkCompleteMessage:
                _working = null;
                Refresh();
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_working != null && _timing.CurTime > _workStarted + UnlockGrace)
        {
            _working = null;
            Refresh();
            return;
        }

        if (_working != null)
        {
            var wave = 0.5f + 0.5f * MathF.Sin((float) _timing.RealTime.TotalSeconds * ShimmerSpeed);
            _mortarView.ModulateSelfOverride = Color.InterpolateBetween(Color.White, MedievalUiStyle.Magic, wave * ShimmerStrength);
        }

        // only while the window is open: a cheap slot lookup every frame, a missing item re-checked a few times a second
        var now = _timing.RealTime;
        if (CurrentVessel() != _shownVessel || (_contentsPending && now >= _nextRecheck))
        {
            _nextRecheck = now + RecheckInterval;
            Refresh();
        }
    }

    private EntityUid? CurrentVessel()
    {
        if (_state is not { HasBeakerIn: true })
            return null;

        return _entMan.System<ItemSlotsSystem>().GetItemOrNull(_mortar, SharedReagentGrinder.BeakerSlotId);
    }

    private void Refresh()
    {
        var busy = _working != null;
        var vessel = CurrentVessel();
        var contents = ResolveContents();
        var check = CheckContents(contents, vessel);

        var (text, color, flagged) = StatusText(contents.Count, check, vessel);
        StatusLabel.Text = text;
        StatusLabel.FontColorOverride = color;

        ShowContents(contents, check, flagged, busy);
        ShowVessel(vessel, busy);

        ShowAutoMode();

        if (!busy)
            _mortarView.ModulateSelfOverride = null;

        GrindButton.Disabled = busy || _state is not { CanGrind: true, Powered: true };
        JuiceButton.Disabled = busy || _state is not { CanJuice: true, Powered: true };
    }

    private void ShowAutoMode()
    {
        var mode = _state?.AutoMode ?? GrinderAutoMode.Off;

        _autoButton.Text = Loc.GetString(mode switch
        {
            GrinderAutoMode.Grind => "medieval-mortar-menu-auto-grind",
            GrinderAutoMode.Juice => "medieval-mortar-menu-auto-juice",
            _ => "medieval-mortar-menu-auto-off",
        });
        _autoButton.ToolTip = Loc.GetString("medieval-mortar-menu-auto-tooltip");
        _autoButton.Pressed = mode != GrinderAutoMode.Off;
    }

    private List<EntityUid> ResolveContents()
    {
        _contentsPending = false;
        var contents = new List<EntityUid>(ChamberSlots);

        if (_state == null)
            return contents;

        foreach (var netEntity in _state.ChamberContents)
        {
            var uid = _entMan.GetEntity(netEntity);

            // listed by the server but not here yet
            if (!_entMan.EntityExists(uid))
            {
                _contentsPending = true;
                continue;
            }

            contents.Add(uid);

            if (contents.Count == ChamberSlots)
                break;
        }

        return contents;
    }

    /// <param name="flagged">What the status line talks about; items with that problem get underlined.</param>
    private void ShowContents(List<EntityUid> contents, ContentsCheck check, string[] flagged, bool busy)
    {
        for (var i = 0; i < ChamberSlots; i++)
        {
            if (i >= contents.Count)
            {
                _slotEntities[i] = null;
                _slotIcons[i].Texture = null;
                _slotEmptyMarks[i].Visible = true;
                _slotWarnings[i].Visible = false;
                _slots[i].ToolTip = null;
                continue;
            }

            var uid = contents[i];
            var problems = check.Problems[i];

            _slotEntities[i] = uid;
            _slotIcons[i].Texture = IconOf(uid);
            // faded while the pestle works: nothing can be taken out then
            _slotIcons[i].ModulateSelfOverride = busy ? MedievalUiStyle.TextFaded : null;
            _slotEmptyMarks[i].Visible = false;
            _slotWarnings[i].Visible = !busy && problems.Exists(p => Array.IndexOf(flagged, p) >= 0);
            _slots[i].ToolTip = SlotTooltip(NameOf(uid), problems);
        }
    }

    private static string SlotTooltip(string name, List<string> problems)
    {
        var tooltip = new StringBuilder(name);

        foreach (var problem in problems)
        {
            tooltip.Append('\n').Append(Loc.GetString(problem));
        }

        return tooltip.ToString();
    }

    private void ShowVessel(EntityUid? vessel, bool busy)
    {
        _shownVessel = vessel;
        _vesselView.SetEntity(vessel);
        _vesselButton.Disabled = busy;

        if (vessel is not { } uid || !_entMan.EntityExists(uid))
        {
            _vesselName.Text = Loc.GetString("medieval-mortar-menu-vessel-none");
            _vesselName.FontColorOverride = MedievalUiStyle.TextFaded;
            _vesselVolume.Text = string.Empty;
            _vesselButton.ToolTip = Loc.GetString("medieval-mortar-menu-vessel-insert-tooltip");
            return;
        }

        _vesselName.Text = NameOf(uid);
        _vesselName.FontColorOverride = MedievalUiStyle.GoldBright;

        // the amount comes with the state; the size of the vessel is known here
        var volume = TotalVolume(_state);
        _vesselVolume.Text = VesselMaxVolume(uid) is { } max
            ? Loc.GetString("medieval-mortar-menu-vessel-volume", ("volume", volume.ToString()), ("max", max.ToString()))
            : volume.ToString();

        _vesselButton.ToolTip = VesselTooltip();
    }

    private string VesselTooltip()
    {
        var tooltip = new StringBuilder(Loc.GetString("medieval-mortar-menu-vessel-eject-tooltip"));

        if (_state?.ReagentQuantities is not { Length: > 0 } reagents)
        {
            tooltip.Append('\n').Append(Loc.GetString("medieval-mortar-menu-vessel-empty"));
            return tooltip.ToString();
        }

        foreach (var (reagent, quantity) in reagents)
        {
            var name = _prototype.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : reagent.Prototype;

            tooltip.Append('\n').Append(Loc.GetString("medieval-mortar-menu-vessel-reagent",
                ("reagent", name), ("amount", quantity.ToString())));
        }

        return tooltip.ToString();
    }

    /// <summary>
    ///     The status line, and which problems it talks about so the window can underline those items.
    ///     Names stay out of it: they can be long, and the underline already shows which item is meant.
    /// </summary>
    private (string Text, Color Color, string[] Flagged) StatusText(int count, ContentsCheck check, EntityUid? vessel)
    {
        if (_working is { } program)
        {
            return (Loc.GetString(program == GrinderProgram.Grind
                ? "medieval-mortar-menu-status-grinding"
                : "medieval-mortar-menu-status-juicing"), MedievalUiStyle.Magic, Array.Empty<string>());
        }

        if (count == 0)
            return Status("medieval-mortar-menu-status-empty", MedievalUiStyle.TextFaded);

        if (vessel == null)
            return Status("medieval-mortar-menu-status-no-vessel", MedievalUiStyle.TextFaded);

        // one program working is enough; nothing to underline then
        if (check.GrindOk && check.JuiceOk)
            return Status("medieval-mortar-menu-status-ready", MedievalUiStyle.Text);

        if (check.GrindOk)
            return Status("medieval-mortar-menu-status-only-grind", MedievalUiStyle.Text);

        if (check.JuiceOk)
            return Status("medieval-mortar-menu-status-only-juice", MedievalUiStyle.Text);

        if (check.CantGrind != null && check.CantJuice != null)
        {
            return Status(check.CantGrind == check.CantJuice
                    ? "medieval-mortar-menu-status-unfit"
                    : "medieval-mortar-menu-status-mixed",
                MedievalUiStyle.Text, ProblemNoGrind, ProblemNoJuice);
        }

        // what a program that can run would leave behind matters more than a program that can't run at all
        if (check.WontFit != null)
            return Status("medieval-mortar-menu-status-wont-fit", MedievalUiStyle.Text, ProblemWontFit);

        if (check.WontFitPressing != null)
            return Status("medieval-mortar-menu-status-wont-fit-pressing", MedievalUiStyle.Text, ProblemWontFitPressing, ProblemWontFit);

        if (check.WontFitGrinding != null)
            return Status("medieval-mortar-menu-status-wont-fit-grinding", MedievalUiStyle.Text, ProblemWontFitGrinding, ProblemWontFit);

        if (check.CantGrind != null)
            return Status("medieval-mortar-menu-status-no-grind", MedievalUiStyle.Text, ProblemNoGrind);

        if (check.CantJuice != null)
            return Status("medieval-mortar-menu-status-no-juice", MedievalUiStyle.Text, ProblemNoJuice);

        return Status("medieval-mortar-menu-status-ready", MedievalUiStyle.Text);
    }

    private static (string, Color, string[]) Status(string locId, Color color, params string[] flagged)
    {
        return (Loc.GetString(locId), color, flagged);
    }

    /// <summary>
    ///     Points at what's in the way, worked out the way the stock grinder does it: a program only runs when
    ///     every item suits it, and whatever doesn't fit into what's left of the vessel is silently left behind.
    ///     These rules mirror the server's ReagentGrinderSystem (Update, CanGrind, CanJuice); if upstream changes
    ///     them, update this and <see cref="LeftBehind"/> too, or the warnings will point at the wrong things.
    /// </summary>
    private ContentsCheck CheckContents(List<EntityUid> contents, EntityUid? vessel)
    {
        var check = new ContentsCheck(contents.Count);

        var grind = new Solution?[contents.Count];
        var juice = new Solution?[contents.Count];
        var allGrind = contents.Count > 0;
        var allJuice = contents.Count > 0;

        for (var i = 0; i < contents.Count; i++)
        {
            grind[i] = GrindSolution(contents[i]);
            juice[i] = JuiceSolution(contents[i]);
            allGrind &= grind[i] != null;
            allJuice &= juice[i] != null;
        }

        // the items each program that can run would leave in the mortar; nothing to fill without a vessel
        var grindLeft = new HashSet<int>();
        var juiceLeft = new HashSet<int>();
        if (vessel is { } uid && VesselMaxVolume(uid) is { } max)
        {
            var free = max - TotalVolume(_state);

            if (allGrind)
                grindLeft = LeftBehind(contents, grind, free);

            if (allJuice)
                juiceLeft = LeftBehind(contents, juice, free);
        }

        for (var i = 0; i < contents.Count; i++)
        {
            var name = NameOf(contents[i]);
            var problems = check.Problems[i];

            if (!allGrind && grind[i] == null)
            {
                problems.Add(ProblemNoGrind);
                check.CantGrind ??= name;
            }

            if (!allJuice && juice[i] == null)
            {
                problems.Add(ProblemNoJuice);
                check.CantJuice ??= name;
            }

            var leftGrinding = grindLeft.Contains(i);
            var leftPressing = juiceLeft.Contains(i);

            if (leftGrinding && leftPressing)
            {
                problems.Add(ProblemWontFit);
                check.WontFit ??= name;
            }
            else if (leftGrinding)
            {
                problems.Add(ProblemWontFitGrinding);
                check.WontFitGrinding ??= name;
            }
            else if (leftPressing)
            {
                problems.Add(ProblemWontFitPressing);
                check.WontFitPressing ??= name;
            }
        }

        check.GrindOk = allGrind && grindLeft.Count == 0;
        check.JuiceOk = allJuice && juiceLeft.Count == 0;

        return check;
    }

    /// <summary>
    ///     Walks the items the way the stock grinder pours them, one after another into what's left of the
    ///     vessel, and returns the ones that wouldn't go in at all. Stacks go in as far as they fit.
    /// </summary>
    private HashSet<int> LeftBehind(List<EntityUid> contents, Solution?[] solutions, FixedPoint2 free)
    {
        var left = new HashSet<int>();

        for (var i = 0; i < contents.Count; i++)
        {
            if (solutions[i] is not { } solution || solution.Volume <= 0)
                continue;

            var volume = solution.Volume;

            if (_entMan.TryGetComponent(contents[i], out StackComponent? stack))
            {
                var fits = Math.Min(stack.Count, (int) Math.Floor(free.Float() / volume.Float()));
                if (fits <= 0)
                {
                    left.Add(i);
                    continue;
                }

                free -= volume * fits;
                continue;
            }

            if (volume > free)
            {
                left.Add(i);
                continue;
            }

            free -= volume;
        }

        return left;
    }

    private FixedPoint2? VesselMaxVolume(EntityUid vessel)
    {
        return _entMan.System<SharedSolutionContainerSystem>().TryGetFitsInDispenser(vessel, out _, out var solution)
            ? solution.MaxVolume
            : null;
    }

    // same checks as the stock grinder
    private Solution? GrindSolution(EntityUid uid)
    {
        if (!_entMan.TryGetComponent(uid, out ExtractableComponent? extractable)
            || extractable.GrindableSolution is not { } solutionName)
            return null;

        return _entMan.System<SharedSolutionContainerSystem>().TryGetSolution(uid, solutionName, out _, out var solution)
            ? solution
            : null;
    }

    private Solution? JuiceSolution(EntityUid uid)
    {
        return _entMan.TryGetComponent(uid, out ExtractableComponent? extractable)
            ? extractable.JuiceSolution
            : null;
    }

    private string NameOf(EntityUid uid)
    {
        return _entMan.TryGetComponent(uid, out MetaDataComponent? meta) ? meta.EntityName : "?";
    }

    private static FixedPoint2 TotalVolume(ReagentGrinderInterfaceState? state)
    {
        var total = FixedPoint2.Zero;

        if (state?.ReagentQuantities == null)
            return total;

        foreach (var reagent in state.ReagentQuantities)
        {
            total += reagent.Quantity;
        }

        return total;
    }

    private Texture? IconOf(EntityUid uid)
    {
        if (_entMan.TryGetComponent(uid, out IconComponent? icon))
            return _entMan.System<SpriteSystem>().GetIcon(icon);

        return _entMan.TryGetComponent(uid, out SpriteComponent? sprite) ? sprite.Icon?.Default : null;
    }

    private sealed class ContentsCheck
    {
        /// <summary>Per item: locale ids of what's in the way, empty if nothing.</summary>
        public readonly List<string>[] Problems;

        public string? CantGrind;
        public string? CantJuice;
        public string? WontFit;
        public string? WontFitGrinding;
        public string? WontFitPressing;

        /// <summary>The program runs and takes everything.</summary>
        public bool GrindOk;
        public bool JuiceOk;

        public ContentsCheck(int count)
        {
            Problems = new List<string>[count];

            for (var i = 0; i < count; i++)
            {
                Problems[i] = new List<string>();
            }
        }
    }

    /// <summary>
    ///     A button with no frame, only a soft background on hover, so the shelf and the vessel row don't turn
    ///     into a wall of boxes.
    /// </summary>
    private sealed class PlainButton : ContainerButton
    {
        private static readonly StyleBoxFlat NormalBox = new() { BackgroundColor = Color.Transparent };
        private static readonly StyleBoxFlat HoverBox = new() { BackgroundColor = MedievalUiStyle.BackgroundHover };
        private static readonly StyleBoxFlat PressedBox = new() { BackgroundColor = MedievalUiStyle.BackgroundPressed };

        protected override void DrawModeChanged()
        {
            base.DrawModeChanged();

            StyleBoxOverride = DrawMode switch
            {
                DrawModeEnum.Hover => HoverBox,
                DrawModeEnum.Pressed => PressedBox,
                _ => NormalBox,
            };
        }
    }
}
