using System.Linq;
using Content.Client.Imperial.Roadmap.UI;
using Content.Shared.Imperial.Medieval.Plague;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Toolshed.Commands.Values;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Plague.UI;

[GenerateTypedNameReferences]
public sealed partial class MedievalPlagueMenu : DefaultWindow
{
    private IPrototypeManager _proto = default!;
    private Dictionary<ProtoId<MedievalPlagueSymptomPrototype>, MedievalPlagueSymptomData> _data = new();
    private SummaryPlagueData _info = new();

    public SymptomCategory Category = SymptomCategory.Symptom;
    public Action<ProtoId<MedievalPlagueSymptomPrototype>>? OnSymptomSelect;
    public Action? InfoPressed;

    public MedievalPlagueMenu()
    {
        RobustXamlLoader.Load(this);

        InfoButton.OnPressed += args => InfoPressed?.Invoke();

        var group = new ButtonGroup(false);
        SpreadMode.Group = group;
        SymptomsMode.Group = group;
        ActionsMode.Group = group;

        SpreadMode.OnToggled += args => SelectMode(SymptomCategory.Spread);
        SymptomsMode.OnToggled += args => SelectMode(SymptomCategory.Symptom);
        ActionsMode.OnToggled += args => SelectMode(SymptomCategory.Action);

        SymptomsMode.Pressed = true;
    }

    public void Populate(IPrototypeManager protoMan, Dictionary<ProtoId<MedievalPlagueSymptomPrototype>, MedievalPlagueSymptomData> dict, SummaryPlagueData info)
    {
        Layout.RemoveAllChildren();
        _proto = protoMan;
        _data = dict;
        _info = info;

        var symptoms = protoMan.EnumeratePrototypes<MedievalPlagueSymptomPrototype>().Where(x => x.Category == Category && ReqsMet(x, dict));
        foreach (var item in symptoms)
        {
            dict.TryGetValue(item.ID, out var data);
            AddItem(item, data, ReqsMet(item, dict));
        }
    }

    private bool ReqsMet(MedievalPlagueSymptomPrototype proto, Dictionary<ProtoId<MedievalPlagueSymptomPrototype>, MedievalPlagueSymptomData> dict)
    {
        var unlocked = dict.Where(x => x.Value.Unlocked && proto.Required.ToList().Contains(x.Key));
        return unlocked.Count() == proto.Required.Count();
    }

    private void AddItem(MedievalPlagueSymptomPrototype proto, MedievalPlagueSymptomData? data, bool reqs)
    {
        var button = new MedievalPlagueSymptomButton(proto, data, reqs);
        button.Button.MouseFilter = MouseFilterMode.Stop;

        Layout.AddChild(button);

        button.OnSelected += args => OnSymptomSelect?.Invoke(args);
        LayoutContainer.SetPosition(button, proto.Position * 3);

        if (data != null && data.Unlocked)
            return;

        PanelContainer panel = new()
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat()
            {
                BackgroundColor = Color.FromHex("#79000cff"),
                BorderColor = Color.FromHex("#aa0c2cff"),
                BorderThickness = new(3f)
            }
        };
        BoxContainer tooltipContainer = new()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new(2)
        };

        panel.AddChild(tooltipContainer);

        var nameLabel = new RichTextLabel()
        {
            Margin = new(2, 0),
            HorizontalAlignment = HAlignment.Center
        };
        nameLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"[bold]{Loc.GetString(proto.Name)}[/bold]"), defaultColor: Color.FromHex("#00b100ff"));
        tooltipContainer.AddChild(nameLabel);

        var progressLabel = new RichTextLabel()
        {
            Margin = new(2, 0)
        };
        progressLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"[bold]Прогресс: {data?.Points ?? 0} / {proto.GetCost(_info)}[/bold]"), defaultColor: Color.FromHex("#00b100ff"));
        tooltipContainer.AddChild(progressLabel);

        if (proto.Required.Count() > 0)
        {
            var label = new RichTextLabel()
            {
                Margin = new(2, 0)
            };

            label.SetMessage(FormattedMessage.FromMarkupOrThrow("[bold]Требует:[/bold]"), defaultColor: Color.FromHex("#00b100ff"));
            tooltipContainer.AddChild(label);
            foreach (var item in proto.Required)
            {
                var reqProto = _proto.Index<MedievalPlagueSymptomPrototype>(item);
                var requiredLabel = new RichTextLabel()
                {
                    Margin = new(2, 0)
                };

                requiredLabel.SetMessage($"- {Loc.GetString(reqProto.Name)}", defaultColor: Color.FromHex("#00b100ff"));
                tooltipContainer.AddChild(requiredLabel);
            }
        }

        button.Button.TooltipSupplier = _ => panel;
        button.Button.TooltipDelay = 0.5f;
    }

    private void SelectMode(SymptomCategory category)
    {
        Category = category;
        Populate(_proto, _data, _info);
    }
}
