using Content.Client.Imperial.UI.Buttons.FancyButton;
using Content.Shared.Imperial.Medieval.Plague;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Plague.UI;

[GenerateTypedNameReferences]
public sealed partial class MedievalPlagueSymptomButton : FancyButton
{
    public Action<ProtoId<MedievalPlagueSymptomPrototype>>? OnSelected;
    public MedievalPlagueSymptomPrototype Proto;

    public (Color, Color, Color) UnavialableColors = (Color.FromHex("#460011ff"), Color.FromHex("#000000ff"), Color.FromHex("#36000eff"));
    public (Color, Color, Color) ProgressColors = (Color.Crimson, Color.FromHex("#240000"), Color.FromHex("#79000cff"));
    public (Color, Color, Color) UnlockedColors = (Color.LimeGreen, Color.FromHex("#002006ff"), Color.FromHex("#007215ff"));

    public MedievalPlagueSymptomButton(MedievalPlagueSymptomPrototype proto, MedievalPlagueSymptomData? data, bool requirmentsMet)
    {
        RobustXamlLoader.Load(this);

        Proto = proto;
        OnPressed += args => OnSelected?.Invoke(proto.ID);

        Texture.Texture = proto.Icon.Frame0();
        UpdateVisuals(data, requirmentsMet);
    }

    public void UpdateVisuals(MedievalPlagueSymptomData? data, bool requirmentsMet)
    {
        if (data == null || !data.Unlocked)
            (BorderColor, Color, HoveredColor) = requirmentsMet ? ProgressColors : UnavialableColors;

        else
            (BorderColor, Color, HoveredColor) = UnlockedColors;

        UpdateColor();
    }
}
