using System.Linq;
using Content.Shared.Imperial.Medieval.Plague;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Toolshed.Commands.Values;

namespace Content.Client.Imperial.Medieval.Plague.UI;

[GenerateTypedNameReferences]
public sealed partial class MedievalPlagueSymptomMiniMenu : DefaultWindow
{
    public Action<ProtoId<MedievalPlagueSymptomPrototype>, int>? OnAddPoints;
    public ProtoId<MedievalPlagueSymptomPrototype> Proto = "";

    public MedievalPlagueSymptomMiniMenu()
    {
        RobustXamlLoader.Load(this);

        OpenSliderButton.OnPressed += args =>
        {
            OpenSliderButton.Visible = false;
            SliderContainer.Visible = true;
        };

        AddPointsButton.OnPressed += args =>
        {
            OpenSliderButton.Visible = false;
            SliderContainer.Visible = true;
            OnAddPoints?.Invoke(Proto, (int)Math.Floor(PointsSlider.Value));
        };

        PointsSlider.OnValueChanged += args => SliderValue.Text = $"{Math.Floor(PointsSlider.Value)}";
    }

    public void Populate(MedievalPlagueSymptomPrototype proto, int maxPoints)
    {
        Proto = proto.ID;
        SymptomName.SetMessage(Loc.GetString(proto.Name));
        SymptomDesc.SetMessage(Loc.GetString(proto.Desc));
        SymptomDisplay.Texture = proto.Icon.Frame0();

        OpenSliderButton.Visible = true;
        OpenSliderButton.Disabled = maxPoints <= 0;
        SliderContainer.Visible = false;

        PointsSlider.MinValue = 1;
        PointsSlider.MaxValue = maxPoints;
        PointsSlider.Value = 1;
        SliderValue.Text = $"{Math.Floor(PointsSlider.Value)}";
    }
}
