using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Plague.UI;

[GenerateTypedNameReferences]
public sealed partial class MedievalPlagueMenu : DefaultWindow
{
    public MedievalPlagueMenu()
    {
        RobustXamlLoader.Load(this);
    }
}
