using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared.Imperial.Medieval.Achievements;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Achievements.UI;

internal enum TreeGate : byte
{
    None = 0,
    Blocked = 1,
    Revealed = 2,
}

[GenerateTypedNameReferences]
public sealed partial class AchievementTreeMenuWindow : MedievalWindow
{
    private readonly IPrototypeManager _proto;
    private readonly IResourceCache _cache;
    private readonly SpriteSystem _spriteSystem;

    private IReadOnlySet<string> _unlocked = new HashSet<string>();
    private IReadOnlyDictionary<string, float> _percents = new Dictionary<string, float>();
    private IReadOnlyDictionary<string, Dictionary<string, int>> _progress = new Dictionary<string, Dictionary<string, int>>();

    private AchievementTreeLayout _treeLayout = default!;
    private float _progressPct = 0f;

    private bool _dragging = false;
    private Vector2 _panOffset = Vector2.Zero;

    private float _zoom = 1f;
    private const float ZoomMin = 0.1f;
    private const float ZoomMax = 2.5f;
    private const float ZoomStep = 0.12f;

    private readonly Dictionary<string, AchievementTreeNode> _nodes = new();
    private readonly Dictionary<string, Vector2> _basePositions = new();
    private readonly Dictionary<(string From, string To), List<Vector2>> _edgeCurves = new();
    private readonly HashSet<string> _rootIds = new();
    private const float NodeSize = 72f;

    private const float RootNodeScale = 1.35f;

    private Dictionary<string, string?> _tabByAchievement = new();
    private string? _currentTab;
    private readonly AchievementTreeViewState _viewState;

    private AchievementDetailWindow? _detailWindow;

    public AchievementTreeMenuWindow(
        IPrototypeManager proto,
        IResourceCache cache,
        SpriteSystem spriteSystem,
        AchievementTreeViewState? viewState = null)
    {
        RobustXamlLoader.Load(this);
        _proto = proto;
        _cache = cache;
        _spriteSystem = spriteSystem;
        _viewState = viewState ?? new AchievementTreeViewState();
        _currentTab = _viewState.CurrentTab;

        _treeLayout = new AchievementTreeLayout
        {
            MouseFilter = Control.MouseFilterMode.Ignore,
        };
        TreePanel.AddChild(_treeLayout);

        TreePanel.OnKeyBindDown += OnTreeKeyDown;
        TreePanel.OnKeyBindUp += OnTreeKeyUp;

        RecenterButton.OnPressed += _ => Recenter();
    }

    public void Populate(
        IReadOnlySet<string> unlocked,
        IReadOnlyDictionary<string, float> percents,
        IReadOnlyDictionary<string, Dictionary<string, int>> progress)
    {
        _unlocked = unlocked;
        _percents = percents;
        _progress = progress;

        UpdateProgressBar();

        if (_nodes.Count == 0)
            BuildTree();
        else
            RefreshNodes();

        _detailWindow?.Refresh(unlocked, percents, progress);
    }

    private void BuildTree()
    {
        _nodes.Clear();
        _basePositions.Clear();
        _edgeCurves.Clear();
        _treeLayout.RemoveAllChildren();

        var protos = _proto.EnumeratePrototypes<AchievementPrototype>().ToList();
        _tabByAchievement = ResolveTabs(protos);
        RebuildTabBar();

        // Restore the camera saved for this tab (or defaults for a fresh one).
        _viewState.CurrentTab = _currentTab;
        RestoreView();

        var (visibleIds, questionMarkIds) = GetVisibleIds(protos);
        var shownIds = visibleIds.Union(questionMarkIds).ToHashSet();

        if (_currentTab != null)
        {
            shownIds = shownIds
                .Where(id => _tabByAchievement.GetValueOrDefault(id) is not { } tab || tab == _currentTab)
                .ToHashSet();
        }

        var visibleProtos = protos.Where(p => shownIds.Contains(p.ID)).ToList();

        _rootIds.Clear();
        foreach (var proto in visibleProtos)
        {
            if (!proto.Prerequisites.Any(req => shownIds.Contains(req.Id)))
                _rootIds.Add(proto.ID);
        }

        var (positions, edgeCurves) = ComputePositions(visibleProtos);

        foreach (var (id, pos) in positions)
            _basePositions[id] = pos;

        foreach (var (key, points) in edgeCurves)
            _edgeCurves[key] = points;

        foreach (var proto in visibleProtos)
        {
            var unlocked = _unlocked.Contains(proto.ID);
            var prereqsMet = ArePrereqsMet(proto, _unlocked);
            var isQuestion = questionMarkIds.Contains(proto.ID);
            var rarity = AchievementRarityHelper.Resolve(proto, _percents.GetValueOrDefault(proto.ID, 0f), _proto);

            var node = new AchievementTreeNode(proto, unlocked, prereqsMet, isQuestion, _spriteSystem, rarity);
            node.OnSelected += OnNodeSelected;

            _nodes[proto.ID] = node;
            _treeLayout.AddChild(node);
        }

        ApplyTransform();
    }

    private static Dictionary<string, string?> ResolveTabs(List<AchievementPrototype> protos)
    {
        var byId = protos.ToDictionary(p => p.ID);
        var resolved = new Dictionary<string, string?>();

        string? Resolve(string id, HashSet<string> visiting)
        {
            if (resolved.TryGetValue(id, out var cached))
                return cached;

            if (!visiting.Add(id))
                return null;

            var proto = byId[id];
            string? tab = proto.Tab;

            if (tab == null)
            {
                foreach (var prereqId in proto.Prerequisites.Select(p => p.Id))
                {
                    if (!byId.ContainsKey(prereqId))
                        continue;

                    tab = Resolve(prereqId, visiting);
                    if (tab != null)
                        break;
                }
            }

            visiting.Remove(id);
            resolved[id] = tab;
            return tab;
        }

        foreach (var proto in protos)
            Resolve(proto.ID, new HashSet<string>());

        return resolved;
    }

    private void RebuildTabBar()
    {
        TabBar.RemoveAllChildren();

        var tabProtos = _tabByAchievement.Values
            .Where(t => t != null)
            .Distinct()
            .Where(id => _proto.HasIndex<AchievementTabPrototype>(id!))
            .Select(id => _proto.Index<AchievementTabPrototype>(id!))
            .OrderBy(t => t.Priority)
            .ThenBy(t => t.Name)
            .ToList();

        if (tabProtos.Count == 0)
        {
            TabBar.Visible = false;
            _currentTab = null;
            return;
        }

        TabBar.Visible = true;

        var group = new ButtonGroup(isNoneSetAllowed: false);
        var keepCurrent = _currentTab != null && tabProtos.Any(t => t.ID == _currentTab);

        foreach (var tabProto in tabProtos)
        {
            var tabId = tabProto.ID;
            var button = new AchievementTabButton
            {
                Icon = _spriteSystem.Frame0(tabProto.Icon),
                ToolTip = Loc.GetString(tabProto.Name),
                Group = group,
            };

            if (keepCurrent && tabId == _currentTab)
                button.Pressed = true;

            button.OnToggled += args =>
            {
                if (!args.Pressed || _currentTab == tabId)
                    return;

                SaveView();
                _currentTab = tabId;
                BuildTree();
            };

            TabBar.AddChild(button);
        }

        if (!keepCurrent)
            _currentTab = tabProtos[0].ID;
    }

    private void RefreshNodes()
    {
        var protos = _proto.EnumeratePrototypes<AchievementPrototype>().ToList();
        var (visibleIds, questionMarkIds) = GetVisibleIds(protos);
        var shownIds = visibleIds.Union(questionMarkIds).ToHashSet();

        if (_currentTab != null)
        {
            shownIds = shownIds
                .Where(id => _tabByAchievement.GetValueOrDefault(id) is not { } tab || tab == _currentTab)
                .ToHashSet();
        }

        if (!shownIds.SetEquals(_nodes.Keys.ToHashSet()))
        {
            BuildTree();
            return;
        }

        foreach (var (id, node) in _nodes)
        {
            var unlocked = _unlocked.Contains(id);
            var prereqsMet = ArePrereqsMet(node.Proto, _unlocked);
            var isQuestion = questionMarkIds.Contains(id);
            var rarity = AchievementRarityHelper.Resolve(node.Proto, _percents.GetValueOrDefault(id, 0f), _proto);
            node.Refresh(unlocked, prereqsMet, isQuestion, _spriteSystem, rarity);
        }

        ApplyTransform();
    }

    private void ApplyTransform()
    {
        var uiScale = UIScale;
        var halfBase = new Vector2(NodeSize / 2f, NodeSize / 2f);
        var halos = new List<AchievementTreeLayout.RootHalo>();

        var panPhys = new Vector2(
            MathF.Round(_panOffset.X * uiScale),
            MathF.Round(_panOffset.Y * uiScale));

        float ToVirtual(float phys) => (phys + 0.01f) / uiScale;

        foreach (var (id, node) in _nodes)
        {
            if (!_basePositions.TryGetValue(id, out var basePos))
                continue;

            var isRoot = _rootIds.Contains(id);
            var scale = isRoot ? RootNodeScale : 1f;

            var baseCenter = basePos + halfBase;
            var sizePhys = MathF.Round(NodeSize * scale * _zoom * uiScale);
            var centerPhys = baseCenter * _zoom * uiScale;
            var posPhys = new Vector2(
                MathF.Round(centerPhys.X - sizePhys / 2f),
                MathF.Round(centerPhys.Y - sizePhys / 2f)) + panPhys;

            LayoutContainer.SetPosition(node, new Vector2(ToVirtual(posPhys.X), ToVirtual(posPhys.Y)));
            node.SetSize = new Vector2(ToVirtual(sizePhys), ToVirtual(sizePhys));
            node.ApplyZoom(_zoom * scale);

            if (isRoot)
            {
                var haloHalfSize = NodeSize * RootNodeScale / 2f;
                halos.Add(new AchievementTreeLayout.RootHalo(baseCenter, haloHalfSize, _unlocked.Contains(id)));
            }
        }

        _treeLayout.Zoom = _zoom;
        _treeLayout.PanOffset = panPhys / uiScale;
        _treeLayout.EdgeCurves = _edgeCurves;
        _treeLayout.RootHalos = halos;
    }

    private (Dictionary<string, Vector2> positions, Dictionary<(string From, string To), List<Vector2>> edgeCurves) ComputePositions(
        List<AchievementPrototype> protos)
    {
        const float StartX = 70f;
        const float StartY = 70f;

        var ordered = protos.ToList();
        ordered.Sort((a, b) =>
        {
            var byPriority = a.Priority.CompareTo(b.Priority);
            return byPriority != 0 ? byPriority : string.CompareOrdinal(a.ID, b.ID);
        });

        var ids = ordered.Select(p => p.ID).ToHashSet();

        var nodes = ordered
            .Select(p => new LayeredTreeLayout.Node(p.ID))
            .ToList();

        var edges = ordered
            .SelectMany(p => p.Prerequisites
                .Where(req => ids.Contains(req.Id))
                .Select(req => new LayeredTreeLayout.Edge(req.Id, p.ID)))
            .ToList();

        var layoutMode = AchievementTabLayout.Tree;
        if (_currentTab != null && _proto.TryIndex<AchievementTabPrototype>(_currentTab, out var tabProto))
            layoutMode = tabProto.Layout;

        LayeredTreeLayout.Result result;

        if (layoutMode == AchievementTabLayout.Radial)
        {
            var settings = new RadialTreeLayout.Settings
            {
                RingStep = 150f,
                NodeSeparation = 40f,
                NodeSize = NodeSize,
            };

            result = RadialTreeLayout.Compute(nodes, edges, settings);
        }
        else
        {
            var settings = new LayeredTreeLayout.Settings
            {
                LayerSeparation = 160f,
                NodeSeparation = 60f,
                NodeSize = NodeSize,
            };

            result = LayeredTreeLayout.Compute(nodes, edges, settings);
        }

        var minX = result.Positions.Count > 0 ? result.Positions.Values.Min(p => p.X) : 0f;
        var minY = result.Positions.Count > 0 ? result.Positions.Values.Min(p => p.Y) : 0f;

        var offset = new Vector2(StartX - minX, StartY - minY);

        var positions = result.Positions.ToDictionary(
            kv => kv.Key,
            kv => kv.Value + offset);

        var edgeCurves = result.EdgeCurves.ToDictionary(
            kv => kv.Key,
            kv => kv.Value.Select(p => p + offset).ToList());

        return (positions, edgeCurves);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        var localPos = args.RelativePosition - TreePanel.Position;
        if (localPos.X < 0 || localPos.Y < 0 || localPos.X > TreePanel.Size.X || localPos.Y > TreePanel.Size.Y)
            return;

        var delta = args.Delta.Y > 0 ? ZoomStep : -ZoomStep;
        var newZoom = Math.Clamp(_zoom + delta, ZoomMin, ZoomMax);

        if (Math.Abs(newZoom - _zoom) < 0.001f)
            return;

        var cursorInTree = args.RelativePosition - TreePanel.Position;
        var worldPoint = (cursorInTree - _panOffset) / _zoom;

        _zoom = newZoom;
        _panOffset = cursorInTree - worldPoint * _zoom;

        SaveView();
        ApplyTransform();
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_dragging)
            return;

        _panOffset += args.Relative;
        SaveView();
        ApplyTransform();
    }

    private void OnTreeKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use || args.Function == EngineKeyFunctions.UseSecondary)
            _dragging = true;
    }

    private void OnTreeKeyUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use || args.Function == EngineKeyFunctions.UseSecondary)
            _dragging = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return _dragging ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    }

    private void Recenter()
    {
        _zoom = 1f;
        _panOffset = Vector2.Zero;
        SaveView();
        ApplyTransform();
    }

    private void SaveView()
    {
        var key = _currentTab ?? string.Empty;
        if (!_viewState.Views.TryGetValue(key, out var view))
            _viewState.Views[key] = view = new AchievementTreeViewState.TabView();

        view.Pan = _panOffset;
        view.Zoom = _zoom;
    }

    private void RestoreView()
    {
        if (_viewState.Views.TryGetValue(_currentTab ?? string.Empty, out var view))
        {
            _panOffset = view.Pan;
            _zoom = view.Zoom;
        }
        else
        {
            _panOffset = Vector2.Zero;
            _zoom = 1f;
        }
    }

    private void OnNodeSelected(AchievementPrototype proto)
    {
        _detailWindow?.Close();
        _detailWindow?.Dispose();

        var unlocked = _unlocked.Contains(proto.ID);
        var percent = _percents.GetValueOrDefault(proto.ID, 0f);
        var rarity = AchievementRarityHelper.Resolve(proto, percent, _proto);
        _progress.TryGetValue(proto.ID, out var condProgress);

        _detailWindow = new AchievementDetailWindow(
            proto, unlocked, percent, rarity, condProgress,
            _unlocked, _proto, _spriteSystem);

        _detailWindow.OpenCentered();
    }

    private void UpdateProgressBar()
    {
        var allVisible = _proto.EnumeratePrototypes<AchievementPrototype>()
            .Where(p => p.Visibility != AchievementVisibility.Hidden || _unlocked.Contains(p.ID))
            .ToList();

        var total = allVisible.Count;
        var done = allVisible.Count(p => _unlocked.Contains(p.ID));

        ProgressLabel.Text = $"{done} / {total}";
        _progressPct = total > 0 ? done * 100f / total : 0f;
        ProgressPercentLabel.Text = $"{_progressPct:F0}%";

        ProgressBarBg.OnResized += OnProgressBarResized;
        OnProgressBarResized();
    }

    private void OnProgressBarResized()
    {
        var w = ProgressBarBg.Size.X;
        if (w > 0)
            ProgressBarFill.MinWidth = (int)(w * (_progressPct / 100f));
    }

    internal static string BlurText(string text)
    {
        var chars = text.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
            if (!char.IsWhiteSpace(chars[i]))
                chars[i] = '█';
        return new string(chars);
    }

    internal static bool ArePrereqsMet(AchievementPrototype proto, IReadOnlySet<string> unlocked)
    {
        foreach (var prereq in proto.Prerequisites)
        {
            if (!unlocked.Contains(prereq.Id))
                return false;
        }
        return true;
    }

    private (HashSet<string> visible, HashSet<string> questionMark) GetVisibleIds(
        List<AchievementPrototype> protos)
    {
        var byId = protos.ToDictionary(p => p.ID);
        var children = protos.ToDictionary(p => p.ID, _ => new List<string>());
        var parents = protos.ToDictionary(p => p.ID, _ => new List<string>());

        foreach (var p in protos)
            foreach (var req in p.Prerequisites)
                if (children.ContainsKey(req.Id))
                {
                    children[req.Id].Add(p.ID);
                    parents[p.ID].Add(req.Id);
                }

        var visible = new HashSet<string>();
        var questionMark = new HashSet<string>();

        var queue = new Queue<(string id, TreeGate gate)>();

        foreach (var p in protos.Where(p => parents[p.ID].Count == 0))
            queue.Enqueue((p.ID, TreeGate.None));

        var visited = new HashSet<string>();

        while (queue.Count > 0)
        {
            var (id, gate) = queue.Dequeue();
            if (!visited.Add(id))
                continue;

            if (!byId.TryGetValue(id, out var proto))
                continue;

            bool unlocked = _unlocked.Contains(id);

            switch (gate)
            {
                case TreeGate.Blocked:
                    continue;

                case TreeGate.Revealed:
                    questionMark.Add(id);
                    break;

                case TreeGate.None:
                    if (proto.Visibility == AchievementVisibility.Hidden && !unlocked)
                        continue;

                    visible.Add(id);
                    break;
            }

            TreeGate childGate;

            if (gate != TreeGate.None)
            {
                childGate = unlocked ? TreeGate.None : gate;
            }
            else if (!unlocked)
            {
                childGate = proto.Visibility switch
                {
                    AchievementVisibility.Blocking => TreeGate.Blocked,
                    AchievementVisibility.BlockingRevealed => TreeGate.Revealed,
                    _ => TreeGate.None,
                };
            }
            else
            {
                childGate = TreeGate.None;
            }

            foreach (var childId in children[id])
                queue.Enqueue((childId, childGate));
        }

        questionMark.ExceptWith(visible);
        return (visible, questionMark);
    }
}
