using Content.Shared.Imperial.Medieval.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class AchievementTooltipPopup : PanelContainer
{
    private static readonly Color QuestionAccent = Color.FromHex("#4a3a28");
    private static readonly Color UnlockedAccent = Color.FromHex("#5c8a3e");
    private static readonly Color LockedAccent = Color.FromHex("#8b6914");

    private static readonly Color NameUnlocked = Color.FromHex("#e8d5a8");
    private static readonly Color NameLocked = Color.FromHex("#9e8c78");
    private static readonly Color NameHidden = Color.FromHex("#5a4830");

    private static readonly Color DescriptionColor = Color.FromHex("#a29077");
    private static readonly Color DescriptionHidden = Color.FromHex("#2b2014");

    public AchievementTooltipPopup(
        AchievementPrototype proto,
        bool unlocked,
        SpriteSystem spriteSystem,
        bool questionMark = false,
        AchievementRarityPrototype? rarity = null)
    {
        RobustXamlLoader.Load(this);

        var isHidden = !questionMark && proto.Visibility == AchievementVisibility.Hidden && !unlocked;
        var obscured = questionMark || isHidden;

        var accent = obscured ? QuestionAccent
            : rarity != null ? Color.FromHex(rarity.AccentColor)
            : unlocked ? UnlockedAccent
            : LockedAccent;

        IconPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0a0704"),
            BorderColor = obscured ? Color.FromHex("#3d2e1e") : accent,
            BorderThickness = new Thickness(2),
            ContentMarginLeftOverride = 5,
            ContentMarginRightOverride = 5,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5,
        };

        AccentDivider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent.WithAlpha(obscured ? 0.35f : 0.6f),
        };

        if (questionMark)
        {
            AchievementIcon.Visible = false;
            HiddenLabel.Visible = true;

            NameLabel.Text = "???";
            NameLabel.FontColorOverride = NameHidden;

            SubtitleLabel.Text = Loc.GetString("achievement-tooltip-secret");
            SubtitleLabel.FontColorOverride = QuestionAccent;
            SubtitleLabel.Visible = true;

            BodyPanel.Visible = false;
            FooterPanel.Visible = false;
            return;
        }

        if (!isHidden)
        {
            AchievementIcon.Texture = spriteSystem.Frame0(proto.Icon);

            if (!unlocked)
                AchievementIcon.ModulateSelfOverride = Color.FromHex("#665533");

            AchievementIcon.Visible = true;
            HiddenLabel.Visible = false;
        }
        else
        {
            AchievementIcon.Visible = false;
            HiddenLabel.Visible = true;
        }

        var name = Loc.GetString(proto.Name ?? proto.ID);
        NameLabel.Text = isHidden ? AchievementTreeMenuWindow.BlurText(name) : name;
        NameLabel.FontColorOverride = isHidden ? NameHidden
            : unlocked ? NameUnlocked
            : NameLocked;

        if (rarity != null && !isHidden)
        {
            SubtitleLabel.Text = Loc.GetString(rarity.Name);
            SubtitleLabel.FontColorOverride = Color.FromHex(rarity.AccentColor);
            SubtitleLabel.Visible = true;
        }

        if (!string.IsNullOrEmpty(proto.Description))
        {
            var desc = Loc.GetString(proto.Description).Trim();

            var msg = new FormattedMessage();
            msg.PushColor(isHidden ? DescriptionHidden : DescriptionColor);
            msg.AddText(isHidden ? AchievementTreeMenuWindow.BlurText(desc) : desc);
            msg.Pop();

            DescriptionLabel.SetMessage(msg);
            BodyPanel.Visible = true;
        }
        else
        {
            BodyPanel.Visible = false;
        }

        FooterPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = unlocked ? Color.FromHex("#0e1a0acc") : Color.FromHex("#1a1108cc"),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5,
        };

        FooterLabel.Text = Loc.GetString(unlocked ? "achievement-tooltip-completed" : "achievement-tooltip-locked");
        FooterLabel.FontColorOverride = unlocked ? UnlockedAccent : LockedAccent;
    }
}
