using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared.Imperial.Medieval.Achievements;
using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class AchievementDetailWindow : MedievalWindow
{
    private readonly AchievementPrototype _proto;
    private readonly IPrototypeManager _protoManager;
    private readonly SpriteSystem _spriteSystem;

    private IReadOnlySet<string> _unlocked = new HashSet<string>();
    private IReadOnlyDictionary<string, float> _percents = new Dictionary<string, float>();
    private IReadOnlyDictionary<string, Dictionary<string, int>> _progress = new Dictionary<string, Dictionary<string, int>>();

    public AchievementDetailWindow(
        AchievementPrototype proto,
        bool unlocked,
        float percent,
        AchievementRarityPrototype? rarity,
        Dictionary<string, int>? condProgress,
        IReadOnlySet<string> allUnlocked,
        IPrototypeManager protoManager,
        SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);

        _proto        = proto;
        _protoManager = protoManager;
        _spriteSystem = spriteSystem;
        _unlocked     = allUnlocked;

        Build(unlocked, percent, rarity, condProgress);
    }

    public void Refresh(
        IReadOnlySet<string> unlocked,
        IReadOnlyDictionary<string, float> percents,
        IReadOnlyDictionary<string, Dictionary<string, int>> progress)
    {
        _unlocked = unlocked;
        _percents = percents;
        _progress = progress;

        var isUnlocked = unlocked.Contains(_proto.ID);
        var percent    = percents.GetValueOrDefault(_proto.ID, 0f);
        var rarity     = AchievementRarityHelper.Resolve(_proto, percent, _protoManager);
        progress.TryGetValue(_proto.ID, out var condProg);

        HeaderContainer.RemoveAllChildren();
        ContentContainer.RemoveAllChildren();
        Build(isUnlocked, percent, rarity, condProg);
    }

    private void Build(bool unlocked, float percent, AchievementRarityPrototype? rarity, Dictionary<string, int>? condProgress)
    {
        var isHidden = _proto.Visibility == AchievementVisibility.Hidden && !unlocked;

        BuildLeftSummary(unlocked, percent, rarity, isHidden);
        BuildDescription(unlocked, isHidden);
        BuildConditions(unlocked, isHidden, condProgress);
    }

    private void BuildLeftSummary(bool unlocked, float percent, AchievementRarityPrototype? rarity, bool isHidden)
    {
        HeaderContainer.AddChild(BuildIcon(unlocked, rarity, isHidden));

        var nameText = isHidden
            ? AchievementTreeMenuWindow.BlurText(Loc.GetString(_proto.Name ?? _proto.ID))
            : Loc.GetString(_proto.Name ?? _proto.ID);

        HeaderContainer.AddChild(new Label
        {
            Text = nameText,
            FontColorOverride = unlocked ? Color.FromHex("#d3bc8e") : Color.FromHex("#7a6650"),
            StyleClasses = { "LabelHeading" },
            HorizontalAlignment = Control.HAlignment.Center,
            Align = Label.AlignMode.Center,
            ClipText = false
        });

        if (rarity != null)
        {
            HeaderContainer.AddChild(new Label
            {
                Text = Loc.GetString(rarity.Name),
                FontColorOverride = Color.FromHex(rarity.AccentColor),
                HorizontalAlignment = Control.HAlignment.Center
            });
        }

        HeaderContainer.AddChild(new Label
        {
            Text = $"{percent:F1}% {Loc.GetString("achievement-percent-players")}",
            FontColorOverride = Color.FromHex("#5c4a3d"),
            HorizontalAlignment = Control.HAlignment.Center
        });

        if (_proto.Prerequisites.Count > 0 && !isHidden)
            BuildPrerequisitesList();
    }

    private void BuildPrerequisitesList()
    {
        HeaderContainer.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            SetHeight = 1,
            Margin = new Thickness(0, 6, 0, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#3d2e1e") }
        });

        var scroll = new ScrollContainer
        {
            HScrollEnabled = false,
            VerticalExpand = true,
            HorizontalExpand = true,
        };

        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };

        foreach (var prereqId in _proto.Prerequisites)
        {
            if (!_protoManager.TryIndex<AchievementPrototype>(prereqId, out var prereq))
                continue;

            var isUnlocked = _unlocked.Contains(prereqId);

            var row = new PanelContainer { HorizontalExpand = true };
            row.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1a1005cc"),
                BorderColor = isUnlocked
                    ? Color.FromHex("#5c8a3e")
                    : Color.FromHex("#6b4c1a"),
                BorderThickness = new Thickness(2, 0, 0, 0),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            };

            var msg = new FormattedMessage();
            msg.PushColor(isUnlocked ? Color.FromHex("#c8b88a") : Color.FromHex("#7a6650"));
            msg.AddText(Loc.GetString(prereq.Name ?? prereq.ID));
            msg.Pop();

            var label = new RichTextLabel { HorizontalExpand = true };
            label.SetMessage(msg);
            row.AddChild(label);
            list.AddChild(row);
        }

        scroll.AddChild(list);
        HeaderContainer.AddChild(scroll);
    }

    private PanelContainer BuildIcon(bool unlocked, AchievementRarityPrototype? rarity, bool isHidden)
    {
        var iconBorder = rarity != null ? Color.FromHex(rarity.AccentColor)
                        : unlocked      ? Color.FromHex("#5c8a3e")
                                        : Color.FromHex("#3d2e1e");

        var iconPanel = new PanelContainer
        {
            SetSize = new Vector2(120, 120),
            HorizontalAlignment = Control.HAlignment.Center
        };

        iconPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#110d09"),
            BorderColor = iconBorder,
            BorderThickness = new Thickness(3),
            ContentMarginLeftOverride = 8, ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 8, ContentMarginBottomOverride = 8,
        };

        if (!isHidden)
        {
            var iconRect = new TextureRect
            {
                Texture = _spriteSystem.Frame0(_proto.Icon),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
            };

            if (!unlocked)
                iconRect.ModulateSelfOverride = Color.FromHex("#55443388");

            iconPanel.AddChild(iconRect);
        }
        else
        {
            iconPanel.AddChild(new Label
            {
                Text = "?",
                FontColorOverride = Color.FromHex("#4a3828"),
                StyleClasses = { "LabelHeadingBigger" },
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center
            });
        }

        return iconPanel;
    }

    private void BuildDescription(bool unlocked, bool isHidden)
    {
        var raw = Loc.GetString(_proto.Description ?? string.Empty);
        var descText = isHidden ? AchievementTreeMenuWindow.BlurText(raw) : raw;

        if (string.IsNullOrWhiteSpace(descText))
            return;

        var descPanel = new PanelContainer { HorizontalExpand = true };
        descPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#160f08cc"),
            ContentMarginLeftOverride = 16,
            ContentMarginRightOverride = 16,
            ContentMarginTopOverride = 16,
            ContentMarginBottomOverride = 16,
        };

        var descMsg = new FormattedMessage();
        descMsg.PushColor(isHidden ? Color.FromHex("#251b12") : Color.FromHex("#9e8c78"));
        descMsg.AddText(descText);
        descMsg.Pop();

        var descLabel = new RichTextLabel { HorizontalExpand = true };
        descLabel.SetMessage(descMsg);
        descPanel.AddChild(descLabel);
        ContentContainer.AddChild(descPanel);
    }

    private void BuildConditions(bool unlocked, bool isHidden, Dictionary<string, int>? condProgress)
    {
        if (_proto.Conditions is not { Count: > 0 } || isHidden)
            return;

        int completedCount = 0;
        foreach (var condition in _proto.Conditions)
        {
            int req     = condition.GetTargetProgress();
            int current = unlocked ? req : condition.GetCurrentProgress(condProgress);

            if (current >= req)
                completedCount++;
        }

        int totalConditions = _proto.Conditions.Count;

        AddConditionsHeader(Loc.GetString("achievement-detail-conditions-header"),
            completedCount, totalConditions);

        bool isFirst = true;

        foreach (var condition in _proto.Conditions)
        {
            int req     = condition.GetTargetProgress();
            int current = unlocked ? req : condition.GetCurrentProgress(condProgress);
            bool condDone = current >= req;

            if (!isFirst)
            {
                ContentContainer.AddChild(new HSeparator(Color.FromHex("#3d2e1e"))
                {
                    Margin = new Thickness(0, 0, 0, 0)
                });
            }

            BuildConditionRow(condition, current, req, condDone);
            isFirst = false;
        }
    }

    private void AddConditionsHeader(string text, int done, int total)
    {
        var allDone = done >= total;

        var headerBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 12, 0, 0),
        };

        var headerPanel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1a1108"),
                ContentMarginLeftOverride = 16,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };

        headerPanel.AddChild(new Label
        {
            Text = text,
            FontColorOverride = Color.FromHex("#8b6914"),
        });

        headerBox.AddChild(headerPanel);

        var badgePanel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = allDone ? Color.FromHex("#1a3312") : Color.FromHex("#1a1108"),
                ContentMarginLeftOverride = 14,
                ContentMarginRightOverride = 14,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
            }
        };

        badgePanel.AddChild(new Label
        {
            Text = $"{done} / {total}",
            FontColorOverride = allDone ? Color.FromHex("#5c8a3e") : Color.FromHex("#8b6914"),
        });

        headerBox.AddChild(badgePanel);
        ContentContainer.AddChild(headerBox);
    }

    private void BuildConditionRow(
        AchievementCondition condition,
        int current,
        int req,
        bool condDone)
    {
        var accentColor = condDone ? Color.FromHex("#5c8a3e") : Color.FromHex("#8b6914");
        var bgColor     = condDone ? Color.FromHex("#0e1a0a") : Color.FromHex("#1a130d");

        var condPanel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bgColor,
                ContentMarginLeftOverride = 12,
                ContentMarginRightOverride = 12,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = req > 1 ? 4 : 8,
            }
        };

        var colBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var topRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        var descLabel = new RichTextLabel { HorizontalExpand = true };
        descLabel.SetMessage(condition.GetDescription(_protoManager));
        topRow.AddChild(descLabel);

        colBox.AddChild(topRow);

        if (req > 1)
        {
            float pct = Math.Clamp((float)current / req, 0f, 1f);
            colBox.AddChild(BuildInlineProgressBar(current, req, pct, accentColor));
        }

        condPanel.AddChild(colBox);
        ContentContainer.AddChild(condPanel);
    }

    private Control BuildInlineProgressBar(int current, int req, float pct, Color accentColor)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 3,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var barRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        var barBg = new PanelContainer
        {
            HorizontalExpand = true,
            SetHeight = 8,
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#150f08") },
        };

        var barFill = new PanelContainer
        {
            SetHeight = 8,
            PanelOverride = new StyleBoxFlat { BackgroundColor = accentColor },
        };

        barBg.OnResized += () =>
        {
            barFill.MinWidth = Math.Max(2, (int)(barBg.Size.X * pct));
        };

        barBg.AddChild(barFill);
        barRow.AddChild(barBg);
        container.AddChild(barRow);

        container.AddChild(new Label
        {
            Text = $"{current} / {req}",
            FontColorOverride = Color.FromHex("#7b6a58"),
            StyleClasses = { StyleNano.StyleClassLabelSmall },
        });

        return container;
    }
}
