using System.Numerics;
using Content.Shared.Imperial.Medieval.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Achievements.UI;

[GenerateTypedNameReferences]
public sealed partial class AchievementTooltipPopup : PanelContainer
{
    public AchievementTooltipPopup(
        AchievementPrototype proto,
        bool unlocked,
        SpriteSystem spriteSystem,
        bool questionMark = false)
    {
        RobustXamlLoader.Load(this);

        if (questionMark)
        {
            if (IconPanel.PanelOverride is StyleBoxFlat iconStyle)
                iconStyle.BorderColor = Color.FromHex("#4a3a28");

            AchievementIcon.Visible = false;
            HiddenLabel.Visible     = true;

            NameLabel.Text = "???";
            NameLabel.FontColorOverride = Color.FromHex("#5a4830");

            BodyPanel.Visible = false;
            return;
        }

        var isHidden = proto.Visibility == AchievementVisibility.Hidden && !unlocked;

        if (IconPanel.PanelOverride is StyleBoxFlat style)
            style.BorderColor = unlocked ? Color.FromHex("#5c8a3e") : Color.FromHex("#3d2e1e");

        if (!isHidden)
        {
            AchievementIcon.Texture = spriteSystem.Frame0(proto.Icon);

            if (!unlocked)
                AchievementIcon.ModulateSelfOverride = Color.FromHex("#665533");

            AchievementIcon.Visible = true;
            HiddenLabel.Visible     = false;
        }
        else
        {
            AchievementIcon.Visible = false;
            HiddenLabel.Visible     = true;
        }

        var nameText = isHidden
            ? AchievementTreeMenuWindow.BlurText(Loc.GetString(proto.Name ?? proto.ID))
            : Loc.GetString(proto.Name ?? proto.ID);

        NameLabel.Text            = nameText;
        NameLabel.FontColorOverride = unlocked ? Color.FromHex("#d3bc8e") : Color.FromHex("#9e8c78");

        if (!string.IsNullOrEmpty(proto.Description))
        {
            var descText = isHidden
                ? AchievementTreeMenuWindow.BlurText(Loc.GetString(proto.Description))
                : Loc.GetString(proto.Description).Trim();

            DescriptionLabel.ModulateSelfOverride = isHidden
                ? Color.FromHex("#251b12")
                : Color.FromHex("#7b6a55");
            DescriptionLabel.SetMessage(descText);
            BodyPanel.Visible = true;
        }
        else
        {
            BodyPanel.Visible = false;
        }
    }
}
