using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Calendar.Board;

[GenerateTypedNameReferences]
public sealed partial class AnnouncementCreateWindow : DefaultWindow
{
    public Action<string, string, string>? OnSubmit;
    private const int MaxDescLength = 256;

    public AnnouncementCreateWindow()
    {
        RobustXamlLoader.Load(this);

        DescPanel.PanelOverride = new StyleBoxFlat
        {
            BorderThickness = new Thickness(1)
        };

        DescInput.OnTextChanged += _ => CheckSubmitConditions();
        TitleInput.OnTextChanged += _ => CheckSubmitConditions();

        CheckSubmitConditions();

        SubmitButton.OnPressed += _ =>
        {
            var descText = Rope.Collapse(DescInput.TextRope);

            if (string.IsNullOrWhiteSpace(TitleInput.Text) || string.IsNullOrWhiteSpace(descText) || descText.Length > MaxDescLength)
                return;

            OnSubmit?.Invoke(TitleInput.Text, descText, AuthorInput.Text);
            Close();
        };
    }

    private void CheckSubmitConditions()
    {
        var titleValid = !string.IsNullOrWhiteSpace(TitleInput.Text);
        var descValid = DescInput.TextLength > 0 && DescInput.TextLength <= MaxDescLength;

        SubmitButton.Disabled = !titleValid || !descValid;
    }
}
