using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;

[GenerateTypedNameReferences]
[Virtual]
public partial class MedievalWindow : BaseWindow
{
    public float WindowEdgeSeparation = 30;
    public float WindowEdgeBump = 50;
    public DirectionFlag AllowOffScreen = ~DirectionFlag.North;

    private const int DRAG_MARGIN_SIZE = 7;
    private const float HEADER_SIZE_Y = 32;

    protected virtual Vector2 ContentsMinimumSize => new(50, 50);

    public MedievalWindow()
    {
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;

        WindowHeader.MinSize = new Vector2(0, HEADER_SIZE_Y);

        Contents = ContentsContainer;

        CloseButton.OnPressed += CloseButtonPressed;
        XamlChildren = new MedievalContentCollection(this);
    }

    public Control Contents { get; private set; }

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        return Vector2.Max(
            ContentsMinimumSize,
            base.MeasureOverride(Vector2.Max(availableSize, ContentsMinimumSize)));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            CloseButton.OnPressed -= CloseButtonPressed;
        }
    }

    private void CloseButtonPressed(BaseButton.ButtonEventArgs args)
    {
        Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (!IsMeasureValid)
            return;

        var (spaceX, spaceY) = Parent!.Size;

        var maxX = spaceX - ((AllowOffScreen & DirectionFlag.West) == 0 ? Size.X : WindowEdgeSeparation);
        var maxY = spaceY - ((AllowOffScreen & DirectionFlag.South) == 0 ? Size.Y : WindowEdgeSeparation);

        if (Position.X > spaceX)
            maxX -= WindowEdgeBump;

        if (Position.Y > spaceY)
            maxY -= WindowEdgeBump;

        var pos = Vector2.Min(Position, new Vector2(maxX, maxY));

        var minX = (AllowOffScreen & DirectionFlag.East) == 0 ? 0 : WindowEdgeSeparation - Size.X;
        var minY = (AllowOffScreen & DirectionFlag.North) == 0 ? 0 : WindowEdgeSeparation - Size.Y;

        pos = Vector2.Max(pos, new Vector2(minX, minY));
        if (Position != pos)
            LayoutContainer.SetPosition(this, pos);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.None;

        if (Resizable)
        {
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
                mode = DragMode.Top;
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
                mode = DragMode.Bottom;

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
                mode |= DragMode.Left;
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
                mode |= DragMode.Right;
        }

        if (mode == DragMode.None && relativeMousePos.Y < HEADER_SIZE_Y)
            mode = DragMode.Move;

        return mode;
    }

    public sealed class MedievalContentCollection : ICollection<Control>, IReadOnlyCollection<Control>
    {
        private readonly MedievalWindow Owner;

        public MedievalContentCollection(MedievalWindow owner)
        {
            Owner = owner;
        }

        public Enumerator GetEnumerator() => new(Owner);
        IEnumerator<Control> IEnumerable<Control>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public void Add(Control item) => Owner.Contents.AddChild(item);
        public void Clear() => Owner.Contents.RemoveAllChildren();
        public bool Contains(Control item) => item?.Parent == Owner.Contents;

        public void CopyTo(Control[] array, int arrayIndex) =>
            Owner.Contents.Children.CopyTo(array, arrayIndex);

        public bool Remove(Control item)
        {
            if (item?.Parent != Owner.Contents)
                return false;

            DebugTools.AssertNotNull(Owner?.Contents);
            Owner!.Contents.RemoveChild(item);
            return true;
        }

        int ICollection<Control>.Count => Owner.Contents.ChildCount;
        int IReadOnlyCollection<Control>.Count => Owner.Contents.ChildCount;
        public bool IsReadOnly => false;

        public struct Enumerator : IEnumerator<Control>
        {
            private OrderedChildCollection.Enumerator _enumerator;

            internal Enumerator(MedievalWindow window)
            {
                _enumerator = window.Contents.Children.GetEnumerator();
            }

            public bool MoveNext() => _enumerator.MoveNext();
            public void Reset() => _enumerator.Reset();
            public Control Current => _enumerator.Current;
            object IEnumerator.Current => Current;
            public void Dispose() => _enumerator.Dispose();
        }
    }
}