using System.Numerics;
using Content.Client.Shuttles.UI;
using Content.Shared.Imperial.Medieval.SurveyMap;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.SurveyMap;

/// <summary>Regional terrain and the notes on one physical, hand-drawn map.</summary>
[GenerateTypedNameReferences]
public sealed partial class MedievalSurveyMapControl : BaseShuttleControl
{
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly ITileDefinitionManager _tileDefinitions = default!;
    private readonly SharedTransformSystem _transform;
    private readonly SharedShuttleSystem _shuttles;
    private List<Entity<MapGridComponent>> _grids = new();
    private Vector2[] _silhouetteVertices = Array.Empty<Vector2>();
    private readonly Dictionary<EntityUid, GeographyDrawData> _geographyData = new();
    private readonly Dictionary<int, Color> _terrainColors = new();
    private EntityCoordinates? _coordinates;

    private sealed class GeographyDrawData
    {
        public GameTick? LastBuild;
        public readonly Dictionary<Color, List<Vector2>> Vertices = new();
    }

    public List<MedievalSurveyMapAnnotation> Annotations = new();
    public int? DisplayedWorldMap;
    public int SelectedAnnotation = -1;
    public Action<int>? OnSelectAnnotation;
    protected override bool Draggable => true;

    public MedievalSurveyMapControl() : base(32f, 256f, 256f)
    {
        RobustXamlLoader.Load(this);
        _transform = EntManager.System<SharedTransformSystem>();
        _shuttles = EntManager.System<SharedShuttleSystem>();
        SetSize = new Vector2(float.NaN, float.NaN);
    }

    public void UpdateState(MedievalSurveyMapGeography state)
    {
        var coordinates = EntManager.GetCoordinates(state.Coordinates);
        if (_coordinates == null || _coordinates.Value.EntityId != coordinates.EntityId)
        {
            WorldRange = state.Range;
            ActualRadarRange = state.Range;
            Offset = Vector2.Zero;
        }
        _coordinates = coordinates;
        WorldMaxRange = state.Range;
        WorldMinRange = Math.Min(32, state.Range);
        WorldRange = Math.Clamp(WorldRange, WorldMinRange, WorldMaxRange);
        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);
    }

    public void ClearState()
    {
        _coordinates = null;
        _geographyData.Clear();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        DrawBacking(handle);
        if (_coordinates == null ||
            !EntManager.TryGetComponent<TransformComponent>(_coordinates.Value.EntityId, out var xform) ||
            xform.MapID == MapId.Nullspace)
            return;

        var center = _transform.ToMapCoordinates(_coordinates.Value).Position + Offset;
        var worldToView = GetWorldToView();
        var extent = Math.Max(PixelWidth, PixelHeight) / Math.Max(1f, Math.Min(PixelWidth, PixelHeight)) * WorldRange;
        var bounds = new Box2(center - new Vector2(extent), center + new Vector2(extent));
        var rootGrid = _coordinates.Value.EntityId;
        if (EntManager.TryGetComponent<MapGridComponent>(rootGrid, out var terrain))
            DrawGeography(handle, _transform.GetWorldMatrix(rootGrid) * worldToView, (rootGrid, terrain));

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, bounds, ref _grids, approx: true, includeMap: true);
        foreach (var grid in _grids)
        {
            if (grid.Owner == rootGrid || !EntManager.HasComponent<FixturesComponent>(grid.Owner) ||
                !EntManager.TryGetComponent<PhysicsComponent>(grid.Owner, out var body))
                continue;
            EntManager.TryGetComponent<IFFComponent>(grid.Owner, out var iff);
            if (!_shuttles.CanDraw(grid.Owner, body, iff))
                continue;
            DrawGeography(handle, _transform.GetWorldMatrix(grid.Owner) * worldToView, grid);
        }
        DrawAnnotations(handle, worldToView);
        DrawWorldCoordinates(handle, center);
    }

    private Matrix3x2 GetWorldToView()
    {
        var center = _transform.ToMapCoordinates(_coordinates!.Value).Position + Offset;
        var radius = MathF.Max(0, MathF.Min(PixelWidth, PixelHeight) / 2f - MinimapMargin * UIScale);
        var scale = WorldRange > 0 ? radius / WorldRange : 0;
        return Matrix3x2.CreateTranslation(-center) * Matrix3x2.CreateScale(scale, -scale) *
               Matrix3x2.CreateTranslation(new Vector2(PixelWidth, PixelHeight) / 2f);
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        var previousOffset = Offset;
        base.MouseMove(args);
        var radius = MathF.Min(Width, Height) / 2f - MinimapMargin;
        if (radius > 0)
            Offset = previousOffset + (Offset - previousOffset) * (MidPoint / radius);
    }

    private void DrawAnnotations(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        for (var i = 0; i < Annotations.Count; i++)
        {
            if (Annotations[i].WorldMap != DisplayedWorldMap)
                continue;

            var point = Vector2.Transform(Annotations[i].WorldPosition, worldToView);
            if (!((UIBox2) PixelSizeBox).Contains(point))
                continue;

            handle.DrawCircle(point, 11 * UIScale, Color.Black);
            handle.DrawCircle(point, 9 * UIScale, i == SelectedAnnotation ? Color.Gold : Color.DarkRed);
            var label = (i + 1).ToString();
            var dimensions = handle.GetDimensions(Font, label, UIScale);
            handle.DrawString(Font, point + new Vector2(-dimensions.X / 2f, dimensions.Y / 2f), label, UIScale, Color.White);
        }
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        if (args.Function != EngineKeyFunctions.UIClick ||
            _coordinates == null || !((UIBox2) PixelSizeBox).Contains(args.RelativePixelPosition) ||
            !EntManager.TryGetComponent<TransformComponent>(_coordinates.Value.EntityId, out var xform) ||
            xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var worldToView = GetWorldToView();
        var closest = -1;
        var closestDistance = 16 * UIScale;
        for (var i = 0; i < Annotations.Count; i++)
        {
            if (Annotations[i].WorldMap != DisplayedWorldMap)
                continue;

            var point = Vector2.Transform(Annotations[i].WorldPosition, worldToView);
            if (!((UIBox2) PixelSizeBox).Contains(point))
                continue;

            var distance = Vector2.Distance(args.RelativePixelPosition, point);
            if (distance > closestDistance)
                continue;

            closest = i;
            closestDistance = distance;
        }

        if (closest < 0)
            return;

        OnSelectAnnotation?.Invoke(closest);
        args.Handle();
    }

    private void DrawWorldCoordinates(DrawingHandleScreen handle, Vector2 position)
    {
        var text = Loc.GetString(
            "medieval-cartographer-table-coordinates",
            ("x", position.X.ToString("F0")),
            ("y", position.Y.ToString("F0")));
        var dimensions = handle.GetDimensions(Font, text, 1f);
        const float margin = 8f;
        const float padding = 4f;
        var textPosition = new Vector2(PixelWidth - dimensions.X - margin, margin);
        var background = new UIBox2(
            textPosition - new Vector2(padding),
            textPosition + dimensions + new Vector2(padding));

        handle.DrawRect(background, Color.Black.WithAlpha(0.65f));
        handle.DrawString(Font, textPosition, text, Color.White);
    }

    private void DrawGeography(DrawingHandleScreen handle, Matrix3x2 gridToView, Entity<MapGridComponent> grid)
    {
        if (!_geographyData.TryGetValue(grid.Owner, out var data))
        {
            data = new GeographyDrawData();
            _geographyData.Add(grid.Owner, data);
        }

        if (data.LastBuild == null || data.LastBuild < grid.Comp.LastTileModifiedTick)
        {
            data.Vertices.Clear();
            var tiles = Maps.GetAllTilesEnumerator(grid.Owner, grid.Comp);
            var tileSize = grid.Comp.TileSize;
            while (tiles.MoveNext(out var tileRef))
            {
                var color = GetTerrainColor(tileRef.Value.Tile.TypeId);
                if (!data.Vertices.TryGetValue(color, out var vertices))
                {
                    vertices = new List<Vector2>();
                    data.Vertices.Add(color, vertices);
                }

                var bottomLeft = Maps.TileToVector(grid, tileRef.Value.GridIndices);
                var bottomRight = bottomLeft + new Vector2(tileSize, 0);
                var topRight = bottomLeft + new Vector2(tileSize);
                var topLeft = bottomLeft + new Vector2(0, tileSize);
                vertices.Add(bottomLeft);
                vertices.Add(bottomRight);
                vertices.Add(topLeft);
                vertices.Add(bottomRight);
                vertices.Add(topLeft);
                vertices.Add(topRight);
            }
            data.LastBuild = grid.Comp.LastTileModifiedTick;
        }

        const int batchSize = 3 * 4096;
        foreach (var (color, vertices) in data.Vertices)
        {
            Extensions.EnsureLength(ref _silhouetteVertices, vertices.Count);
            for (var i = 0; i < vertices.Count; i++)
                _silhouetteVertices[i] = Vector2.Transform(vertices[i], gridToView);

            for (var start = 0; start < vertices.Count; start += batchSize)
            {
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList,
                    new Span<Vector2>(_silhouetteVertices, start, Math.Min(batchSize, vertices.Count - start)), color);
            }
        }
    }

    private Color GetTerrainColor(int typeId)
    {
        if (_terrainColors.TryGetValue(typeId, out var color))
            return color;

        var id = _tileDefinitions[typeId].ID;
        if (id.Contains("Water", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#578CA8");
        else if (id.Contains("Snow", StringComparison.OrdinalIgnoreCase) || id.Contains("Ice", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#D2DEDA");
        else if (id.Contains("Grass", StringComparison.OrdinalIgnoreCase) || id.Contains("Jungle", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#697F50");
        else if (id.Contains("Sand", StringComparison.OrdinalIgnoreCase) || id.Contains("Desert", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#C7B77D");
        else if (id.Contains("Dirt", StringComparison.OrdinalIgnoreCase) || id.Contains("Soil", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#957755");
        else if (id.Contains("Wood", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#BB9165");
        else if (id.Contains("Cave", StringComparison.OrdinalIgnoreCase) || id.Contains("Rock", StringComparison.OrdinalIgnoreCase) ||
                 id.Contains("Basalt", StringComparison.OrdinalIgnoreCase) || id.Contains("Chromite", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#646569");
        else
            color = Color.FromHex("#ADB0A6");

        _terrainColors.Add(typeId, color);
        return color;
    }
}
