using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Medieval.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class ColorSelectorControl : Control
{
    public Color SelectedColor;
    public List<Color> Colors = new();
    public Action<Color>? OnColorChanged;
    public Dictionary<Color, BaseButton> Buttons = new();
    private float _buttonWidth;

    public ColorSelectorControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate()
    {
        var group = new ButtonGroup();
        Buttons = new();

        Grid.DisposeAllChildren();

        foreach (var color in Colors)
        {
            var button = new TextureButton();
            // button.ClipText = true;
            // button.MinSize = new Vector2(65, 55);
            // // button.Label.Dispose();
            button.Scale = new Vector2(1.4f, 1.4f);
            button.TexturePath = "/Textures/Interface/Nano/rounded_button_bordered.svg.96dpi.png";
            button.Group = group;
            button.AddStyleClass(ContainerButton.StyleClassButton);
            button.AddStyleClass(StyleNano.ButtonSquare);
            button.HorizontalExpand = false;
            button.HorizontalAlignment = HAlignment.Stretch;
            button.ModulateSelfOverride = color == SelectedColor
                ? Color.LightGreen
                : new Color(0, 0, 0, 0);

            // button.Modulate = StyleNano.ButtonColorDefault;
            button.OnButtonDown += args =>
            {
                SelectedColor = color;
                OnColorChanged?.Invoke(color);
            };

            if (SelectedColor == color)
            {
                button.Pressed = true;
            }


            var texture = new TextureRect();
            texture.HorizontalExpand = true;
            texture.HorizontalAlignment = HAlignment.Center;
            texture.VerticalAlignment = VAlignment.Center;
            texture.VerticalExpand = true;
            texture.Margin = new Thickness(3);
            texture.TexturePath = "/Textures/Interface/Nano/rounded_button.svg.96dpi.png";
            texture.Modulate = color;
            texture.Stretch = TextureRect.StretchMode.Scale;
            button.AddChild(texture);

            Buttons.Add(color, button);

            Grid.AddChild(button);
        }
    }

    public void UpdateSelectedButton()
    {
        foreach (var (color, button) in Buttons)
        {
            button.ModulateSelfOverride = color == SelectedColor
                ? Color.LightGreen
                : new Color(0, 0, 0, 0);
        }
    }
}
