using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.CapturePoint;

[GenerateTypedNameReferences]
public sealed partial class CapturePointStartWindow : MedievalWindow
{
    public CapturePointStartWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
