using System.Numerics;
using Content.Shared.Imperial.Medieval.MagicRunes.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

//=========================================================================
// MagicScrollWindow.xaml.cs
//=========================================================================
// Purpose: Code-behind for magic scroll window with rune decryption UI
// Author: rhailrake
//=========================================================================

namespace Content.Client.Imperial.Medieval.MagicScroll;

[GenerateTypedNameReferences]
public sealed partial class MagicScrollWindow : DefaultWindow
{
    private MagicScrollBoundUserInterfaceState? _currentState;
    private readonly Dictionary<MagicRune, Button> _knownRuneButtons = new();
    private readonly Dictionary<MagicRune, Label> _encryptedRuneLabels = new();
    private MinesweeperWindow? _minesweeperWindow;
    private int _playerIntelligence = 10;
    private int _gridSize = 5;
    private int _totalMines = 2;

    public MagicScrollBoundUserInterface? Owner;

    public MagicScrollWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(MagicScrollBoundUserInterfaceState state)
    {
        _currentState = state;
        _playerIntelligence = state.PlayerIntelligence;
        _gridSize = state.GridSize;
        _totalMines = state.TotalMines;
        UpdatePowerDisplay();
        UpdateEncryptedRunes();
        UpdateKnownRunes();
    }

    private void UpdatePowerDisplay()
    {
        if (_currentState == null) return;

        PowerLabel.Text = $"Сила свитка: {_currentState.ScrollPower:F1}";

        var decodedCount = _currentState.DecodedRunes.Count;
        var totalCount = _currentState.EncryptedRunes.Count;

        if (decodedCount == totalCount)
        {
            StatusLabel.Text = "Статус: Полностью расшифрован";
            StatusLabel.Modulate = Color.Green;
        }
        else
        {
            StatusLabel.Text = $"Статус: Расшифровано {decodedCount}/{totalCount} рун";
            StatusLabel.Modulate = Color.White;
        }
    }

    private void UpdateEncryptedRunes()
    {
        if (_currentState == null) return;

        EncryptedRunesGrid.RemoveAllChildren();
        _encryptedRuneLabels.Clear();

        foreach (var rune in _currentState.EncryptedRunes)
        {
            var isDecoded = _currentState.DecodedRunes.Contains(rune);
            var label = new Label
            {
                Text = isDecoded ? MagicRuneData.GetSymbol(rune) : "?",
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(40, 40),
                MouseFilter = Control.MouseFilterMode.Stop
            };

            if (isDecoded)
            {
                label.Modulate = Color.LightGreen;
                label.ToolTip = MagicRuneData.GetMeaning(rune);
            }
            else
            {
                label.Modulate = Color.Gray;
                label.ToolTip = "Не расшифровано";
            }

            EncryptedRunesGrid.AddChild(label);
            _encryptedRuneLabels[rune] = label;
        }
    }

    private void UpdateKnownRunes()
    {
        if (_currentState == null) return;

        KnownRunesGrid.RemoveAllChildren();
        _knownRuneButtons.Clear();

        foreach (var rune in _currentState.KnownRunes)
        {
            var button = new Button
            {
                Text = MagicRuneData.GetSymbol(rune),
                MinSize = new Vector2(50, 50),
                ToolTip = MagicRuneData.GetMeaning(rune)
            };

            var canUse = CanUseRuneForDecryption(rune);

            if (canUse)
            {
                button.Modulate = Color.White;
                button.OnPressed += _ => StartMinesweeper(rune);
            }
            else
            {
                button.Modulate = Color.Gray;
                button.Disabled = true;
                button.ToolTip += " (уже использована или нет подходящих рун для расшифровки)";
            }

            KnownRunesGrid.AddChild(button);
            _knownRuneButtons[rune] = button;
        }
    }

    private bool CanUseRuneForDecryption(MagicRune knownRune)
    {
        if (_currentState == null) return false;

        return _currentState.EncryptedRunes.Contains(knownRune) &&
               !_currentState.DecodedRunes.Contains(knownRune);
    }

    private void StartMinesweeper(MagicRune rune)
    {
        if (_minesweeperWindow != null)
        {
            _minesweeperWindow.Close();
        }

        _minesweeperWindow = new MinesweeperWindow();
        _minesweeperWindow.GameCompleted += success => OnMinesweeperCompleted(rune, success);
        _minesweeperWindow.StartGame(rune, _playerIntelligence, _gridSize, _totalMines);
        _minesweeperWindow.OpenCentered();
    }

    private void OnMinesweeperCompleted(MagicRune rune, bool success)
    {
        if (success)
        {
            Owner?.SendMessage(new MagicScrollRuneUnlockedMessage(rune));
        }
        else
        {
            Owner?.SendMessage(new MagicScrollExplosionMessage());
        }

        _minesweeperWindow = null;
    }
}
