using System.Numerics;
using System.Runtime.InteropServices;
using Content.Shared.Imperial.Medieval.MagicRunes.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

//=========================================================================
// MinesweeperWindow.cs
//=========================================================================
// Purpose: Minesweeper minigame for rune decryption challenges
// Author: rhailrake, edited by Bladefire5
//=========================================================================

namespace Content.Client.Imperial.Medieval.MagicScroll;

[GenerateTypedNameReferences]
public sealed partial class MinesweeperWindow : DefaultWindow
{
    private readonly Random _random = new();

    private bool[,] _mineField = new bool[0, 0];
    private bool[,] _revealed = new bool[0, 0];
    private bool[,] _flagged = new bool[0, 0];

    private int _mineCount;
    private int _revealedCount;
    private bool _gameOver;
    private bool _gameStarted;

    private IGameTiming _gameTiming = default!;
    private TimeSpan? _turnStartTime;
    private TimeSpan? _turnEndTime;

    private const float GameEndDelay = 3.0f;

    private int _playerIntelligence = 10;
    private int _requiredIntelligence = 10;
    private bool _debugBypassMinigameRequirements;
    private int _gridSize = 5;
    private int _totalMines = 2;
    private int _moveTimeSeconds;
    private int _minimumMoveDelaySeconds;
    private int _tipsRemaining;
    private int _maxRestarts = -1;
    private int _restartsRemaining = -1;
    private bool _isUnstable;
    private bool _isRunePair;
    private bool _hintUsedThisTurn;
    private bool _safeRevealAvailable = true;
    private bool _misfireForgivenessAvailable = true;

    public event Action? GameStarted;
    public event Action? RestartUsed;
    public event Action<bool, bool>? GameCompleted;

    public MinesweeperWindow()
    {
        RobustXamlLoader.Load(this);
        _gameTiming = IoCManager.Resolve<IGameTiming>();

        StartButton.OnPressed += _ => StartMinigame();
        CloseButto.OnPressed += _ => Close();

        OnClose += () =>
        {
            /* Closing an active game is an intentional failure and explodes the scroll.
             Closing before the Start button was pressed is safe.*/
            if (_gameStarted && !_gameOver)
                GameCompleted?.Invoke(false, true);
        };

        HintButton.OnPressed += _ =>
        {
            if (!_gameStarted || _gameOver || _hintUsedThisTurn || _tipsRemaining <= 0)
                return;

            UseHint();
        };

        RestartButton.OnPressed += _ =>
        {
            if (!_gameStarted || _gameOver)
                return;

            if (_maxRestarts >= 0 && _restartsRemaining <= 0)
            return;

            if (_restartsRemaining > 0)
            {
                _restartsRemaining--;
                RestartUsed?.Invoke();
            }

            GameCompleted?.Invoke(false, false);

            _gameStarted = false;
            _gameOver = false;
            _turnStartTime = null;
            _turnEndTime = null;
            _misfireForgivenessAvailable = true;

            PrepareGame();

            StartButton.Disabled = false;
            HintButton.Disabled = true;
            RestartButton.Disabled = true;

            UpdateStatus();
        };
    }

    public void StartGame(
        MagicRune rune,
        int playerIntelligence,
        int requiredIntelligence,
        int gridSize,
        int totalMines,
        int moveTimeSeconds,
        int minimumMoveDelaySeconds,
        int tipsAvailable,
        int maxRestarts,
        bool isUnstable = false,
        bool debugBypassMinigameRequirements = false)
    {
        _isUnstable = isUnstable;
        _debugBypassMinigameRequirements = debugBypassMinigameRequirements;
        ConfigureGame(
            MagicRuneData.GetSymbol(rune),
            MagicRuneLocalization.GetMeaning(rune),
            playerIntelligence,
            requiredIntelligence,
            gridSize,
            totalMines,
            moveTimeSeconds,
            minimumMoveDelaySeconds,
            tipsAvailable,
            maxRestarts,
            isRunePair: false);
    }

    public void StartPairGame(
        MagicRunePair pair,
        int playerIntelligence,
        int requiredIntelligence,
        int gridSize,
        int totalMines,
        int moveTimeSeconds,
        int minimumMoveDelaySeconds,
        int tipsAvailable,
        int maxRestarts,
        bool isUnstable = false,
        bool debugBypassMinigameRequirements = false)
    {
        _isUnstable = isUnstable;
        _debugBypassMinigameRequirements = debugBypassMinigameRequirements;
        ConfigureGame(
            MagicRuneData.GetPairDisplay(pair),
            MagicRuneLocalization.GetPairMeaning(pair),
            playerIntelligence,
            requiredIntelligence,
            gridSize,
            totalMines,
            moveTimeSeconds,
            minimumMoveDelaySeconds,
            tipsAvailable,
            maxRestarts,
            isRunePair: true);
    }

    private void ConfigureGame(
        string runeDisplay,
        string runeMeaning,
        int playerIntelligence,
        int requiredIntelligence,
        int gridSize,
        int totalMines,
        int moveTimeSeconds,
        int minimumMoveDelaySeconds,
        int tipsAvailable,
        int maxRestarts,
        bool isRunePair)
    {
        _playerIntelligence = playerIntelligence;
        _requiredIntelligence = requiredIntelligence;
        _gridSize = Math.Max(1, gridSize);
        _totalMines = Math.Clamp(totalMines, 1, _gridSize * _gridSize - 1);
        _moveTimeSeconds = Math.Max(0, moveTimeSeconds);
        _minimumMoveDelaySeconds = Math.Max(0, minimumMoveDelaySeconds);
        _tipsRemaining = Math.Max(0, tipsAvailable);
        _maxRestarts = maxRestarts;
        _restartsRemaining = maxRestarts;

        _isRunePair = isRunePair;
        RuneLabel.Text = Loc.GetString(
            _isRunePair ? "magic-scroll-minesweeper-deciphering-pair" : "magic-scroll-minesweeper-deciphering-rune",
            ("display", runeDisplay), ("meaning", runeMeaning));

        _gameStarted = false;
        _gameOver = false;
        _turnStartTime = null;
        _turnEndTime = null;
        _misfireForgivenessAvailable = true;

        PrepareGame();
        StartButton.Disabled = false;
        HintButton.Disabled = true;
        RestartButton.Disabled = true;
        UpdateStatus();
    }

    private void StartMinigame()
    {
        if (_gameStarted || _gameOver)
            return;

        _gameStarted = true;
        GameStarted?.Invoke();

        _gameStarted = true;
        StartButton.Disabled = true;
        UpdateRestartButton();
        PrepareGame();
        StartTurn();
    }

    private void PrepareGame()
    {
        _mineField = new bool[_gridSize, _gridSize];
        _revealed = new bool[_gridSize, _gridSize];
        _flagged = new bool[_gridSize, _gridSize];
        _mineCount = _totalMines;
        _revealedCount = 0;
        _hintUsedThisTurn = false;
        _safeRevealAvailable = true;

        CreateMinefield();
        CreateGrid();
        UpdateHintButton();
        UpdateStatus();
    }

    private void CreateMinefield()
    {
        var positions = new List<(int x, int y)>();

        for (var x = 0; x < _gridSize; x++)
        {
            for (var y = 0; y < _gridSize; y++)
                positions.Add((x, y));
        }

        _random.Shuffle(CollectionsMarshal.AsSpan(positions));

        for (var i = 0; i < _mineCount; i++)
        {
            var (x, y) = positions[i];
            _mineField[x, y] = true;
        }
    }
    // makes first move always safe
    private void MakeRevealSafe(int x, int y)
    {
        if (!_mineField[x, y])
            return;

        var safePositions = new List<(int x, int y)>();

        for (var newX = 0; newX < _gridSize; newX++)
        {
            for (var newY = 0; newY < _gridSize; newY++)
            {
                if ((newX != x || newY != y) && !_mineField[newX, newY])
                    safePositions.Add((newX, newY));
            }
        }

        if (safePositions.Count == 0)
            return;

        var newPosition = safePositions[_random.Next(safePositions.Count)];

        _mineField[x, y] = false;
        _mineField[newPosition.x, newPosition.y] = true;
    }

    private void StartTurn()
    {
        if (!_gameStarted || _gameOver)
            return;

        _hintUsedThisTurn = false;
        var now = _gameTiming.CurTime;
        _turnStartTime = now;

        if (_moveTimeSeconds > 0)
            _turnEndTime = now + TimeSpan.FromSeconds(_moveTimeSeconds);
        else
            _turnEndTime = null;

        UpdateHintButton();
        UpdateStatus();
    }

    private bool IsMoveAllowed()
    {
        if (!_gameStarted || _gameOver)
            return false;

        if (_isUnstable &&
            _minimumMoveDelaySeconds > 0 &&
            _turnStartTime.HasValue &&
            _gameTiming.CurTime < _turnStartTime.Value +
            TimeSpan.FromSeconds(_minimumMoveDelaySeconds))
        {
            EndGame(false, true);
            return false;
        }

        return true;
    }

    private void FinishMove()
    {
        if (_gameOver)
            return;

        // A normal tile action ends the current turn and starts the next one.
        StartTurn();
    }

    private void UseHint()
    {
        if (!IsMoveAllowed())
            return;

        for (var i = 0; i < _gridSize; i++)
        {
            for (var j = 0; j < _gridSize; j++)
            {
                if (!_revealed[i, j] && !_mineField[i, j] && !_flagged[i, j])
                {
                    RevealCell(i, j);
                    _hintUsedThisTurn = true;
                    _tipsRemaining--;
                    UpdateHintButton();

                    if (!_gameOver)
                        StatusLabel.Text = Loc.GetString("magic-scroll-minesweeper-hint-used");

                    return;
                }
            }
        }

        _hintUsedThisTurn = true;
        _tipsRemaining = 0;
        UpdateHintButton();
        StatusLabel.Text = Loc.GetString("magic-scroll-minesweeper-no-safe-hint");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_gameOver)
            return;

        if (!_gameStarted || !_turnEndTime.HasValue)
            return;

        UpdateTimerDisplay();

        if (_gameTiming.CurTime >= _turnEndTime.Value)
        {
            _turnEndTime = null;
            EndGame(false, true);
        }
    }

    private void CreateGrid()
    {
        MinesweeperGrid.RemoveAllChildren();
        MinesweeperGrid.Columns = _gridSize;

        for (var x = 0; x < _gridSize; x++)
        {
            for (var y = 0; y < _gridSize; y++)
            {
                var button = new Button
                {
                    Text = "",
                    MinSize = new Vector2(40, 40)
                };

                button.EnableAllKeybinds = true;

                var cellX = x;
                var cellY = y;

                button.OnPressed += args =>
                {
                    if (!IsMoveAllowed())
                        return;

                    if (args.Event.Function == EngineKeyFunctions.UIClick)
                    {
                        if (HandleCellClick(cellX, cellY) && !_gameOver)
                            FinishMove();
                    }
                    else if (args.Event.Function == EngineKeyFunctions.UIRightClick)
                    {
                        if (ToggleFlag(cellX, cellY) && !_gameOver)
                            FinishMove();
                    }
                };

                MinesweeperGrid.AddChild(button);
            }
        }
    }

    private bool HandleCellClick(int x, int y)
    {
        var targetX = x;
        var targetY = y;

        if (!_debugBypassMinigameRequirements && _playerIntelligence < _requiredIntelligence)
        {
            var intelligenceDeficit = _requiredIntelligence - _playerIntelligence;
            var misfireChance = intelligenceDeficit * (10f / 3f);

            if (_random.NextDouble() * 100 < misfireChance)
            {
                if (_misfireForgivenessAvailable)
                {
                    _misfireForgivenessAvailable = false;

                    StatusLabel.Text = Loc.GetString("magic-scroll-minesweeper-misfire-forgiven");
                    StatusLabel.Modulate = Color.Yellow;
                }
                else
                {
                    var neighbors = GetNeighbors(x, y);

                    if (neighbors.Count > 0)
                    {
                        var randomNeighbor = neighbors[_random.Next(neighbors.Count)];
                        targetX = randomNeighbor.x;
                        targetY = randomNeighbor.y;

                        StatusLabel.Text =
                        Loc.GetString("magic-scroll-minesweeper-misfire");
                        StatusLabel.Modulate = Color.Orange;
                    }
                }
            }
        }

        if (_safeRevealAvailable)
        {
            _safeRevealAvailable = false;
            MakeRevealSafe(targetX, targetY);
        }

        if (_revealed[targetX, targetY] || _flagged[targetX, targetY])
            return false;

        RevealCell(targetX, targetY);
        return true;
    }

    private List<(int x, int y)> GetNeighbors(int x, int y)
    {
        var neighbors = new List<(int, int)>();

        for (var dx = -1; dx <= 1; dx++)
        {
            for (var dy = -1; dy <= 1; dy++)
            {
                if (dx == 0 && dy == 0)
                    continue;

                var nx = x + dx;
                var ny = y + dy;

                if (nx >= 0 && nx < _gridSize && ny >= 0 && ny < _gridSize)
                    neighbors.Add((nx, ny));
            }
        }

        return neighbors;
    }

    private void RevealCell(int x, int y)
    {
        if (_gameOver || _revealed[x, y] || _flagged[x, y])
            return;

        _revealed[x, y] = true;
        _revealedCount++;

        var button = GetButtonAt(x, y);
        if (button == null)
            return;

        if (_mineField[x, y])
        {
            button.Text = "💣";
            button.Modulate = Color.Red;
            EndGame(false, true);
            return;
        }

        var adjacentMines = CountAdjacentMines(x, y);

        if (adjacentMines > 0)
        {
            button.Text = adjacentMines.ToString();
            button.Modulate = GetNumberColor(adjacentMines);
        }
        else
        {
            button.Text = "";
            button.Modulate = Color.LightGreen;

            for (var dx = -1; dx <= 1; dx++)
            {
                for (var dy = -1; dy <= 1; dy++)
                {
                    var nx = x + dx;
                    var ny = y + dy;

                    if (nx >= 0 && nx < _gridSize &&
                        ny >= 0 && ny < _gridSize &&
                        !_revealed[nx, ny] &&
                        !_flagged[nx, ny])
                    {
                        RevealCell(nx, ny);
                    }
                }
            }
        }

        if (_revealedCount == _gridSize * _gridSize - _mineCount)
            EndGame(true, false);

        UpdateStatus();
    }

    private bool ToggleFlag(int x, int y)
    {
        if (_gameOver || _revealed[x, y])
            return false;

        _flagged[x, y] = !_flagged[x, y];

        var button = GetButtonAt(x, y);
        if (button == null)
            return false;

        if (_flagged[x, y])
        {
            button.Text = "!";
            button.Modulate = Color.Yellow;
        }
        else
        {
            button.Text = "";
            button.Modulate = Color.White;
        }

        UpdateStatus();
        return true;
    }

    private Button? GetButtonAt(int x, int y)
    {
        var index = x * _gridSize + y;

        if (index < 0 || index >= MinesweeperGrid.ChildCount)
            return null;

        return MinesweeperGrid.GetChild(index) as Button;
    }

    private int CountAdjacentMines(int x, int y)
    {
        var count = 0;

        for (var dx = -1; dx <= 1; dx++)
        {
            for (var dy = -1; dy <= 1; dy++)
            {
                if (dx == 0 && dy == 0)
                    continue;

                var nx = x + dx;
                var ny = y + dy;

                if (nx >= 0 && nx < _gridSize &&
                    ny >= 0 && ny < _gridSize &&
                    _mineField[nx, ny])
                {
                    count++;
                }
            }
        }

        return count;
    }

    private Color GetNumberColor(int number)
    {
        return number switch
        {
            1 => Color.Blue,
            2 => Color.Green,
            3 => Color.Red,
            4 => Color.Purple,
            5 => Color.Maroon,
            _ => Color.White
        };
    }

    private void EndGame(bool won, bool blow)
    {
        if (_gameOver)
            return;

        _gameOver = true;
        _turnStartTime = null;
        _turnEndTime = null;

        StartButton.Disabled = true;
        HintButton.Disabled = true;
        RestartButton.Disabled = true;

        if (won)
        {
            _revealedCount = _gridSize * _gridSize - _mineCount;
            StatusLabel.Text =
                Loc.GetString(_isRunePair ? "magic-scroll-minesweeper-victory-pair" : "magic-scroll-minesweeper-victory-rune");
            StatusLabel.Modulate = Color.Green;
        }
        else
        {
            StatusLabel.Text = Loc.GetString(
                blow ? "magic-scroll-minesweeper-defeat-explosion" : "magic-scroll-minesweeper-defeat");
            StatusLabel.Modulate = Color.Red;

            for (var i = 0; i < _gridSize; i++)
            {
                for (var j = 0; j < _gridSize; j++)
                {
                    if (!_mineField[i, j])
                        continue;

                    var button = GetButtonAt(i, j);
                    if (button != null && !_revealed[i, j])
                    {
                        button.Text = "💣";
                        button.Modulate = Color.DarkRed;
                    }
                }
            }
        }

        GameCompleted?.Invoke(won, blow);
        UpdateStatus();

        Timer.Spawn(
            TimeSpan.FromSeconds(GameEndDelay),
            () =>
            {
                if (IsOpen)
                    Close();
            });
    }

    private void UpdateTimerDisplay()
    {
        if (!_gameStarted || _gameOver || !_turnEndTime.HasValue)
        {
            TimerLabel.Text = Loc.GetString("magic-scroll-minesweeper-time-none");
            return;
        }

        var remaining = _turnEndTime.Value - _gameTiming.CurTime;
        var seconds = Math.Max(0, (int)Math.Ceiling(remaining.TotalSeconds));
        TimerLabel.Text = Loc.GetString("magic-scroll-minesweeper-time", ("seconds", seconds));
    }

    private void UpdateHintButton()
    {
        HintButton.Text = Loc.GetString("magic-scroll-minesweeper-hint-count", ("count", _tipsRemaining));
        HintButton.Disabled =
            !_gameStarted ||
            _gameOver ||
            _hintUsedThisTurn ||
            _tipsRemaining <= 0;
    }

    private void UpdateRestartButton()
    {
        if (_maxRestarts == 0)
        {
            RestartButton.Disabled = true;
            RestartButton.Text = Loc.GetString("magic-scroll-minesweeper-restart");
            return;
        }

        if (_maxRestarts > 0)
        {
            RestartButton.Disabled = _restartsRemaining <= 0;
            RestartButton.Text = Loc.GetString("magic-scroll-minesweeper-restart-count", ("count", _restartsRemaining));
            return;
        }

        // -1 means unlimited.
        RestartButton.Disabled = false;
        RestartButton.Text = Loc.GetString("magic-scroll-minesweeper-restart");

    }

    private void UpdateStatus()
    {
        UpdateTimerDisplay();

        if (!_gameStarted)
        {
            StatusLabel.Text = Loc.GetString("magic-scroll-minesweeper-start-prompt");
            StatusLabel.Modulate = Color.White;
            MinesLabel.Text = Loc.GetString("magic-scroll-minesweeper-mines", ("count", _mineCount));
            OpenedLabel.Text = Loc.GetString("magic-scroll-minesweeper-revealed",
                ("revealed", 0), ("total", _gridSize * _gridSize - _mineCount));
            return;
        }

        if (_gameOver)
        {
            var totalSafeCells = _gridSize * _gridSize - _mineCount;
            MinesLabel.Text = Loc.GetString("magic-scroll-minesweeper-mines", ("count", 0));
            OpenedLabel.Text = Loc.GetString("magic-scroll-minesweeper-revealed",
                ("revealed", totalSafeCells), ("total", totalSafeCells));
            return;
        }

        var flaggedCount = 0;

        for (var i = 0; i < _gridSize; i++)
        {
            for (var j = 0; j < _gridSize; j++)
            {
                if (_flagged[i, j])
                    flaggedCount++;
            }
        }

        MinesLabel.Text = Loc.GetString("magic-scroll-minesweeper-mines", ("count", _mineCount - flaggedCount));
        OpenedLabel.Text =
            Loc.GetString("magic-scroll-minesweeper-revealed",
                ("revealed", _revealedCount), ("total", _gridSize * _gridSize - _mineCount));

        if (!_debugBypassMinigameRequirements && _playerIntelligence < _requiredIntelligence)
        {
            var intelligenceDeficit = 11 - _playerIntelligence;
            var misfireChance = intelligenceDeficit * 5;
            StatusLabel.Text =
                Loc.GetString("magic-scroll-minesweeper-objective-misfire", ("chance", misfireChance));
            StatusLabel.Modulate = Color.Yellow;
        }
        else if (_isUnstable && _minimumMoveDelaySeconds > 0)
        {
            StatusLabel.Text =
                Loc.GetString("magic-scroll-minesweeper-objective-unstable-delay", ("seconds", _minimumMoveDelaySeconds));
            StatusLabel.Modulate = Color.Orange;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("magic-scroll-minesweeper-objective");
            StatusLabel.Modulate = Color.White;
        }
    }
}
