using System.Linq;
using Content.Shared.Imperial.Medieval.Factions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Factions.UI.Elements;

/// <summary>
/// Панель для отображения членов фракции по их должности
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionJobPanel : BoxContainer
{
    public Action<FactionMemberGroup, string>? ObjectiveSet;

    public string Job;

    public FactionJobPanel(string job)
    {
        RobustXamlLoader.Load(this);

        Job = job;
        if (job != string.Empty)
            JobLabel.Text = job;
    }

    public void Update()
    {
        BorderedPanel.BorderRadius /= Box.Children.Where(x => x is FactionMenuEntry e).Count();
    }
}
