using System.Linq;
using Content.Shared.Imperial.Medieval.Factions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI.Elements;

[GenerateTypedNameReferences]
public sealed partial class FactionGoalEntry : BoxContainer
{
    public FactionGoalEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void Refresh(FactionGoalData data)
    {
        var proto = IoCManager.Resolve<IPrototypeManager>().Index(data.GoalProto);
        Name.SetMessage(proto.Name);
        Desc.SetMessage(data.Desctiption);
        Icon.Texture = proto.Icon.Frame0();
        Progress.Value = data.Progress;
        ProgressText.SetMessage($"{data.Progress * 100f:0.00}%", defaultColor: Color.White);
    }
}
