using System.Linq;
using Content.Client.Imperial.Medieval.Factions;
using Content.Client.Imperial.Roadmap.UI;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Factions.UI.Elements;

/// <summary>
/// Панель для отображения членов фракции по группам.
/// Позволяет редактировать их задачу
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionGroupPanel : BorderedPanelContainer
{
    public Action<FactionMemberGroup, string>? ObjectiveSet;

    public FactionMemberGroup Group;

    public FactionGroupPanel(FactionMemberGroup group, FactionMenuAccess access, FactionMemberGroup self, string groupObjective = "")
    {
        RobustXamlLoader.Load(this);

        GroupNamePanel.PanelOverride = new StyleBoxFlat(MedievalFactionsSystem.GroupColors[group]);
        Group = group;
        if (group != FactionMemberGroup.None)
            GroupNameText.Text = Loc.GetString($"group-{group}");

        Objective.Text = groupObjective;
        SetObjectiveButtonText.Text = groupObjective != string.Empty ? "Изменить" : "Назначить задачу";
        ObjectivePanel.Visible = groupObjective != string.Empty && group != FactionMemberGroup.None;

        SetObjectiveButton.Visible = access switch
        {
            FactionMenuAccess.None => false,
            FactionMenuAccess.Group => self == group && group != FactionMemberGroup.None,
            FactionMenuAccess.Full => group != FactionMemberGroup.None,
            _ => false
        };

        ObjectiveEdit.OnTextEntered += args => ObjectiveSet?.Invoke(group, args.Text);

        SetObjectiveButton.OnPressed += args =>
        {
            SetObjectiveButton.Visible = false;
            ObjectiveEditPanel.Visible = true;
            if (groupObjective.Length > 32)
                ObjectiveEdit.SetText(groupObjective.Substring(0, 32), true);
            else
                ObjectiveEditTip.Visible = true;
        };

        ObjectiveEdit.OnTextChanged += args =>
        {
            ObjectiveEditTip.Visible = args.Text == string.Empty;
            if (args.Text.Length > 32)
                ObjectiveEdit.SetText(args.Text.Substring(0, 32));
        };

    }

    public void Update()
    {
        AliveCounter.SetMessage($"Живые: {Box.Children.Where(x => x is FactionMenuEntry e && e.Alive).Count()} / {Box.Children.Where(x => x is FactionMenuEntry).Count()}", defaultColor: Color.White);
        BorderRadius /= Box.Children.Where(x => x is FactionMenuEntry e).Count();
    }
}
