using System.Linq;
using Content.Client.Imperial.Medieval.Factions;
using Content.Client.Lobby;
using Content.Shared.Chat;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Factions.UI.Elements;

/// <summary>
/// Панель, содержащая информацию о разыскиваемом члене группы
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WantedDeskEntry : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly LobbyUIController _lobby;

    public WantedDeskEntry(WantedData data)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _lobby = UserInterfaceManager.GetUIController<LobbyUIController>();

        var ent = _lobby.LoadProfileEntity(data.Profile, _proto.Index<JobPrototype>(data.Job), true);
        Character.SetEntity(ent);

        Name.SetMessage(data.Profile.Name);
        Faction.SetMessage($"Состоял в: {_proto.Index(data.Faction).Name.ToLower()}");
        Job.SetMessage($"Должность: {_proto.Index<JobPrototype>(data.Job).LocalizedName.ToLower()}");
        Species.SetMessage($"Раса: {Loc.GetString($"species-{data.Profile.Species}")}");
        Sex.SetMessage($"Пол: {Loc.GetString($"humanoid-profile-editor-sex-{data.Profile.Sex.ToString().ToLower()}-text").ToLower()}");
        Age.SetMessage($"Возраст: {data.Profile.Age} лет");

        if (data.FlavorText != string.Empty)
        {
            var label = new RichTextLabel();
            label.SetMessage(data.FlavorText);
            Info.AddChild(label);
        }

        if (data.Details != string.Empty)
        {
            var label = new RichTextLabel();
            label.SetMessage(data.Details);
            Details.AddChild(label);
        }

        RewardHeadName.SetMessage(data.Performer);
        var icon = _proto.Index(data.Faction).Icon;
        if (icon != null)
        {
            FactionSprite.Texture = icon.Frame0();
            FactionSprite.Visible = true;
        }
    }


}
