using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Imperial.Medieval.UniversalLock.Lock;

[GenerateTypedNameReferences]
public sealed partial class UniversalLockWindow : DefaultWindow
{
    // Сигнатура изменена для передачи названия (string) и кода (int[])
    public Action<string, int[], int>? OnSetCode;
    private List<LineEdit> _inputs = new();
    private List<Slider> _sliders = new();
    private int _maxValue;

    public UniversalLockWindow()
    {
        RobustXamlLoader.Load(this);

        SetCodeButton.OnPressed += _ => SubmitCode();
    }

    public void UpdateState(int maxValue, int length)
    {
        InfoLabel.Text = $"{Loc.GetString("UniversalLock-ui-setup-allowed-value-from")} 0 - {maxValue}";
        _maxValue = maxValue;

        if (_inputs.Count != length)
        {
            InputsContainer.DisposeAllChildren();
            _inputs.Clear();
            _sliders.Clear();

            for (int i = 0; i < length; i++)
            {
                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 10
                };

                var slider = new Slider
                {
                    MinValue = 0,
                    MaxValue = maxValue,
                    Rounded = true,
                    HorizontalExpand = true,
                    Value = 0
                };

                var input = new LineEdit
                {
                    MinWidth = 45,
                    MaxWidth = 45,
                    Text = "0",
                    HorizontalAlignment = HAlignment.Center
                };

                slider.OnValueChanged += val =>
                {
                    input.Text = (val.Value).ToString();
                };

                input.OnTextChanged += args =>
                {
                    if (int.TryParse(args.Text, out var val))
                    {
                        if (val < 0) val = 0;
                        if (val > _maxValue) val = _maxValue;

                        slider.Value = val;
                    }
                };

                _sliders.Add(slider);
                _inputs.Add(input);

                rowContainer.AddChild(slider);
                rowContainer.AddChild(input);
                InputsContainer.AddChild(rowContainer);
            }
        }
    }

    private void SubmitCode()
    {
        var lockName = LockNameInput.Text;
        var code = new int[_inputs.Count];

        for (int i = 0; i < _inputs.Count; i++)
        {
            if (int.TryParse(_inputs[i].Text, out var val))
            {
                if (val < 0 || val > _maxValue)
                {
                    return;
                }
                code[i] = val;
            }
            else
            {
                code[i] = 0;
            }
        }

        // Блокируем поле названия вместе с остальными элементами UI
        LockNameInput.Editable = false;

        foreach (var slider in _sliders)
        {
            slider.Disabled = true;
        }
        foreach (var input in _inputs)
        {
            input.Editable = false;
        }
        SetCodeButton.Disabled = true;

        OnSetCode?.Invoke(lockName, code, _maxValue);
    }
}
