# Beginner

- type: entity
  id: MedievalActionObeliskBeginner
  name: medieval-store-spells-earth-obelisk-beginner-name
  description: medieval-store-spells-earth-obelisk-beginner-desc
  components:
  - type: CastTraining
    trainingResults:
      - !type:AddMagicEssence
        essenceAddProbability: 0.0007
        bonusAddProbability: 1
        addedEssences:
          MagicMedievalEarth: 1
        bonusEssences:
          MagicMedievalEarth: 1
  - type: ManaDrainSpell
    manaDrain: 40
    canUseWithoutMana: true
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 12
  - type: SpellCastEffect
    effectProto: ObeliskSpellCastEffectBeginner
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 50
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Imperial/Medieval/mob_spawn_effect.ogg
    icon:
      sprite: Imperial/Medieval/Magic/Earth/Obelisk/icons.rsi
      state: beginner
  - type: TargetAction
    checkCanAccess: false
    range: 8
  - type: WorldTargetAction
    event: !type:MedievalSpawnSpellEvent
      spawnedEntityPrototype: MedievalObeliskBeginner
      spawnType: SpawnOnMousePosition
      spellCastDoAfter:
        delay: 1
        breakOnDropItem: false
        breakOnWeightlessMove: false
        breakOnMove: false
        needHand: true
        speedModifier: 0.3
      speechPoints:
        0:
          speech: medieval-spell-speach-obelisk
          color: "#838275"
          hideChat: true
  - type: ActionUpgrade
    effectedLevels:
      2: MedievalActionObeliskMiddle
      3: MedievalActionObeliskSenior

# Middle

- type: entity
  id: MedievalActionObeliskMiddle
  name: medieval-store-spells-earth-obelisk-middle-name
  description: medieval-store-spells-earth-obelisk-middle-desc
  parent: MedievalActionObeliskBeginner
  components:
  - type: ManaDrainSpell
    manaDrain: 50
    canUseWithoutMana: true
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 12
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 55
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Imperial/Medieval/mob_spawn_effect.ogg
    icon:
      sprite: Imperial/Medieval/Magic/Earth/Obelisk/icons.rsi
      state: middle
  - type: TargetAction
    checkCanAccess: false
    range: 8
  - type: WorldTargetAction
    event: !type:MedievalSpawnSpellEvent
      spawnedEntityPrototype: MedievalObeliskMiddle
      spawnType: SpawnOnMousePosition
      spellCastDoAfter:
        delay: 1
        breakOnDropItem: false
        breakOnWeightlessMove: false
        breakOnMove: false
        needHand: true
        speedModifier: 0.3
      speechPoints:
        0:
          speech: medieval-spell-speach-obelisk
          color: "#838275"
          hideChat: true

# Senior

- type: entity
  id: MedievalActionObeliskSenior
  name: medieval-store-spells-earth-obelisk-senior-name
  description: medieval-store-spells-earth-obelisk-senior-desc
  parent: MedievalActionObeliskBeginner
  components:
  - type: ManaDrainSpell
    manaDrain: 60
    canUseWithoutMana: true
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 12
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 80
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Imperial/Medieval/mob_spawn_effect.ogg
    icon:
      sprite: Imperial/Medieval/Magic/Earth/Obelisk/icons.rsi
      state: senior
  - type: TargetAction
    checkCanAccess: false
    range: 10
  - type: WorldTargetAction
    event: !type:MedievalSpawnSpellEvent
      spawnedEntityPrototype: MedievalObeliskSenior
      spawnType: SpawnOnMousePosition
      spellCastDoAfter:
        delay: 1
        breakOnDropItem: false
        breakOnWeightlessMove: false
        breakOnMove: false
        needHand: true
        speedModifier: 0.3
      speechPoints:
        0:
          speech: medieval-spell-speach-obelisk
          color: "#838275"
          hideChat: true
