using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenuEntry : Control
{
    public Action<NetEntity, string>? ObjectiveSet;
    public Action<NetEntity, string>? GroupSet;
    public Action<NetEntity>? RemoveButtonPressed;

    public FactionMenuEntry(NetEntity ent, FactionMemberData data)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NameLabel.SetMessage(data.Name);
        JobLabel.SetMessage(data.Job);
        ObjectiveEdit.Text = data.Objective;
        GroupEdit.Text = data.Group;

        ObjectiveEdit.OnTextEntered += args => ObjectiveSet?.Invoke(ent, args.Text);
        GroupEdit.OnTextEntered += args => GroupSet?.Invoke(ent, args.Text);
        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke(ent);
    }
}
