using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionRemoveConfirmationMenu : FancyWindow
{
    public Action<NetEntity>? OnConfirm;
    public FactionRemoveConfirmationMenu(NetEntity ent)
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke(ent);
        CancelButton.OnPressed += _ => Close();
    }
}
