using System.Linq;
using Content.Client.Friends;
using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenuEntry : Control
{
    public Action<NetEntity, string>? ObjectiveSet;
    public Action<NetEntity, FactionMemberGroup>? GroupSet;
    public Action<NetEntity>? RemoveButtonPressed;

    public FactionMenuEntry(NetEntity ent, FactionMemberData data, string objective)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (data.Group == FactionMemberGroup.None)
        {
            for (var i = 0; i < FriendsSystem.FactionGroups.Count; i++)
            {
                var item = FriendsSystem.FactionGroups.ElementAt(i).Value;
                GroupSelector.AddItem(item.Item2, item.Item1, i);
            }
            GroupSelector.Select(0);
            GroupSelector.OnItemSelected += args => GroupSet?.Invoke(ent, FriendsSystem.FactionGroups.ElementAt(args.Id).Key);
        }
        else
        {
            GroupRemoveButton.Visible = true;
            GroupSelector.Visible = false;
            Objective.Text = objective;
            Objective.Visible = objective != string.Empty;
            GroupRemoveButtonText.Text = FriendsSystem.FactionGroups[data.Group].Item2;
            GroupRemoveButton.ModulateSelfOverride = FriendsSystem.FactionGroups[data.Group].Item1;
            GroupRemoveButton.OnPressed += args => GroupSet?.Invoke(ent, FactionMemberGroup.None);
        }

        RemoveButton.OnPressed += _ => RemoveButtonPressed?.Invoke(ent);
    }
}

public sealed class ColoredOptionButton : OptionButton
{
    private Color? _cachedColor;
    public void AddItem(string label, Color color, int? id = null)
    {
        _cachedColor = color;
        AddItem(label, id);
    }

    public override void ButtonOverride(Button button)
    {
        base.ButtonOverride(button);

        button.ModulateSelfOverride = _cachedColor;
        _cachedColor = null;
    }
}
