using System.Text.RegularExpressions;
using Content.Client.Friends;
using Content.Shared.Friends;
using Content.Shared.Friends.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly FriendsSystem _friends;

    public Action<FactionMemberGroup, string>? ObjectiveSet;
    public Action<NetEntity, FactionMemberGroup>? GroupSet;
    public Action<NetEntity>? RemoveButtonPressed;

    public ProtoId<MedievalFactionPrototype> Faction = "";

    public FactionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _friends = _entMan.System<FriendsSystem>();
    }

    public void Populate(ProtoId<MedievalFactionPrototype> proto, Dictionary<NetEntity, FactionMemberData> data)
    {
        Members.DisposeAllChildren();
        Faction = proto;

        foreach (var item in data)
        {
            var group = item.Value.Group;
            _friends.TryGetFactionGroupObjective(proto, item.Value.Group, out var objective);
            var entry = new FactionMenuEntry(item.Key, item.Value, objective ?? "");
            entry.GroupSet += (ent, group) => GroupSet?.Invoke(ent, group);
            EnsureContainer(group).AddChild(entry);
        }
    }

    private BoxContainer EnsureContainer(FactionMemberGroup group)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionGroupPanel panel)
                continue;
            if (panel.Group == group)
                return panel.Box;
        }
        var newPanel = new FactionGroupPanel(group);
        newPanel.ObjectiveSet += (group, obj) => ObjectiveSet?.Invoke(group, obj);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }
}
