using System.Text.RegularExpressions;
using Content.Client.Friends;
using Content.Client.Imperial.Medieval.Friends.UI.Elements;
using Content.Shared.Friends;
using Content.Shared.Friends.Components;
using Content.Shared.Friends.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly FriendsSystem _friends;

    public Action<FactionMemberGroup, string>? ObjectiveSet;
    public Action<int, FactionMemberGroup>? GroupSet;
    public Action<int>? FirePressed;
    public Action<int>? HeadhuntPressed;
    public Action<int, bool>? SetLeaderPressed;

    public ProtoId<MedievalFactionPrototype> Faction = "";

    public bool JobModeBool
    {
        get => _jobMode;
        set
        {
            if (_jobMode == value)
                return;
            _jobMode = value;
            Populate(Faction, _self, _localData, _access, _selfGroup);
        }
    }
    private bool _jobMode = true;
    private Dictionary<int, FactionMemberData> _localData = new();
    private FactionMenuAccess _access = FactionMenuAccess.None;
    private FactionMemberGroup _selfGroup = FactionMemberGroup.None;
    private int _self = 0;

    private int? _fireSelected;

    public FactionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _friends = _entMan.System<FriendsSystem>();
        JobMode.OnToggled += args =>
        {
            JobModeBool = true;
            JobMode.Pressed = true;
            GroupMode.Pressed = false;
        };
        GroupMode.OnToggled += args =>
        {
            JobModeBool = false;
            JobMode.Pressed = false;
            GroupMode.Pressed = true;
        };
        Cancel.OnPressed += args =>
        {
            Confirmation.Visible = false;
            Main.Visible = true;
            _fireSelected = null;
        };
        Fire.OnPressed += args =>
        {
            if (!_fireSelected.HasValue)
                return;
            FirePressed?.Invoke(_fireSelected.Value);
            Main.Visible = true;
            Confirmation.Visible = false;
            _fireSelected = null;
        };
        Headhunt.OnPressed += args =>
        {
            if (!_fireSelected.HasValue)
                return;
            HeadhuntPressed?.Invoke(_fireSelected.Value);
            Main.Visible = true;
            Confirmation.Visible = false;
            _fireSelected = null;
        };
    }

    public void Populate(ProtoId<MedievalFactionPrototype> proto, int self, Dictionary<int, FactionMemberData> data, FactionMenuAccess access, FactionMemberGroup selfGroup)
    {
        Members.DisposeAllChildren();
        Faction = proto;
        _localData = data;
        _access = access;
        _self = self;
        _selfGroup = selfGroup;
        Headhunt.Visible = IoCManager.Resolve<IPrototypeManager>().Index(proto).AllowHeadhunt;

        foreach (var item in data)
        {
            var group = item.Value.Group;
            _friends.TryGetFactionGroupObjective(proto, item.Value.Group, out var objective);
            var entry = new FactionMenuEntry(item.Key, self, item.Value, access, objective ?? "");
            entry.GroupSet += (ent, group) => GroupSet?.Invoke(ent, group);
            entry.RemoveButtonPressed += args =>
            {
                _fireSelected = args;
                Main.Visible = false;
                Confirmation.Visible = true;
            };
            entry.SetLeaderPressed += (id, isLeader) => SetLeaderPressed?.Invoke(id, isLeader);

            var container = _jobMode ? EnsureJobContainer(item.Value.Job) : EnsureGroupContainer(group, objective ?? "", access, selfGroup);
            container.AddChild(entry);
        }
    }

    private BoxContainer EnsureJobContainer(string job)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionJobPanel panel)
                continue;
            if (panel.Job == job)
                return panel.Box;
        }
        var newPanel = new FactionJobPanel(job);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }

    private BoxContainer EnsureGroupContainer(FactionMemberGroup group, string objective, FactionMenuAccess access, FactionMemberGroup selfGroup)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionGroupPanel panel)
                continue;
            if (panel.Group == group)
                return panel.Box;
        }
        var newPanel = new FactionGroupPanel(group, access, selfGroup, objective);
        newPanel.ObjectiveSet += (group, obj) => ObjectiveSet?.Invoke(group, obj);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }
}
