using Content.Shared.Friends;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenu : DefaultWindow
{
    public Action<NetEntity, string>? ObjectiveSet;
    public Action<NetEntity, string>? GroupSet;
    public Action<NetEntity>? RemoveButtonPressed;

    public FactionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        HeaderClass = "windowHeaderWood";
        TitleClass = "windowTitleAlert";
        GetChild(0).SetOnlyStyleClass("windowPanelWood");
    }

    public void Populate(Dictionary<NetEntity, FactionMemberData> data)
    {
        Members.DisposeAllChildren();

        foreach (var item in data)
        {
            var entry = new FactionMenuEntry(item.Key, item.Value);
            entry.ObjectiveSet += (ent, obj) => ObjectiveSet?.Invoke(ent, obj);
            entry.GroupSet += (ent, group) => GroupSet?.Invoke(ent, group);
            entry.RemoveButtonPressed += args => RemoveButtonPressed?.Invoke(args);
            Members.AddChild(entry);
        }
    }
}
