using System.Linq;
using System.Text.RegularExpressions;
using Content.Client.Friends;
using Content.Client.Imperial.Medieval.Friends.UI.Elements;
using Content.Shared.Friends;
using Content.Shared.Friends.Components;
using Content.Shared.Friends.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Friends.UI;


[GenerateTypedNameReferences]
public sealed partial class WantedDeskMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    public EntityUid Owner;

    public WantedDeskMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(WantedDeskBoundUserInterfaceState state)
    {
        Wanted.RemoveAllChildren();

        var comp = _entMan.GetComponentOrNull<WantedDeskComponent>(Owner);

        foreach (var item in state.Wanted)
        {
            if (comp != null && comp.Blacklisted.Contains(item.Value.Faction))
                continue;

            var entry = new WantedDeskEntry(item.Value);
            Wanted.AddChild(entry);
        }
    }
}
