using System.Numerics;
using Content.Client.Shuttles.UI;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.CartographerTable;

[GenerateTypedNameReferences]
public sealed partial class MedievalCartographerTableNavControl : BaseShuttleControl
{
    private const float SilhouetteAlpha = 0.28f;

    [Dependency] private readonly IMapManager _mapManager = default!;

    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;
    private List<Entity<MapGridComponent>> _grids = new();
    private Vector2[] _silhouetteVertices = Array.Empty<Vector2>();

    private EntityCoordinates? _coordinates;
    private Angle? _rotation;
    private bool _rotateWithEntity = true;

    public MedievalCartographerTableNavControl() : base(64f, 256f, 256f)
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
    }

    public void UpdateState(NavInterfaceState state)
    {
        _coordinates = EntManager.GetCoordinates(state.Coordinates);
        _rotation = state.Angle;

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
            ActualRadarRange = WorldMaxRange;

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);
        _rotateWithEntity = state.RotateWithEntity;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);

        if (_coordinates == null || _rotation == null)
            return;

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform) ||
            xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var mapPos = _transform.ToMapCoordinates(_coordinates.Value);
        var posMatrix = Matrix3Helpers.CreateTransform(_coordinates.Value.Position, _rotation.Value);
        var ourEntRot = _rotateWithEntity ? _transform.GetWorldRotation(xform) : _rotation.Value;
        var ourEntMatrix = Matrix3Helpers.CreateTransform(_transform.GetWorldPosition(xform), ourEntRot);
        var shuttleToWorld = Matrix3x2.Multiply(posMatrix, ourEntMatrix);
        Matrix3x2.Invert(shuttleToWorld, out var worldToShuttle);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) *
                            Matrix3x2.CreateTranslation(MidPointVector);

        var ourGridId = xform.GridUid;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) &&
            fixturesQuery.HasComponent(ourGridId.Value))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGridSilhouette(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
        }

        var rot = ourEntRot + _rotation.Value;
        var viewBounds = new Box2Rotated(
            new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position),
            rot,
            mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(
            xform.MapID,
            new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector),
            ref _grids,
            approx: true,
            includeMap: false);

        foreach (var grid in _grids)
        {
            var gridUid = grid.Owner;
            if (gridUid == ourGridId ||
                !fixturesQuery.HasComponent(gridUid) ||
                !bodyQuery.TryGetComponent(gridUid, out var gridBody))
            {
                continue;
            }

            EntManager.TryGetComponent<IFFComponent>(gridUid, out var iff);

            if (!_shuttles.CanDraw(gridUid, gridBody, iff))
                continue;

            var gridToWorld = _transform.GetWorldMatrix(gridUid);
            var gridAABB = gridToWorld.TransformBox(grid.Comp.LocalAABB);

            if (!gridAABB.Intersects(viewAABB))
                continue;

            var gridToView = gridToWorld * worldToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(grid, self: false, iff);

            DrawGridSilhouette(handle, gridToView, grid, color);
        }
    }

    private void DrawGridSilhouette(
        DrawingHandleScreen handle,
        Matrix3x2 gridToView,
        Entity<MapGridComponent> grid,
        Color color)
    {
        var gridData = GridData.GetOrNew(grid.Owner);

        if (gridData.LastBuild < grid.Comp.LastTileModifiedTick)
        {
            gridData.Vertices.Clear();

            var tileSize = grid.Comp.TileSize;
            var tiles = Maps.GetAllTilesEnumerator(grid.Owner, grid.Comp);

            while (tiles.MoveNext(out var tileRef))
            {
                var index = tileRef.Value.GridIndices;

                var bl = Maps.TileToVector(grid, index);
                var br = bl + new Vector2(tileSize, 0f);
                var tr = bl + new Vector2(tileSize, tileSize);
                var tl = bl + new Vector2(0f, tileSize);

                gridData.Vertices.Add(bl);
                gridData.Vertices.Add(br);
                gridData.Vertices.Add(tl);

                gridData.Vertices.Add(br);
                gridData.Vertices.Add(tl);
                gridData.Vertices.Add(tr);
            }

            gridData.EdgeIndex = gridData.Vertices.Count;
            gridData.LastBuild = grid.Comp.LastTileModifiedTick;
        }

        var totalData = gridData.Vertices.Count;
        Extensions.EnsureLength(ref _silhouetteVertices, totalData);

        for (var i = 0; i < totalData; i++)
        {
            _silhouetteVertices[i] = Vector2.Transform(gridData.Vertices[i], gridToView);
        }

        const int batchSize = 3 * 4096;

        for (var start = 0; start < totalData; start += batchSize)
        {
            var count = Math.Min(batchSize, totalData - start);
            handle.DrawPrimitives(
                DrawPrimitiveTopology.TriangleList,
                new Span<Vector2>(_silhouetteVertices, start, count),
                color.WithAlpha(SilhouetteAlpha));
        }
    }
}
