using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.CartographerTable;

[GenerateTypedNameReferences]
public sealed partial class MedievalCartographerTableWindow : FancyWindow
{
    public MedievalCartographerTableWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavInterfaceState state)
    {
        RadarScreen.UpdateState(state);
    }
}
