using Content.Client.Imperial.Medieval.CapturePoint.UI.MedievalWindow;
using Content.Shared.Imperial.Medieval.CapturePoint.Components;
using Content.Shared.Imperial.Medieval.FactionFlag.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Globalization;

namespace Content.Client.Imperial.Medieval.FactionFlag.UI;

[GenerateTypedNameReferences]
public sealed partial class MedievalFactionFlagWindow : MedievalWindow
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    private readonly Dictionary<NetEntity, MedievalFactionFlagPointControl> _points = [];

    private NetEntity? _selectedPoint;

    public MedievalFactionFlagWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetPoints(List<MedievalFactionFlagPointData> points)
    {
        foreach (var point in points)
        {
            if (_points.TryGetValue(point.Entity, out var control))
            {
                control.Update(point);
                continue;
            }

            AddPoint(point);
        }

        if (_selectedPoint == null)
            return;

        if (_points.TryGetValue(_selectedPoint.Value, out var selectedControl))
            UpdateInfoBar(selectedControl);
    }

    public void AddPoint(MedievalFactionFlagPointData data)
    {
        var control = new MedievalFactionFlagPointControl(data);

        control.OnButtonDown += _ => SelectPoint(control);

        _points[data.Entity] = control;

        Map.AddMapControl(control, data.Position);
    }

    private void SelectPoint(MedievalFactionFlagPointControl control)
    {
        if (_selectedPoint != null && _points.TryGetValue(_selectedPoint.Value, out var prev))
            prev.IsSelected = false;

        _selectedPoint = control.Entity;
        control.IsSelected = true;

        UpdateInfoBar(control);
    }

    private void UpdateInfoBar(MedievalFactionFlagPointControl control)
    {
        var data = control.Data;

        PointNameLabel.Text = data.Name;

        if (data.Owner != null)
        {
            var ownerFaction = _protoMan.Index(data.Owner.Value);
            var ownerName = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(ownerFaction.Name);

            OwnerLabel.SetMessage(ownerName, defaultColor: ownerFaction.Color);
        }
        else
            OwnerLabel.SetMessage(Loc.GetString("medieval-faction-flag-state-neutral"), defaultColor: Color.LightGray);

        var stateText = data.State switch
        {
            CapturePointState.Capturing => Loc.GetString("medieval-faction-flag-state-capturing"),
            CapturePointState.Cooldown => Loc.GetString("medieval-faction-flag-state-cooldown"),
            CapturePointState.Idle when data.Owner == null => Loc.GetString("medieval-faction-flag-state-neutral"),
            CapturePointState.Idle => Loc.GetString("medieval-faction-flag-state-controlled"),
            _ => string.Empty,
        };

        StateLabel.SetMessage(stateText);

        if (data.State == CapturePointState.Capturing && data.CapturingFaction != null)
        {
            var attackerFaction = _protoMan.Index(data.CapturingFaction.Value);
            var attackerName = CultureInfo.InvariantCulture.TextInfo.ToTitleCase(attackerFaction.Name);

            AttackerLabelValue.SetMessage(attackerName, defaultColor: attackerFaction.Color);
            AttackerContainer.Visible = true;
        }
        else
            AttackerContainer.Visible = false;
    }
}
