# Beginner

- type: entity
  id: MedievalActionBlinkBeginner
  name: medieval-store-spells-light-blink-beginner-name
  description: medieval-store-spells-light-blink-beginner-desc
  components:
  - type: CastTraining
    trainingResults:
      - !type:AddMagicEssence
        essenceAddProbability: 0.0007
        bonusAddProbability: 1
        addedEssences:
          MagicMedievalLight: 1
        bonusEssences:
          MagicMedievalLight: 1
  - type: ManaDrainSpell
    manaDrain: 45
    canUseWithoutMana: true
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 15
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 60
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Weapons/Guns/Gunshots/Magic/staff_healing.ogg
    icon:
      sprite: Imperial/Medieval/Magic/Light/Blink/icons.rsi
      state: beginner
  - type: TargetAction
    checkCanAccess: false
    range: 6
  - type: WorldTargetAction
    event: !type:MedievalTeleportSpellEvent
      spellCastDoAfter:
        delay: 1
        breakOnDropItem: false
        breakOnWeightlessMove: false
        breakOnMove: false
        needHand: true
      speechPoints:
        0:
          speech: medieval-spell-speach-blink
          color: "#7D7D7D"
          hideChat: true
  - type: ShowSpawnedEntity
    sprites:
      - drawedSprite:
          sprite: Imperial/Medieval/Magic/Light/Blink/icons.rsi
          state: beginner
        inRangeColor: "#000062"
        outOfRangeColor: "#4A5076"
        alwaysRender: true
        range: 6
    rotationPerClick: 0
  - type: MedievalSpellTeleportEffect
    fadeDistortion:
      - type: PhaseSpaceDistortion
        isMove: false
        needSpriteVisible: false
        distortions:
          - relativePosition: 0,0
            fadePosition: 1,0
            distortionPathTime: 1
          - relativePosition: 0,0
            fadePosition: -1,0
            distortionPathTime: 1
          - relativePosition: 0,0
            fadePosition: 0,1
            distortionPathTime: 1
          - relativePosition: 0,0
            fadePosition: 0,-1
            distortionPathTime: 1
    appearanceDistortion:
      - type: PhaseSpaceDistortion
        isMove: true
        needSpriteVisible: false
        distortions:
          - relativePosition: 1,0
            fadePosition: 1,0
            distortionPathTime: 1
          - relativePosition: -1,0
            fadePosition: -1,0
            distortionPathTime: 1
          - relativePosition: 0,1
            fadePosition: 0,1
            distortionPathTime: 1
          - relativePosition: 0,-1
            fadePosition: 0,-1
            distortionPathTime: 1
  - type: ActionUpgrade
    effectedLevels:
      2: MedievalActionBlinkMiddle

# Middle

- type: entity
  id: MedievalActionBlinkMiddle
  parent: MedievalActionBlinkBeginner
  name: medieval-store-spells-light-blink-middle-name
  description: medieval-store-spells-light-blink-middle-desc
  components:
  - type: ManaDrainSpell
    manaDrain: 70
    canUseWithoutMana: true
    manaLowMessage: medieval-spell-speach-not-enough-mana-fire-spell
    damageOnUseWithoutMana:
      groups:
        Burn: 15
  - type: SpellCastEffect
    effectProto: BlinkSpellCastEffectBeginner
  - type: MedievalTargetSpell
  - type: Action
    useDelay: 60
    itemIconStyle: BigAction
    sound: !type:SoundPathSpecifier
      path: /Audio/Weapons/Guns/Gunshots/Magic/staff_healing.ogg
    icon:
      sprite: Imperial/Medieval/Magic/Light/Blink/icons.rsi
      state: beginner
  - type: TargetAction
    checkCanAccess: false
    range: 60
  - type: WorldTargetAction
    event: !type:MedievalTeleportSpellEvent
      spellCastDoAfter:
        delay: 1
        breakOnDropItem: false
        breakOnWeightlessMove: false
        breakOnMove: false
        needHand: true
      speechPoints:
        0:
          speech: medieval-spell-speach-blink
          color: "#7D7D7D"
          hideChat: true
  - type: ShowSpawnedEntity
    sprites:
      - drawedSprite:
          sprite: Imperial/Medieval/Magic/Light/Blink/icons.rsi
          state: beginner
        inRangeColor: "#000062"
        outOfRangeColor: "#4A5076"
        alwaysRender: true
        range: 10
    rotationPerClick: 0
