using Content.Client.Imperial.Roadmap.UI;
using Content.Shared.Imperial.Medieval.Language;
using Content.Shared.Imperial.Medieval.Skills;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Skills.UI;

[GenerateTypedNameReferences]
public sealed partial class MiniSkillEntry : Control
{
    public int Level
    {
        get => _level;
        set
        {
            UpdateVisualizer(Math.Clamp(value, 1, 20));
        }
    }

    private int _level = 1;


    public Action<int>? LevelSet;

    public MiniSkillEntry(string name, int level)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = name;
        LevelLabel.Text = Loc.GetString("imperial-hm-ui-lvl", ("amount", $"{level}"));
        Level = level;

        SetButton.OnPressed += _ =>
        {
            LevelInput.Visible = true;
            LevelLabel.Visible = false;
            LevelInput.Text = level.ToString();
            LevelInput.GrabKeyboardFocus();
        };

        LevelInput.OnTextEntered += args =>
        {
            if (int.TryParse(args.Text, out var level))
                LevelSet?.Invoke(level);
        };
    }

    public void UpdateVisualizer(int level)
    {
        LevelLabel.Text = $"УР: {level}";
        _level = level;
        LevelLabel.Visible = true;
        LevelInput.Clear();
        LevelInput.Visible = false;
    }
}
