using Content.Client.Imperial.Roadmap.UI;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Guidebook;
using Content.Shared.Imperial.Medieval.Language;
using Content.Shared.Imperial.Medieval.Skills;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Skills.UI;

[GenerateTypedNameReferences]
public sealed partial class SkillEntry : Control
{
    public string? Label
    {
        get => Name.Text;
        set => Name.Text = value;
    }

    public int Level
    {
        get => _level;
        set
        {
            UpdateVisualizer(Math.Clamp(value, 1, 20));
        }
    }

    private int _level = 1;

    private Color _color;

    public Action<int>? LevelSet;
    public Action? Decreased;

    public SkillEntry(string id, string name, int level, SpriteSpecifier icon, Color color, IPrototypeManager proto)
    {
        RobustXamlLoader.Load(this);

        Name.Text = name;
        LevelLabel.Text = $"УР: {level}";
        _color = color;
        Level = level;
        Icon.Texture = icon.Frame0();
        Info.OnPressed += args =>
        {
            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();

            var page = proto.HasIndex<GuideEntryPrototype>(id) ? id : null;

            if (proto.TryIndex<GuideEntryPrototype>("Skills", out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>() { { "Skills", guideRoot } };

                guidebookController.OpenGuidebook(dict, includeChildren: true, selected: page);
            }

        };


        IncreaseButton.OnPressed += _ => LevelSet?.Invoke(Level + 1);
        DecreaseButton.OnPressed += _ => LevelSet?.Invoke(Level - 1);
    }

    public void UpdateVisualizer(int level)
    {
        VisualizerContainer.RemoveAllChildren();
        _level = level;
        LevelLabel.Text = $"УР: {level}";

        IncreaseButton.Disabled = level >= 20;
        DecreaseButton.Disabled = level <= 1;

        for (var i = 0; i < 20; i++)
        {
            var diff = 20 - level;

            var panel = new BorderedPanelContainer()
            {
                PanelOverride = new StyleBoxFlat(Color.White),
                BackgroundPanelColor = i >= diff ? _color : Color.Gray,
                BorderRadius = 35f,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new(2, 4),
            };
            VisualizerContainer.AddChild(panel);
        }
    }
}
