using Content.Shared.Imperial.Medieval.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementWidget : BoxContainer
{
    public float Timer = 0f;
    public readonly float DisplayTime = 5.0f;
    private readonly float _animTime = 0.4f;

    private const int TargetMargin = 0;
    private const int StartOffset = -100;

    public AchievementWidget(
        AchievementPrototype proto,
        IResourceCache cache,
        SpriteSystem spriteSystem,
        IPrototypeManager protoManager,
        float globalPercent = 100f)
    {
        RobustXamlLoader.Load(this);

        Modulate = Color.White.WithAlpha(0f);

        var fontPath = new ResPath("/Fonts/NotoSans/NotoSans-Regular.ttf");
        var fontRes = cache.GetResource<FontResource>(fontPath);
        AchievementNameLabel.FontOverride = new VectorFont(fontRes, 14);

        AchievementIcon.Texture = spriteSystem.Frame0(proto.Icon);
        AchievementNameLabel.Text = proto.Name ?? "Achievement";

        var descMessage = new FormattedMessage();
        descMessage.PushColor(Color.FromHex("#c2b4a3"));
        descMessage.AddText(proto.Description ?? string.Empty);
        descMessage.Pop();
        DescriptionLabel.SetMessage(descMessage);

        var rarity = AchievementRarityHelper.Resolve(proto, globalPercent, protoManager);
        ApplyRarity(rarity);
    }

    private void ApplyRarity(AchievementRarityPrototype rarity)
    {
        var accentColor = Color.FromHex(rarity.AccentColor);

        var style = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1e1611"),
            BorderColor     = accentColor,
            BorderThickness = new Thickness(3, 0, 0, 0),
        };
        style.SetContentMarginOverride(StyleBox.Margin.Left, 12);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 16);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 8);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 8);
        MainPanel.PanelOverride = style;
    }

    public void UpdateAnimation(float deltaSeconds, float uiScale)
    {
        Timer += deltaSeconds;
        var scaledStart  = StartOffset * uiScale;
        var scaledTarget = TargetMargin * uiScale;

        if (Timer < _animTime)
        {
            var t = Timer / _animTime;
            var easedT = 1f - MathF.Pow(1f - t, 3f);
            Margin = new Thickness(0, 0, 0, scaledStart + (scaledTarget - scaledStart) * easedT);
            Modulate = Color.White.WithAlpha(t);
        }
        else if (Timer > DisplayTime - _animTime)
        {
            var t = (DisplayTime - Timer) / _animTime;
            var easedT = MathF.Pow(t, 3f);
            Margin = new Thickness(0, 0, 0, scaledStart + (scaledTarget - scaledStart) * easedT);
            Modulate = Color.White.WithAlpha(t);
        }
        else
        {
            Margin = new Thickness(0, 0, 0, scaledTarget);
            Modulate = Color.White.WithAlpha(1f);
        }
    }
}
