using System.Linq;
using Content.Server.Administration.Logs;
using Content.Server.DoAfter;
using Content.Server.Hands.Systems;
using Content.Server.Popups;
using Content.Server.Stack;
using Content.Server.Imperial.Medieval.RandomSteal;
using Content.Shared.Database;
using Content.Shared.DoAfter;
using Content.Shared.IdentityManagement;
using Content.Shared.Imperial.Medieval.Additions;
using Content.Shared.Imperial.Medieval.Skills;
using Content.Shared.Imperial.RandomSteal.Components;
using Content.Shared.Imperial.RandomSteal.Events;
using Content.Shared.Interaction;
using Content.Shared.Inventory;
using Content.Shared.Item;
using Content.Shared.Stacks;
using Content.Shared.Storage;
using Content.Shared.Verbs;
using Robust.Server.Audio;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Shared.Imperial.RandomSteal.Systems;

public sealed partial class RandomStealSystem : EntitySystem
{
    [Dependency] private readonly InventorySystem _inventorySystem = default!;
    [Dependency] private readonly PopupSystem _popupSystem = default!;
    [Dependency] private readonly IAdminLogManager _adminLogger = default!;
    [Dependency] private readonly DoAfterSystem _doAfterSystem = default!;
    [Dependency] private readonly HandsSystem _hands = default!;
    [Dependency] private readonly AudioSystem _audio = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly StackSystem _stackSystem = default!;
    [Dependency] private readonly AntiStealAfkSystem _afk = default!;
    [Dependency] private readonly SharedInteractionSystem _interaction = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public override void Initialize()
    {
        SubscribeLocalEvent<RandomStealComponent, GetVerbsEvent<AlternativeVerb>>(OnGetAlternativeVerbs);
        SubscribeLocalEvent<RandomStealComponent, StealDoAfterArgs>(OnDoAfterSteal);
        // SkillProgressionComponent already has an autogenerated unpause handler for its scalar timers.
        SubscribeLocalEvent<SkillsComponent, EntityUnpausedEvent>(OnSkillUnpaused);
    }

    private void OnSkillUnpaused(EntityUid uid, SkillsComponent skills, ref EntityUnpausedEvent args)
    {
        if (!TryComp<SkillProgressionComponent>(uid, out var state))
            return;
        foreach (var victim in state.HiddenTheftUntil.Keys.ToArray())
            state.HiddenTheftUntil[victim] += args.PausedTime;
    }

    private List<EntityUid> Candidates(EntityUid target, RandomStealComponent rules)
    {
        var result = new List<EntityUid>();
        foreach (var slot in rules.Slots)
        {
            if (!_inventorySystem.TryGetSlotEntity(target, slot, out var item))
                continue;
            if (TryComp<StorageComponent>(item, out var storage))
            {
                result.AddRange(storage.Container.ContainedEntities.Where(IsAllowed));
                continue;
            }
            if (IsAllowed(item.Value))
                result.Add(item.Value);
        }
        return result.Distinct().ToList();

        bool IsAllowed(EntityUid uid) =>
            !EntityManager.IsQueuedForDeletion(uid) && TryComp<ItemComponent>(uid, out var item) && rules.Sizes.Contains(item.Size);
    }

    private bool CanSelect(EntityUid uid) => TryComp<SkillsComponent>(uid, out var skills)
        && SkillScaling.Level(skills, SharedSkillsSystem.AgilityId) >= SkillScaling.Expert;

    private void OnGetAlternativeVerbs(EntityUid uid, RandomStealComponent comp, GetVerbsEvent<AlternativeVerb> args)
    {
        if (!args.CanAccess || !args.CanInteract || args.User == uid || !HasComp<RandomStealComponent>(args.User))
            return;
        var targets = Candidates(uid, comp);
        if (targets.Count == 0)
            return;
        if (TryComp<SkillsComponent>(args.User, out var skills) && SkillScaling.Level(skills, SharedSkillsSystem.AgilityId) >= SkillScaling.Expert)
        {
            foreach (var item in targets)
            {
                var selected = item;
                args.Verbs.Add(new AlternativeVerb
                {
                    Text = Loc.GetString("skills-steal-selected", ("item", Name(item))),
                    Act = () => TrySteal(args.User, uid, selected)
                });
            }
        }
        else
        {
            args.Verbs.Add(new AlternativeVerb
            {
                Text = Loc.GetString("stealActionSpellward"),
                Act = () => TrySteal(args.User, uid, null)
            });
        }
    }

    private void TrySteal(EntityUid user, EntityUid target, EntityUid? selected)
    {
        if (user == target || selected != null && !CanSelect(user)
            || !_interaction.InRangeUnobstructed(user, target) || !_afk.TryStrip(user, target)
            || !TryComp<RandomStealComponent>(target, out var rules)
            || !TryComp<RandomStealComponent>(user, out var thief))
            return;
        var candidates = Candidates(target, rules);
        if (candidates.Count == 0 || selected != null && !candidates.Contains(selected.Value))
            return;
        var item = selected ?? _random.Pick(candidates);
        var items = new List<EntityUid> { item };
        var extra = new TryGetAdditionalStealTargetEvent();
        RaiseLocalEvent(user, ref extra);
        candidates.Remove(item);
        if (extra.Success && candidates.Count > 0)
            items.Add(_random.Pick(candidates));
        var args = new DoAfterArgs(EntityManager, user, thief.TimeNeed,
            new StealDoAfterArgs(items) { Selected = selected != null }, user, target: target)
        {
            BreakOnMove = true,
            BreakOnDamage = true,
            NeedHand = true,
            Hidden = true,
            DistanceThreshold = 1.5f,
            BlockDuplicate = true
        };
        _doAfterSystem.TryStartDoAfter(args);
    }

    private void OnDoAfterSteal(EntityUid uid, RandomStealComponent comp, StealDoAfterArgs args)
    {
        if (args.Cancelled || args.Handled || args.Target is not { } target || args.Selected && !CanSelect(uid)
            || !_afk.TryStrip(uid, target) || !_interaction.InRangeUnobstructed(uid, target)
            || !TryComp<RandomStealComponent>(target, out var rules))
            return;
        args.Handled = true;
        var candidates = Candidates(target, rules);
        if (args.Entities.Count is < 1 or > 2 || !candidates.Contains(args.Entities[0]))
            return;

        var intelligence = TryComp<SkillsComponent>(target, out var victim)
            ? SkillScaling.Level(victim, SharedSkillsSystem.IntelligenceId) : SkillScaling.Baseline;
        var baseChance = (float) comp.Chance;
        if (TryComp<StealChanceIncreaserComponent>(uid, out var trait))
            baseChance += trait.Bonus;
        if (TryComp<StealRaceChanceIncreaserComponent>(uid, out var race))
            baseChance += race.Bonus;
        var modifiers = new GetStealChanceModifiersEvent(1f);
        RaiseLocalEvent(uid, ref modifiers);
        var success = SkillScaling.StealSuccess(baseChance / 100f, modifiers.Modifier, intelligence);
        if (!_random.Prob(success))
        {
            var hidden = false;
            if (TryComp<SkillsComponent>(uid, out var skills) && SkillScaling.Level(skills, SharedSkillsSystem.AgilityId) >= SkillScaling.Legendary)
            {
                var state = EnsureComp<SkillProgressionComponent>(uid);
                if (!state.HiddenTheftUntil.TryGetValue(target, out var until) || _timing.CurTime >= until)
                {
                    hidden = true;
                    state.HiddenTheftUntil[target] = _timing.CurTime + TimeSpan.FromSeconds(
                        _prototypes.Index<SkillPrototype>(SharedSkillsSystem.AgilityId).Modifiers["HiddenTheftCooldown"]);
                }
            }
            _popupSystem.PopupEntity(Loc.GetString("stealFailedSpellwardUser"), target, uid);
            if (!hidden)
            {
                _popupSystem.PopupEntity(Loc.GetString("stealFailedSpellward", ("entity1", Identity.Name(uid, EntityManager))), uid, target);
                _audio.PlayPvs(comp.FailedSound, uid, comp.FailedSound.Params);
            }
            _adminLogger.Add(LogType.Action, LogImpact.Medium, $"{ToPrettyString(uid):user} failed to steal from {ToPrettyString(target):target}; undetected: {hidden}.");
            return;
        }

        if (!TransferTheft(uid, target, args.Entities[0]))
            return;
        var extra = new TryGetAdditionalStealTargetEvent();
        RaiseLocalEvent(uid, ref extra);
        if (extra.Success && args.Entities.Count == 2 && Candidates(target, rules).Contains(args.Entities[1])
            && _hands.CanPickupAnyHand(uid, args.Entities[1]))
            TransferTheft(uid, target, args.Entities[1], force: false);
        _popupSystem.PopupEntity(Loc.GetString("stealSuccessSpellward", ("entity1", Identity.Name(target, EntityManager))), uid, uid);
    }

    private bool TransferTheft(EntityUid uid, EntityUid target, EntityUid original, bool force = true)
    {
        var stolen = original;
        if (TryComp<StackComponent>(stolen, out var stack) && stack.Count > 1)
        {
            var maximum = Math.Max(1, (int) Math.Floor(stack.Count * 0.7f));
            var amount = _random.Next(1, maximum + 1);
            if (_stackSystem.Split(stolen, amount, Transform(uid).Coordinates) is not { } split)
                return false;
            stolen = split;
        }
        var pickedUp = force ? _hands.TryForcePickupAnyHand(uid, stolen) : _hands.TryPickupAnyHand(uid, stolen);
        if (!pickedUp)
        {
            // Splitting must not steal a stack onto the floor when pickup itself fails.
            if (stolen != original)
                _stackSystem.TryAdd(stolen, original);
            return false;
        }
        _adminLogger.Add(LogType.Action, LogImpact.Medium, $"{ToPrettyString(uid):user} stole {ToPrettyString(stolen):item} from {ToPrettyString(target):target}.");
        return true;
    }
}
