using System.Linq;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;


[GenerateTypedNameReferences]
public sealed partial class AcceptFactionRelationsMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action? SendPressed;

    public AcceptFactionRelationsMenu(ProtoId<MedievalFactionPrototype> proto, ProtoId<FactionRelationsPrototype> relation)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MainLabel.SetMessage(Loc.GetString("medieval-hm-relations-leaderchng", ("name", $"{_proto.Index(proto).Name}"), ("name2", $"{_proto.Index(relation).Name}")));

        SendButton.OnPressed += args =>
        {
            SendPressed?.Invoke();
            Close();
        };
        DiscardButton.OnPressed += args => Close();
    }
}
