using Content.Client.Imperial.Medieval.Factions;
using Content.Client.Imperial.Medieval.Factions.UI.Elements;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Components;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;


[GenerateTypedNameReferences]
public sealed partial class FactionMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly MedievalFactionsSystem _friends;

    public Action<FactionMemberGroup, string>? ObjectiveSet;
    public Action<int, FactionMemberGroup>? GroupSet;
    public Action<int>? FirePressed;
    public Action<int, string>? HeadhuntPressed;
    public Action<int, bool>? SetLeaderPressed;

    public Action<ProtoId<MedievalFactionPrototype>>? WarPressed;

    public MenuMode Mode = MenuMode.Job;
    public FactionMenuData Data = new();

    private int? _fireSelected;

    public FactionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _friends = _entMan.System<MedievalFactionsSystem>();

        ButtonGroup modeGroup = new(false);

        JobMode.Group = modeGroup;
        GroupMode.Group = modeGroup;
        RelationsMode.Group = modeGroup;
        GoalsMode.Group = modeGroup;

        JobMode.OnToggled += args =>
        {
            Mode = MenuMode.Job;
            Populate(Data);
        };
        GroupMode.OnToggled += args =>
        {
            Mode = MenuMode.Group;
            Populate(Data);
        };
        RelationsMode.OnToggled += args =>
        {
            Mode = MenuMode.Relations;
            PopulateRelations(Data);
        };
        GoalsMode.OnToggled += args =>
        {
            Mode = MenuMode.Goals;
            PopulateGoals(Data.Goals ?? new());
        };

        Cancel.OnPressed += args =>
        {
            Confirmation.Visible = false;
            Main.Visible = true;
            _fireSelected = null;
        };
        Fire.OnPressed += args =>
        {
            if (!_fireSelected.HasValue)
                return;
            FirePressed?.Invoke(_fireSelected.Value);
            Main.Visible = true;
            Confirmation.Visible = false;
            _fireSelected = null;
        };
        Headhunt.OnPressed += args =>
        {
            if (!_fireSelected.HasValue)
                return;
            Headhunt.Visible = false;
            HeadhuntConfirmation.Visible = true;
        };
        HeadhuntConfirm.OnPressed += args =>
        {
            if (!_fireSelected.HasValue)
                return;
            HeadhuntPressed?.Invoke(_fireSelected.Value, HeadhuntDetails.Text);
            HeadhuntDetails.Clear();
            Headhunt.Visible = true;
            HeadhuntConfirmation.Visible = false;
            Main.Visible = true;
            Confirmation.Visible = false;
            _fireSelected = null;
        };
    }

    public void Populate(FactionMenuData data)
    {
        Members.RemoveAllChildren();
        Data = data;
        Headhunt.Visible = IoCManager.Resolve<IPrototypeManager>().Index(Data.Faction).AllowHeadhunt && !HeadhuntConfirmation.Visible;

        foreach (var item in Data.Members)
        {
            var group = item.Value.Group;
            _friends.TryGetFactionGroupObjective(Data.Faction, item.Value.Group, out var objective);
            var entry = new FactionMenuEntry(item.Key, Data.Self, item.Value, Data.Access, objective ?? "");
            entry.GroupSet += (ent, group) => GroupSet?.Invoke(ent, group);
            entry.RemoveButtonPressed += args =>
            {
                if (item.Value.Dead)
                {
                    FirePressed?.Invoke(args);
                    return;
                }

                _fireSelected = args;
                ConfirmationLabel.SetMessage(Loc.GetString("medieval-hm-relations-firefire", ("name", $"{item.Value.JobPrefix}"), ("name2", $"{item.Value.Name}")));
                Main.Visible = false;
                Confirmation.Visible = true;
                Headhunt.Visible = IoCManager.Resolve<IPrototypeManager>().Index(Data.Faction).AllowHeadhunt;
            };
            entry.SetLeaderPressed += (id, isLeader) => SetLeaderPressed?.Invoke(id, isLeader);

            var container = Mode switch
            {
                MenuMode.Job => EnsureJobContainer(item.Value.Job),
                MenuMode.Group => EnsureGroupContainer(group, objective ?? "", Data.Access, Data.SelfGroup),
                _ => throw new ArgumentOutOfRangeException(),
            };
            container.AddChild(entry);
        }

        foreach (var item in Members.Children)
        {
            if (item is FactionJobPanel job)
                job.Update();
            if (item is FactionGroupPanel group)
                group.Update();
        }
    }

    private BoxContainer EnsureJobContainer(string job)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionJobPanel panel)
                continue;
            if (panel.Job == job)
                return panel.Box;
        }
        var newPanel = new FactionJobPanel(job);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }

    private BoxContainer EnsureGroupContainer(FactionMemberGroup group, string objective, FactionMenuAccess access, FactionMemberGroup selfGroup)
    {
        foreach (var item in Members.Children)
        {
            if (item is not FactionGroupPanel panel)
                continue;
            if (panel.Group == group)
                return panel.Box;
        }
        var newPanel = new FactionGroupPanel(group, access, selfGroup, objective);
        newPanel.ObjectiveSet += (group, obj) => ObjectiveSet?.Invoke(group, obj);
        Members.AddChild(newPanel);
        return newPanel.Box;
    }

    public void PopulateRelations(FactionMenuData data)
    {
        Members.RemoveAllChildren();
        Data = data;

        if (Data.Relations.Count == 0)
        {
            Members.AddChild(new Label { Text = Loc.GetString("faction-menu-no-relations") });
            return;
        }

        var panel = new FactionRelationsPanel(Data)
        {
            Margin = new(6)
        };

        panel.WarPressed += args => WarPressed?.Invoke(args);
        Members.AddChild(panel);
    }

    public void PopulateGoals(List<FactionGoalData> list)
    {
        Members.RemoveAllChildren();
        foreach (var item in list)
        {
            var entry = new FactionGoalEntry();
            Members.AddChild(entry);
            entry.Refresh(item);
        }
    }

    public enum MenuMode
    {
        Job,
        Group,
        Relations,
        Goals
    }
}
