using System.Linq;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;


[GenerateTypedNameReferences]
public sealed partial class SetFactionRelationsMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<ProtoId<MedievalFactionPrototype>, ProtoId<MedievalFactionPrototype>, ProtoId<FactionRelationsPrototype>>? SendPressed;

    public ProtoId<MedievalFactionPrototype> TargetFaction;
    public ProtoId<MedievalFactionPrototype> UserFaction;
    public ProtoId<FactionRelationsPrototype> Relation = "Neutral";

    private bool _paper;

    public SetFactionRelationsMenu(ProtoId<MedievalFactionPrototype> userFaction, ProtoId<MedievalFactionPrototype>? targetFaction, bool paper = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UserFaction = userFaction;
        _paper = paper;

        PopulateFactions(userFaction, targetFaction);
        PopulateRelations();
        UpdateMessage();

        SendButton.OnPressed += args =>
        {
            SendPressed?.Invoke(UserFaction, TargetFaction, Relation);
            Close();
        };
        DiscardButton.OnPressed += args => Close();
    }

    private void UpdateMessage()
    {
        var relation = _proto.Index(Relation);
        MainLabel.SetMessage(Loc.GetString("medieval-hm-relations-leaderchng", ("name", $"{_proto.Index(TargetFaction).Name}"), ("name2", $"{relation.Name}")), defaultColor: relation.Color);

        PaperWarning.Visible = _paper;
    }

    private void PopulateFactions(ProtoId<MedievalFactionPrototype> userFaction, ProtoId<MedievalFactionPrototype>? targetFaction)
    {
        if (targetFaction != null)
        {
            TargetFaction = targetFaction.Value;
            UserFaction = userFaction;
            FactionSelectButton.Visible = false;
            return;
        }

        var factions = _proto.EnumeratePrototypes<MedievalFactionPrototype>().Where(x => x.ID != userFaction && !x.BlockedRelations.Contains(userFaction))
            .ToList();
        factions.OrderBy(x => x.Name);
        for (var i = 0; i < factions.Count(); i++)
        {
            FactionSelectButton.AddItem(factions[i].Name, i);
        }

        TargetFaction = factions.ElementAt(0).ID;
        FactionSelectButton.SelectId(0);

        FactionSelectButton.OnItemSelected += args =>
        {
            FactionSelectButton.SelectId(args.Id);
            TargetFaction = factions.ElementAt(args.Id);
            UpdateMessage();
        };
    }

    private void PopulateRelations()
    {
        var relations = _proto.EnumeratePrototypes<FactionRelationsPrototype>().Where(x => IsAllowed(x.ID))
            .ToList();
        relations.OrderBy(x => x.Name);
        for (var i = 0; i < relations.Count(); i++)
        {
            RelationSelectButton.AddItem(relations.ElementAt(i).Name, i);
        }

        RelationSelectButton.SelectId(0);
        Relation = relations.ElementAt(0).ID;

        RelationSelectButton.OnItemSelected += args =>
        {
            RelationSelectButton.SelectId(args.Id);
            Relation = relations.ElementAt(args.Id).ID;
            UpdateMessage();
        };
    }

    private bool IsAllowed(ProtoId<FactionRelationsPrototype> relation)
    {
        if (_proto.Index(UserFaction).BlockedRelations.Contains(TargetFaction))
            return false;

        return true;
    }
}
