using System.Linq;
using Content.Shared.Imperial.Medieval.Factions;
using Content.Shared.Imperial.Medieval.Factions.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Factions.UI;


[GenerateTypedNameReferences]
public sealed partial class SetFactionRelationsMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<ProtoId<MedievalFactionPrototype>, ProtoId<MedievalFactionPrototype>, ProtoId<FactionRelationsPrototype>>? SendPressed;

    public SetFactionRelationsMenu(ProtoId<MedievalFactionPrototype> userFaction, ProtoId<MedievalFactionPrototype> targetFaction)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var relations = _proto.EnumeratePrototypes<FactionRelationsPrototype>();
        relations.OrderBy(x => x.Name);
        for (var i = 0; i < relations.Count(); i++)
        {
            RelationSelectButton.AddItem(relations.ElementAt(i).Name, i);
        }

        RelationSelectButton.OnItemSelected += args =>
        {
            RelationSelectButton.SelectId(args.Id);
            var relation = relations.ElementAt(args.Id);
            MainLabel.SetMessage($"Вы уверены, что хотите изменить отношения с фракцией {_proto.Index(targetFaction).Name} на {relation.Name}?", defaultColor: relation.Color);
        };
        RelationSelectButton.SelectId(0);
        MainLabel.SetMessage($"Вы уверены, что хотите изменить отношения с фракцией {_proto.Index(targetFaction).Name} на {relations.ElementAt(0).Name}?", defaultColor: relations.ElementAt(0).Color);

        SendButton.OnPressed += args =>
        {
            SendPressed?.Invoke(userFaction, targetFaction, relations.ElementAt(RelationSelectButton.SelectedId));
            Close();
        };
        DiscardButton.OnPressed += args => Close();
    }
}
