- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateCaptain
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle

- type: antag
  id: Pirate
  name: roles-antag-pirate-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h

- type: antag
  id: CaptainPirate
  name: roles-antag-captain-pirate-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000