using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Imperial.Medieval.Exam;
using Content.Client.Imperial.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Content.Shared.Imperial.Medieval.Exam.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A generic locking selector.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RequirementsSelector : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _userInterface = default!;

    private readonly RadioOptions<int> _options;
    private readonly StripeBack _lockStripe;

    private readonly Label _requirementsLabel;
    private readonly TextButton _requirementsExamTypeLabel;

    private List<ProtoId<GuideEntryPrototype>>? _guides;

    public event Action<int>? OnSelected;
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    public int Selected => _options.SelectedId;

    private ExamUIController Exam => _userInterface.GetUIController<ExamUIController>();

    private ProtoId<ExamPrototype> _examPrototype;

    public RequirementsSelector()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _options = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleBase.ButtonOpenRight,
            ButtonStyle = StyleBase.ButtonOpenBoth,
            LastButtonStyle = StyleBase.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        //Override default radio option button width
        _options.GenerateItem = GenerateButton;

        _options.OnItemSelected += args =>
        {
            _options.Select(args.Id);
            OnSelected?.Invoke(args.Id);
        };

        _requirementsLabel = new Label
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = {StyleBase.StyleClassLabelSubText},
        };

        _requirementsExamTypeLabel = new TextButton
        {
            Text = "",
            Visible = false,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            TextColorOverride = Color.White,
            StyleClasses = {StyleBase.StyleClassLabelSubText},
        };

        _requirementsExamTypeLabel.OnPressed += _ => Exam.OpenWindow(_examPrototype);

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                _requirementsLabel,
                _requirementsExamTypeLabel,
            }
        };

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    /// <summary>
    /// Actually adds the controls.
    /// </summary>
    public void Setup(
        (string, int)[] items,
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null)
    {
        foreach (var (text, value) in items)
        {
            _options.AddItem(Loc.GetString(text), value);
        }

        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.ToolTip = description;

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }

        OptionsContainer.AddChild(_options);
        OptionsContainer.AddChild(_lockStripe);
    }

    public void LockRequirements(FormattedMessage requirements)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(requirements);

        // God save the great Roman Sakutin's pattern.
        // WE'LL KEEP IT ALL IN LINES,
        // YOU DON'T FUCKING LEAVE ME, IT'S TOO LATE
        //                - TornadoTech
        var raw = requirements.ToString();
        if (raw.Contains("$IMPMDExamNotPassed"))
        {
            _lockStripe.AddStyleClass("imperialExam");
            _lockStripe.EdgeColor = Color.FromHex("#00BF1D");

#pragma warning disable RA0026
            var match = Regex.Match(raw, @"\$IMPMDExamNotPassed_(.*?)_\$");
#pragma warning restore RA0026
            var examId = match.Groups[1].Value;

            _examPrototype = examId;
            var exam = _prototype.Index<ExamPrototype>(examId);

            _requirementsExamTypeLabel.Text = $"Пройдите тест \"{Loc.GetString(exam.Name)}\"";

            _requirementsLabel.Visible = false;
            _requirementsExamTypeLabel.Visible = true;
        }
        else
        {
            if (_lockStripe.HasStyleClass("imperialExam"))
                _lockStripe.RemoveStyleClass("imperialExam");

            _lockStripe.EdgeColor = Color.FromHex("#525252ff");

            _requirementsLabel.Visible = true;
            _requirementsExamTypeLabel.Visible = false;

            _lockStripe.TooltipSupplier = _ => tooltip;
        }

        _lockStripe.Visible = true;
        _options.Visible = false;
    }

    public void UnlockRequirements()
    {
        _lockStripe.Visible = false;
        _options.Visible = true;
    }

    private Button GenerateButton(string text, int value)
    {
        return new Button
        {
            Text = text,
            MinWidth = 90,
            HorizontalExpand = true,
        };
    }

    public void Select(int id)
    {
        _options.Select(id);
    }
}
