using Content.Client.Imperial.Medieval.Trading;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.Medieval.Courier;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Courier;

[GenerateTypedNameReferences]
public sealed partial class CourierMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private StoreWithdrawWindow? _withdrawWindow;
    private CurrencyPrototype? _currency;

    public event Action<BaseButton.ButtonEventArgs, int>? OnBuyOffer;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;

    public FixedPoint2 Balance = new();

    public CourierMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
    }

    public void UpdateState(CourierUpdateState state)
    {
        Balance = state.Balance;
        _currency = _prototypeManager.TryIndex(state.Currency, out var currency) ? currency : null;

        GuildNameInfo.Text = Loc.GetString(state.GuildNameLoc);

        var balanceText = Loc.GetString(
            "store-ui-balance-display",
            ("currency", Loc.GetString("courier-ui-balance-name")),
            ("amount", state.Balance));

        BalanceInfo.SetMarkup(balanceText.Trim());
        FreeMailsInfo.Text = Loc.GetString("courier-ui-free-mails-display", ("value", state.FreeMailsCount));
        ReputationInfo.Text = Loc.GetString("courier-ui-delivery-points-display", ("value", state.DeliveryPoints));

        PopulateOffers(state.Offers, state.Balance, state.DeliveryPoints, state.FreeMailsCount);

        WithdrawButton.Disabled = state.Balance <= 0 || _currency == null || !_currency.CanWithdraw;
    }

    private void PopulateOffers(IReadOnlyList<CourierTradeOffer> offers, int balance, int deliveryPoints, int freeMailsCount)
    {
        TradingItemsContainer.Children.Clear();

        var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        for (var i = 0; i < offers.Count; i++)
        {
            var offer = offers[i];
            var canBuy = balance >= offer.BalanceCost &&
                         deliveryPoints >= offer.DeliveryPointsCost &&
                         freeMailsCount >= offer.FreeMailsCost;

            Texture? texture = null;
            if (_prototypeManager.HasIndex<EntityPrototype>(offer.ProductEntity))
                texture = spriteSystem.GetPrototypeIcon(offer.ProductEntity).Default;

            var item = new GuildTradingItem
            {
                ProductEntity = offer.ProductEntity,
                Description = string.IsNullOrWhiteSpace(offer.DescriptionLoc)
                    ? null
                    : Loc.GetString(offer.DescriptionLoc),
            };

            var control = new TradingItemControl(item, GetOfferCostString(offer), string.Empty, canBuy, texture);
            var offerIndex = i;
            control.StoreItemBuyButton.OnButtonDown += args => OnBuyOffer?.Invoke(args, offerIndex);
            TradingItemsContainer.AddChild(control);
        }
    }

    private string GetOfferCostString(CourierTradeOffer offer)
    {
        var costs = new List<string>();

        if (offer.BalanceCost > 0)
        {
            var currencyName = _currency != null
                ? Loc.GetString(_currency.DisplayName, ("amount", offer.BalanceCost))
                : Loc.GetString("courier-ui-balance-name");

            costs.Add(Loc.GetString(
                "store-ui-price-display",
                ("amount", offer.BalanceCost),
                ("currency", currencyName)).Trim());
        }

        if (offer.DeliveryPointsCost > 0)
            costs.Add(Loc.GetString("courier-ui-delivery-points-cost", ("value", offer.DeliveryPointsCost)));

        if (offer.FreeMailsCost > 0)
            costs.Add(Loc.GetString("courier-ui-free-mails-cost", ("value", offer.FreeMailsCost)));

        if (costs.Count == 0)
            return Loc.GetString("store-currency-free");

        return string.Join(" + ", costs);
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_currency == null)
            return;

        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> { { _currency, Balance } });
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }
}
