using Content.Client.Lobby;
using Content.Shared.Imperial.Medieval.Courier;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.Courier;

[GenerateTypedNameReferences]
public sealed partial class LetterRecipientEntry : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly LobbyUIController _lobby;

    public LetterRecipientEntry(LetterRecipientData data)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lobby = UserInterfaceManager.GetUIController<LobbyUIController>();

        JobPrototype? jobProto = null;
        if (!string.IsNullOrWhiteSpace(data.JobId) &&
            _proto.TryIndex<JobPrototype>(data.JobId, out var indexedJob))
        {
            jobProto = indexedJob;
        }

        var ent = _lobby.LoadProfileEntity(data.Profile, jobProto, jobProto != null);
        Character.SetEntity(ent);

        var speciesName = Loc.TryGetString($"species-{data.Profile.Species}", out var localizedSpecies)
            ? localizedSpecies
            : Loc.GetString("courier-letter-recipient-unknown-species");

        var sexName = Loc.TryGetString(
            $"humanoid-profile-editor-sex-{data.Profile.Sex.ToString().ToLowerInvariant()}-text",
            out var localizedSex)
            ? localizedSex
            : Loc.GetString("courier-letter-recipient-unknown-sex");

        RecipientName.SetMessage(data.Profile.Name);
        MainInfoTitle.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("courier-letter-recipient-main-info")));
        RecipientInfoName.SetMessage(Loc.GetString("courier-letter-recipient-name", ("name", data.Profile.Name)));
        Job.SetMessage(Loc.GetString("courier-letter-recipient-job", ("job", jobProto?.LocalizedName ?? data.JobName)));
        Species.SetMessage(Loc.GetString("courier-letter-recipient-species", ("species", speciesName)));
        Sex.SetMessage(Loc.GetString("courier-letter-recipient-sex", ("sex", sexName)));
    }
}
