using Content.Shared.Imperial.Medieval.Courier;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Courier;

[GenerateTypedNameReferences]
public sealed partial class LetterRecipientMenu : DefaultWindow
{
    public LetterRecipientMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(LetterRecipientBoundUserInterfaceState state)
    {
        Recipients.RemoveAllChildren();
        Title = Loc.GetString("courier-letter-recipient-window-title");

        if (state.Recipient == null)
        {
            var emptyLabel = new RichTextLabel();
            emptyLabel.SetMessage(Loc.GetString("courier-letter-recipient-missing"));
            Recipients.AddChild(emptyLabel);
            return;
        }

        Title = Loc.GetString("courier-letter-recipient-window-title-with-name", ("name", state.Recipient.Profile.Name));
        Recipients.AddChild(new LetterRecipientEntry(state.Recipient));
    }
}
