using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Content.Client.Lobby.UI;

namespace Content.Client.Imperial.Medieval.Flavors
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorHelpWindow : DefaultWindow
    {

        public FlavorHelpWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }
    }
}
