using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Content.Client.Message;

namespace Content.Client.Imperial.Medieval.Flavors
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorExamineWindow : DefaultWindow
    {
        [Dependency] private readonly ClientFlavorManager _flavors = default!;

        public FlavorExamineWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }
        public FlavorExamineWindow(string details, string path = "") : this()
        {
            FlavorImage.Texture = _flavors.GetImage(path).texture;
            FlavorText.SetMarkupPermissive(details);
        }
        public FlavorExamineWindow(string details, byte[]? image) : this()
        {
            FlavorImage.Texture = _flavors.GetImageFromByteArray(image).texture;
            FlavorText.SetMarkupPermissive(details);
        }
    }
}
