using System.Linq;
using Content.Shared.Imperial.Medieval.CollegiumAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.CollegiumAi.UI;

[GenerateTypedNameReferences]
public sealed partial class CollegiumAiMageListMenu : DefaultWindow
{
    /// <summary>
    /// Raised with the mage the watcher wants to jump to.
    /// </summary>
    public event Action<NetEntity>? MageSelected;

    private List<CollegiumAiMageEntry> _mages = new();

    public CollegiumAiMageListMenu()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => Rebuild();
    }

    public void Populate(List<CollegiumAiMageEntry> mages)
    {
        _mages = mages.OrderBy(mage => mage.Name).ToList();
        Rebuild();
    }

    private void Rebuild()
    {
        Mages.RemoveAllChildren();

        var filter = SearchBar.Text.Trim();

        var shown = _mages
            .Where(mage => filter.Length == 0 || mage.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (shown.Count == 0)
        {
            var empty = new RichTextLabel { Margin = new Thickness(4) };
            empty.SetMessage(Loc.GetString("collegium-ai-mage-list-empty"));
            Mages.AddChild(empty);
            return;
        }

        foreach (var mage in shown)
        {
            Mages.AddChild(BuildEntry(mage));
        }
    }

    private Button BuildEntry(CollegiumAiMageEntry mage)
    {
        var button = new Button
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 2),
            // Dead mages are listed so the watcher knows why they went quiet, but cannot be jumped to.
            Disabled = !mage.Alive,
            ToolTip = mage.Alive ? null : Loc.GetString("collegium-ai-mage-list-dead"),
        };

        var rows = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
            MouseFilter = MouseFilterMode.Ignore,
        };

        var name = new RichTextLabel { MouseFilter = MouseFilterMode.Ignore };
        if (mage.Alive)
        {
            // Plain text: a character name is player-supplied and must never be read as markup.
            name.SetMessage(mage.Name);
        }
        else
        {
            // The loc string wraps the name in colour markup and is then parsed, so the name itself must be escaped.
            name.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("collegium-ai-mage-list-dead-name", ("name", FormattedMessage.EscapeText(mage.Name)))));
        }

        rows.AddChild(name);

        if (!string.IsNullOrWhiteSpace(mage.Job))
        {
            // Passport ranks carry their own colour markup.
            var job = new RichTextLabel { MouseFilter = MouseFilterMode.Ignore };
            job.SetMessage(FormattedMessage.FromMarkupPermissive(mage.Job));
            rows.AddChild(job);
        }

        button.AddChild(rows);
        button.OnPressed += _ => MageSelected?.Invoke(mage.Entity);

        return button;
    }
}
