using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.SmithingSystem;
using Content.Shared.Imperial.Medieval.SmithingSystem.Bui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.SmithingSystem;

[GenerateTypedNameReferences]
public sealed partial class SmithingWindow : FancyWindow
{
    public event Action<SmithHitMesage>? TargetHit;
    public event Action? HitMissed;
    public event Action? TargetExpired;
    public event Action? StartGamePressed;
    public event Action<int>? GameEnded;

    private IRobustRandom _random;
    private bool _gameStarted;

    private readonly Vector2 _targetSize = new(15, 15);

    private int _totalSteps;
    private int _completedSteps;
    private int _points;

    private SmithGameData? _gameData;
    public SmithingWindow()
    {
        RobustXamlLoader.Load(this);

        _random = IoCManager.Resolve<IRobustRandom>();

        MainLayout.MouseFilter = MouseFilterMode.Pass;

        MainLayout.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || !_gameStarted)
            {
                return;
            }

            HitMissed?.Invoke();

            _points--;
            PointsLabel.Text = _points.ToString();
        };

        StartGameButton.OnPressed += _ =>
        {
            StartGamePressed?.Invoke();
            StartGameButton.Visible = false;
        };
    }
    private void CreateTarget(float grayTime, float goldTime)
    {
        var width = MainLayout.Width - MainLayout.Margin.Right;
        var height = MainLayout.Height - MainLayout.Margin.Bottom;

        var randomWidth = _random.NextFloat(MainLayout.Margin.Left + _targetSize.X / 2, width - _targetSize.X / 2);
        var randomHeight = _random.NextFloat(MainLayout.Margin.Top + _targetSize.Y, height - _targetSize.Y / 2);

        var button = new SmithTargetButton(grayTime, goldTime)
        {
            TexturePath = "/Textures/Fluids/Interface/NavMap/beveled_circle.png",
            SetSize = _targetSize,
        };

        MainLayout.AddChild(button);

        LayoutContainer.SetPosition(button, new Vector2(randomWidth, randomHeight));

        button.Clicked += (state) =>
        {
            if (state == SmithHitState.Good)
            {
                _points++;
            }

            PointsLabel.Text = _points.ToString();

            _completedSteps++;

            TargetHit?.Invoke(new SmithHitMesage(state, true));
            MainLayout.RemoveChild(button);
        };

        button.Expired += () =>
        {
            Timer.Spawn(0,
                () =>
                {
                    _points--;
                    _completedSteps++;

                    TargetExpired?.Invoke();

                    PointsLabel.Text = _points.ToString();
                    MainLayout.RemoveChild(button);
                });
        };
    }

    public void StartGame(SmithGameData gameData)
    {
        _gameData = gameData;
        _gameStarted = true;

        _totalSteps = gameData.Steps.Count;
    }

    private float _ticker;
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (!_gameStarted || _gameData == null)
        {
            return;
        }

        StepsLabel.Text = $"{_completedSteps} / {_totalSteps}";

        if (_completedSteps >= _totalSteps)
        {
            _gameStarted = false;
            GameEnded?.Invoke(_points);
        }

        if (_ticker >= _gameData.SpawnTime)
        {

            if (!_gameData.Steps.TryPop(out var targetData))
            {
                return;
            }

            CreateTarget(targetData.GoodHitTime, targetData.PerfectHitTime);

            _ticker = 0f;

            return;
        }

        _ticker += args.DeltaSeconds;
    }

    private sealed class SmithTargetButton : TextureButton
    {
        public event Action<SmithHitState>? Clicked;
        public event Action? Expired;

        private float _deltaTime;
        private int _currentStage;

        private readonly float _grayTime;
        private readonly float _goldTime;

        private bool _expired;

        private List<SpriteSpecifier> _spriteStates = new()
        {
            new SpriteSpecifier.Rsi(new ResPath("/Textures/Imperial/Medieval/Interface/sparkle.rsi"), "arrive"),
            new SpriteSpecifier.Rsi(new ResPath("/Textures/Imperial/Medieval/Interface/sparkle.rsi"), "glowing"),
            new SpriteSpecifier.Rsi(new ResPath("/Textures/Imperial/Medieval/Interface/sparkle.rsi"), "disappear"),
        };

        public SmithTargetButton(float grayTime, float goldTime)
        {
            var animTexture = new AnimatedTextureRect();
            animTexture.SetFromSpriteSpecifier(_spriteStates[_currentStage]);
            animTexture.HorizontalExpand = true;
            animTexture.VerticalExpand = true;

            AddChild(animTexture);

            _goldTime = goldTime;
            _grayTime = grayTime;

            OnPressed += _ =>
            {
                var state = _currentStage == 1 ? SmithHitState.Good : SmithHitState.Neutral;
                Clicked?.Invoke(state);
            };
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            _deltaTime += args.DeltaSeconds;

            switch (_currentStage)
            {
                case 0:
                    if (_deltaTime >= _grayTime)
                    {
                        _deltaTime = 0;
                        _currentStage = 1;
                        ModulateSelfOverride = Color.Gold;
                    }
                    break;
                case 1:
                    if (_deltaTime >= _goldTime)
                    {
                        _deltaTime = 0;
                        _currentStage = 2;
                        ModulateSelfOverride = Color.Gray;
                    }
                    break;
                case 2:
                    if (_deltaTime >= _grayTime && !_expired)
                    {
                        Expired?.Invoke();
                        _expired = true;
                    }
                    break;
            }
        }
    }
}

