using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.PlayerCreations.Books;

[GenerateTypedNameReferences]
public sealed partial class BookSendDialogWindow : DefaultWindow
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;

    private SharedPopupSystem _popup;

    public BookSendDialogWindow(Action<string, string, string>? onConfirm)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _popup = _systemManager.GetEntitySystem<SharedPopupSystem>();

        BookNameField.Placeholder = new Rope.Leaf(Loc.GetString("book-window-confirmation-name-placeholder"));
        BookDescriptionField.Placeholder = new Rope.Leaf(Loc.GetString("book-window-confirmation-description-placeholder"));
        BookAuthorField.Placeholder = new Rope.Leaf(Loc.GetString("book-window-confirmation-author-placeholder"));


        SendButton.OnPressed += _ =>
        {
            if (BookNameField.TextLength is < 3 or >= 20)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("book-window-confirmation-name-length", ("min", 3), ("max", 20)),
                        _playerManager.LocalSession);
                }

                return;
            }

            if (BookDescriptionField.TextLength >= 200)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("book-window-confirmation-description-length", ("max", 200)),
                        _playerManager.LocalSession);
                }

                return;
            }

            if (BookAuthorField.TextLength is < 5 or >= 40)
            {
                if (_playerManager.LocalSession != null)
                {
                    _popup.PopupCursor(Loc.GetString("book-window-confirmation-author-length", ("min", 5), ("max", 40)),
                        _playerManager.LocalSession);
                }

                return;
            }

            var name = Rope.Collapse(BookNameField.TextRope);
            var description = Rope.Collapse(BookDescriptionField.TextRope);
            var author = Rope.Collapse(BookAuthorField.TextRope);

            onConfirm?.Invoke(name, description, author);
            Close();
        };

    }


}
