using System.Numerics;
using Content.Shared.Storage;
using Content.Shared.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.Trade.UI;

[GenerateTypedNameReferences]
public sealed partial class TradeTerminalWindow : DefaultWindow
{
    public event Action<NetEntity>? OnCall;
    public event Action? OnAccept;
    public event Action? OnHangUp;
    public event Action? OnConfirm;
    public event Action? OnCancel;
    public event Action<ItemStorageLocation, int>? OnInsertAt;
    public event Action<NetEntity>? OnRemoveItem;

    private bool _isCountingDown;
    private bool _compactTradeLayout;
    private TimeSpan _endTime;
    private float _maxDuration;

    private readonly IGameTiming _timing;

    public TradeTerminalWindow(EntityUid terminal)
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
        Resizable = true;

        BtnHangUpCalling.Text = Loc.GetString("trade-terminal-btn-hang-up");
        BtnAccept.Text = Loc.GetString("trade-terminal-btn-accept");
        BtnDecline.Text = Loc.GetString("trade-terminal-btn-decline");
        BtnHangUp.Text = Loc.GetString("trade-terminal-btn-hang-up");
        BtnCancel.Text = Loc.GetString("trade-terminal-btn-cancel");
        BtnConfirm.Text = Loc.GetString("trade-terminal-btn-confirm");

        LblDirTitle.Text = Loc.GetString("trade-terminal-dir-title");
        LblDirHint.Text = Loc.GetString("trade-terminal-dir-hint");
        LblInsertHint.Text = Loc.GetString("trade-terminal-insert-hint");
        LblPartnerHint.Text = Loc.GetString("trade-terminal-partner-hint");

        BtnAccept.OnPressed += _ => OnAccept?.Invoke();
        BtnDecline.OnPressed += _ => OnHangUp?.Invoke();
        BtnHangUpCalling.OnPressed += _ => OnHangUp?.Invoke();
        BtnHangUp.OnPressed += _ => OnHangUp?.Invoke();
        BtnConfirm.OnPressed += _ => OnConfirm?.Invoke();
        BtnCancel.OnPressed += _ => OnCancel?.Invoke();

        OwnOfferGrid.SetStorageEntity(terminal);
        OwnOfferGrid.OnInsertAt += (location, amount) => OnInsertAt?.Invoke(location, amount);
        OwnOfferGrid.OnRemoveItem += item => OnRemoveItem?.Invoke(item);

        ApplyFantasyStyling();
    }

    public void UpdateState(TradeBuiState state)
    {
        _isCountingDown = state.OwnState == TradeSessionState.Countdown;
        _endTime = state.CountdownEndTime;
        _maxDuration = state.CountdownDuration;
        Title = Loc.GetString("trade-terminal-window-title", ("name", state.OwnName));

        PanelDirectory.Visible = state.OwnState == TradeSessionState.Idle;
        PanelCalling.Visible = state.OwnState == TradeSessionState.Calling;
        PanelRinging.Visible = state.OwnState == TradeSessionState.Ringing;
        PanelTrade.Visible = state.OwnState is TradeSessionState.Active
                                                 or TradeSessionState.Countdown
                                                 or TradeSessionState.Completed;

        switch (state.OwnState)
        {
            case TradeSessionState.Idle:
                DrawDirectory(state);
                break;

            case TradeSessionState.Calling:
                LblCallingTitle.Text = Loc.GetString(
                    "trade-terminal-calling-label",
                    ("target", state.PartnerName ?? "???"));
                break;

            case TradeSessionState.Ringing:
                LblRingingTitle.Text = Loc.GetString(
                    "trade-terminal-ringing-label",
                    ("caller", state.IncomingCallerName ?? "???"));
                break;

            case TradeSessionState.Active:
            case TradeSessionState.Countdown:
            case TradeSessionState.Completed:
                DrawTradePanel(state);
                break;
        }
    }

    private void DrawDirectory(TradeBuiState state)
    {
        DirectoryList.RemoveAllChildren();

        if (state.Directory.Count == 0)
        {
            DirectoryList.AddChild(new Label
            {
                Text = Loc.GetString("trade-terminal-dir-empty"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var entry in state.Directory)
            DirectoryList.AddChild(MakeDirectoryRow(entry));
    }

    private Control MakeDirectoryRow(TradeTerminalDto entry)
    {
        var isFree = entry.State == TradeSessionState.Idle;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 5),
        };

        row.AddChild(new Label
        {
            Text = "*",
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 6, 0),
            ModulateSelfOverride = isFree
                ? Color.FromHex("#44ff88")
                : Color.FromHex("#ff5555"),
        });

        row.AddChild(new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });

        row.AddChild(new Label
        {
            Text = isFree
                ? Loc.GetString("trade-terminal-dir-free")
                : Loc.GetString("trade-terminal-dir-busy"),
            StyleClasses = { "LabelSubText" },
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        });

        var button = new Button
        {
            Text = Loc.GetString("trade-terminal-btn-call"),
            Disabled = !isFree,
            MinWidth = 80,
        };
        var captured = entry.Entity;
        button.OnPressed += _ => OnCall?.Invoke(captured);
        row.AddChild(button);

        return new PanelContainer
        {
            Margin = new Thickness(0, 0, 0, 4),
            PanelOverride = MakePanelStyle(
                isFree ? "#19130f" : "#181013",
                isFree ? "#7e6336" : "#7a4b43",
                1),
            Children =
            {
                row,
            },
        };
    }

    private void DrawTradePanel(TradeBuiState state)
    {
        var isActive = state.OwnState == TradeSessionState.Active;
        var canInsert = isActive && !state.OwnConfirmed;
        var canTakeItems = state.OwnState == TradeSessionState.Completed;

        LblOwnColumn.Text = Loc.GetString("trade-terminal-col-own");

        var partnerNameStr = state.PartnerName != null
            ? Loc.GetString("trade-terminal-col-partner-named", ("name", state.PartnerName))
            : Loc.GetString("trade-terminal-col-partner");

        if (state.PartnerConfirmed)
            partnerNameStr += $" [{Loc.GetString("trade-terminal-ready")}]";

        LblPartnerColumn.Text = partnerNameStr;

        LblInsertHint.Visible = canInsert || canTakeItems;
        LblInsertHint.Text = canTakeItems
            ? Loc.GetString("trade-terminal-take-hint")
            : Loc.GetString("trade-terminal-insert-hint");

        OwnOfferGrid.UpdateOffer(state.OwnGrid, state.OwnItems, canInsert, canInsert || canTakeItems);
        PartnerOfferGrid.UpdateOffer(state.PartnerGrid, state.PartnerItems, canInsert: false, canRemove: false);

        DrawStatus(state);

        BtnConfirm.Disabled = !isActive;
        BtnCancel.Disabled = state.OwnState == TradeSessionState.Completed;
        BtnHangUp.Disabled = state.OwnState == TradeSessionState.Completed;

        if (state.OwnState == TradeSessionState.Countdown)
        {
            BtnConfirm.Text = Loc.GetString("trade-terminal-btn-confirm-waiting");
            SetConfirmButtonStyle("Constructive", "Caution");
        }
        else if (state.OwnConfirmed)
        {
            BtnConfirm.Text = Loc.GetString("trade-terminal-btn-unconfirm");
            SetConfirmButtonStyle("Caution", "Constructive");
        }
        else
        {
            BtnConfirm.Text = Loc.GetString("trade-terminal-btn-confirm");
            SetConfirmButtonStyle("Constructive", "Caution");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateResponsiveLayout();

        if (!_isCountingDown || _maxDuration <= 0)
            return;

        var remainingSeconds = (float) (_endTime - _timing.CurTime).TotalSeconds;

        if (remainingSeconds < 0)
            remainingSeconds = 0;

        LblCountdown.Text = Loc.GetString(
            "trade-terminal-countdown-label",
            ("seconds", (int) MathF.Ceiling(remainingSeconds)));

        BarCountdown.Value = remainingSeconds / _maxDuration;
    }

    private void UpdateResponsiveLayout()
    {
        var compact = PixelWidth is > 0 and < 620;
        if (compact == _compactTradeLayout)
            return;

        _compactTradeLayout = compact;
        TradeColumns.Orientation = compact
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;

        OwnOfferPanel.MinSize = compact ? new Vector2(0, 236) : new Vector2(272, 0);
        PartnerOfferPanel.MinSize = compact ? new Vector2(0, 236) : new Vector2(272, 0);

        OwnOfferPanel.Margin = compact
            ? new Thickness(0, 0, 0, 4)
            : new Thickness(0, 0, 4, 0);

        PartnerOfferPanel.Margin = compact
            ? new Thickness(0, 4, 0, 0)
            : new Thickness(4, 0, 0, 0);

        TradeDivider.MinSize = compact ? new Vector2(0, 1) : new Vector2(1, 0);
        TradeDivider.HorizontalExpand = compact;
        TradeDivider.VerticalExpand = !compact;
        TradeDivider.Margin = compact
            ? new Thickness(0, 0, 0, 0)
            : new Thickness(0, 3);
    }

    private void DrawStatus(TradeBuiState state)
    {
        switch (state.OwnState)
        {
            case TradeSessionState.Active:
                LblStatus.Text = Loc.GetString("trade-terminal-status-active");
                LblCountdown.Visible = false;
                BarCountdown.Visible = false;
                break;

            case TradeSessionState.Countdown:
                LblStatus.Text = Loc.GetString(
                    "trade-terminal-status-countdown",
                    ("name", state.ConfirmedByName ?? "???"));

                LblCountdown.Visible = true;
                BarCountdown.Visible = true;
                break;

            case TradeSessionState.Completed:
                LblStatus.Text = Loc.GetString("trade-terminal-status-completed");
                LblCountdown.Visible = false;
                BarCountdown.Visible = false;
                break;
        }
    }

    private void SetConfirmButtonStyle(string keepClass, string removeClass)
    {
        while (BtnConfirm.StyleClasses.Remove(keepClass))
        {
        }

        while (BtnConfirm.StyleClasses.Remove(removeClass))
        {
        }

        BtnConfirm.StyleClasses.Add(keepClass);
    }

    private void ApplyFantasyStyling()
    {
        DirectoryCard.PanelOverride = MakePanelStyle("#17100d", "#84623b", 2);
        DirectoryHeaderBand.PanelOverride = MakePanelStyle("#261a12", "#ab7f49", 1);
        DirectoryListFrame.PanelOverride = MakePanelStyle("#0f0b09", "#5b4428", 1);
        CallingCard.PanelOverride = MakePanelStyle("#17110d", "#936e3c", 2);
        RingingCard.PanelOverride = MakePanelStyle("#161018", "#836847", 2);
        TradeStatusPanel.PanelOverride = MakePanelStyle("#201610", "#977142", 2);
        OwnOfferPanel.PanelOverride = MakePanelStyle("#18110d", "#9b7640", 2);
        OwnHeaderBand.PanelOverride = MakePanelStyle("#2a1c11", "#b48a52", 1);
        OwnGridFrame.PanelOverride = MakePanelStyle("#100b08", "#6a512b", 1);
        OwnHintBand.PanelOverride = MakePanelStyle("#1d140f", "#624a2d", 1);
        PartnerOfferPanel.PanelOverride = MakePanelStyle("#141218", "#7f6840", 2);
        PartnerHeaderBand.PanelOverride = MakePanelStyle("#231c20", "#927452", 1);
        PartnerGridFrame.PanelOverride = MakePanelStyle("#0f0d12", "#5f5138", 1);
        PartnerHintBand.PanelOverride = MakePanelStyle("#17141a", "#51463a", 1);
        TradeActionPanel.PanelOverride = MakePanelStyle("#1a1310", "#7d5c35", 2);
        TradeDivider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#76592f"),
        };

        LblDirTitle.ModulateSelfOverride = Color.FromHex("#e3be7c");
        LblDirHint.ModulateSelfOverride = Color.FromHex("#c4aa82");
        LblCallingTitle.ModulateSelfOverride = Color.FromHex("#e4c183");
        LblRingingTitle.ModulateSelfOverride = Color.FromHex("#e4c183");
        LblOwnColumn.ModulateSelfOverride = Color.FromHex("#f0cf92");
        LblPartnerColumn.ModulateSelfOverride = Color.FromHex("#dec58f");
        LblStatus.ModulateSelfOverride = Color.FromHex("#e8d5b0");
        LblInsertHint.ModulateSelfOverride = Color.FromHex("#d1b78a");
        LblPartnerHint.ModulateSelfOverride = Color.FromHex("#b8a687");
        LblCountdown.ModulateSelfOverride = Color.FromHex("#f2d590");

        BtnHangUp.ModulateSelfOverride = Color.FromHex("#cdb58d");
        BtnConfirm.ModulateSelfOverride = Color.FromHex("#e1c889");
        BtnCancel.ModulateSelfOverride = Color.FromHex("#cb9688");
        BtnHangUpCalling.ModulateSelfOverride = Color.FromHex("#d7bf8c");
        BtnAccept.ModulateSelfOverride = Color.FromHex("#d9c591");
        BtnDecline.ModulateSelfOverride = Color.FromHex("#cf9c8d");
    }

    private static StyleBoxFlat MakePanelStyle(string background, string border, int thickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(thickness),
            ContentMarginLeftOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginBottomOverride = 4,
        };
    }
}
